package com.composables.icons.fontawesome.regular

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.fontawesome.FontAwesome
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val FontAwesome.Regular.ObjectUngroup: ImageVector
    get() {
        if (_ObjectUngroup != null) return _ObjectUngroup!!
        
        _ObjectUngroup = ImageVector.Builder(
            name = "object-ungroup",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 576f,
            viewportHeight = 512f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(564f, 224f)
                curveToRelative(6.627f, 0f, 12f, -5.373f, 12f, -12f)
                verticalLineToRelative(-72f)
                curveToRelative(0f, -6.627f, -5.373f, -12f, -12f, -12f)
                horizontalLineToRelative(-72f)
                curveToRelative(-6.627f, 0f, -12f, 5.373f, -12f, 12f)
                verticalLineToRelative(12f)
                horizontalLineToRelative(-88f)
                verticalLineToRelative(-24f)
                horizontalLineToRelative(12f)
                curveToRelative(6.627f, 0f, 12f, -5.373f, 12f, -12f)
                verticalLineTo(44f)
                curveToRelative(0f, -6.627f, -5.373f, -12f, -12f, -12f)
                horizontalLineToRelative(-72f)
                curveToRelative(-6.627f, 0f, -12f, 5.373f, -12f, 12f)
                verticalLineToRelative(12f)
                horizontalLineTo(96f)
                verticalLineTo(44f)
                curveToRelative(0f, -6.627f, -5.373f, -12f, -12f, -12f)
                horizontalLineTo(12f)
                curveTo(5.373f, 32f, 0f, 37.373f, 0f, 44f)
                verticalLineToRelative(72f)
                curveToRelative(0f, 6.627f, 5.373f, 12f, 12f, 12f)
                horizontalLineToRelative(12f)
                verticalLineToRelative(160f)
                horizontalLineTo(12f)
                curveToRelative(-6.627f, 0f, -12f, 5.373f, -12f, 12f)
                verticalLineToRelative(72f)
                curveToRelative(0f, 6.627f, 5.373f, 12f, 12f, 12f)
                horizontalLineToRelative(72f)
                curveToRelative(6.627f, 0f, 12f, -5.373f, 12f, -12f)
                verticalLineToRelative(-12f)
                horizontalLineToRelative(88f)
                verticalLineToRelative(24f)
                horizontalLineToRelative(-12f)
                curveToRelative(-6.627f, 0f, -12f, 5.373f, -12f, 12f)
                verticalLineToRelative(72f)
                curveToRelative(0f, 6.627f, 5.373f, 12f, 12f, 12f)
                horizontalLineToRelative(72f)
                curveToRelative(6.627f, 0f, 12f, -5.373f, 12f, -12f)
                verticalLineToRelative(-12f)
                horizontalLineToRelative(224f)
                verticalLineToRelative(12f)
                curveToRelative(0f, 6.627f, 5.373f, 12f, 12f, 12f)
                horizontalLineToRelative(72f)
                curveToRelative(6.627f, 0f, 12f, -5.373f, 12f, -12f)
                verticalLineToRelative(-72f)
                curveToRelative(0f, -6.627f, -5.373f, -12f, -12f, -12f)
                horizontalLineToRelative(-12f)
                verticalLineTo(224f)
                horizontalLineToRelative(12f)
                close()
                moveTo(352f, 64f)
                horizontalLineToRelative(32f)
                verticalLineToRelative(32f)
                horizontalLineToRelative(-32f)
                verticalLineTo(64f)
                close()
                moveToRelative(0f, 256f)
                horizontalLineToRelative(32f)
                verticalLineToRelative(32f)
                horizontalLineToRelative(-32f)
                verticalLineToRelative(-32f)
                close()
                moveTo(64f, 352f)
                horizontalLineTo(32f)
                verticalLineToRelative(-32f)
                horizontalLineToRelative(32f)
                verticalLineToRelative(32f)
                close()
                moveToRelative(0f, -256f)
                horizontalLineTo(32f)
                verticalLineTo(64f)
                horizontalLineToRelative(32f)
                verticalLineToRelative(32f)
                close()
                moveToRelative(32f, 216f)
                verticalLineToRelative(-12f)
                curveToRelative(0f, -6.627f, -5.373f, -12f, -12f, -12f)
                horizontalLineTo(72f)
                verticalLineTo(128f)
                horizontalLineToRelative(12f)
                curveToRelative(6.627f, 0f, 12f, -5.373f, 12f, -12f)
                verticalLineToRelative(-12f)
                horizontalLineToRelative(224f)
                verticalLineToRelative(12f)
                curveToRelative(0f, 6.627f, 5.373f, 12f, 12f, 12f)
                horizontalLineToRelative(12f)
                verticalLineToRelative(160f)
                horizontalLineToRelative(-12f)
                curveToRelative(-6.627f, 0f, -12f, 5.373f, -12f, 12f)
                verticalLineToRelative(12f)
                horizontalLineTo(96f)
                close()
                moveToRelative(128f, 136f)
                horizontalLineToRelative(-32f)
                verticalLineToRelative(-32f)
                horizontalLineToRelative(32f)
                verticalLineToRelative(32f)
                close()
                moveToRelative(280f, -64f)
                horizontalLineToRelative(-12f)
                curveToRelative(-6.627f, 0f, -12f, 5.373f, -12f, 12f)
                verticalLineToRelative(12f)
                horizontalLineTo(256f)
                verticalLineToRelative(-12f)
                curveToRelative(0f, -6.627f, -5.373f, -12f, -12f, -12f)
                horizontalLineToRelative(-12f)
                verticalLineToRelative(-24f)
                horizontalLineToRelative(88f)
                verticalLineToRelative(12f)
                curveToRelative(0f, 6.627f, 5.373f, 12f, 12f, 12f)
                horizontalLineToRelative(72f)
                curveToRelative(6.627f, 0f, 12f, -5.373f, 12f, -12f)
                verticalLineToRelative(-72f)
                curveToRelative(0f, -6.627f, -5.373f, -12f, -12f, -12f)
                horizontalLineToRelative(-12f)
                verticalLineToRelative(-88f)
                horizontalLineToRelative(88f)
                verticalLineToRelative(12f)
                curveToRelative(0f, 6.627f, 5.373f, 12f, 12f, 12f)
                horizontalLineToRelative(12f)
                verticalLineToRelative(160f)
                close()
                moveToRelative(40f, 64f)
                horizontalLineToRelative(-32f)
                verticalLineToRelative(-32f)
                horizontalLineToRelative(32f)
                verticalLineToRelative(32f)
                close()
                moveToRelative(0f, -256f)
                horizontalLineToRelative(-32f)
                verticalLineToRelative(-32f)
                horizontalLineToRelative(32f)
                verticalLineToRelative(32f)
                close()
            }
        }.build()
        
        return _ObjectUngroup!!
    }

private var _ObjectUngroup: ImageVector? = null

