package com.composables.icons.bootstrap.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.bootstrap.Bootstrap
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Bootstrap.Outline.BorderInner: ImageVector
    get() {
        if (_BorderInner != null) return _BorderInner!!
        
        _BorderInner = ImageVector.Builder(
            name = "border-inner",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 16f,
            viewportHeight = 16f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(0.969f, 0f)
                horizontalLineTo(0f)
                verticalLineToRelative(0.969f)
                horizontalLineToRelative(0.5f)
                verticalLineTo(1f)
                horizontalLineToRelative(0.469f)
                verticalLineTo(0.969f)
                horizontalLineTo(1f)
                verticalLineTo(0.5f)
                horizontalLineTo(0.969f)
                close()
                moveToRelative(0.937f, 1f)
                horizontalLineToRelative(0.938f)
                verticalLineTo(0f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineTo(0f)
                horizontalLineTo(3.78f)
                verticalLineToRelative(1f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineTo(0f)
                horizontalLineToRelative(-0.938f)
                close()
            }
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(8.5f, 7.5f)
                horizontalLineTo(16f)
                verticalLineToRelative(1f)
                horizontalLineTo(8.5f)
                verticalLineTo(16f)
                horizontalLineToRelative(-1f)
                verticalLineTo(8.5f)
                horizontalLineTo(0f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(7.5f)
                verticalLineTo(0f)
                horizontalLineToRelative(1f)
                close()
            }
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(9.406f, 1f)
                horizontalLineToRelative(0.938f)
                verticalLineTo(0f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineTo(0f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineTo(0f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.469f)
                verticalLineTo(0.969f)
                horizontalLineToRelative(0.5f)
                verticalLineTo(0f)
                horizontalLineToRelative(-0.969f)
                verticalLineToRelative(0.5f)
                horizontalLineTo(15f)
                verticalLineToRelative(0.469f)
                horizontalLineToRelative(0.031f)
                close()
                moveTo(1f, 2.844f)
                verticalLineToRelative(-0.938f)
                horizontalLineTo(0f)
                verticalLineToRelative(0.938f)
                close()
                moveToRelative(14f, -0.938f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.938f)
                close()
                moveTo(1f, 4.719f)
                verticalLineTo(3.78f)
                horizontalLineTo(0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                close()
                moveToRelative(14f, -0.938f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineTo(3.78f)
                horizontalLineToRelative(-1f)
                close()
                moveTo(1f, 6.594f)
                verticalLineToRelative(-0.938f)
                horizontalLineTo(0f)
                verticalLineToRelative(0.938f)
                close()
                moveToRelative(14f, -0.938f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.938f)
                close()
                moveTo(0f, 9.406f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.938f)
                close()
                moveToRelative(16f, 0.938f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(0.938f)
                close()
                moveToRelative(-16f, 0.937f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.938f)
                close()
                moveToRelative(16f, 0.938f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(0.938f)
                close()
                moveToRelative(-16f, 0.937f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.938f)
                close()
                moveToRelative(16f, 0.938f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(0.938f)
                close()
                moveTo(0f, 16f)
                horizontalLineToRelative(0.969f)
                verticalLineToRelative(-0.5f)
                horizontalLineTo(1f)
                verticalLineToRelative(-0.469f)
                horizontalLineTo(0.969f)
                verticalLineTo(15f)
                horizontalLineTo(0.5f)
                verticalLineToRelative(0.031f)
                horizontalLineTo(0f)
                close()
                moveToRelative(1.906f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineTo(3.78f)
                verticalLineToRelative(1f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(3.75f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, -0.5f)
                verticalLineToRelative(0.5f)
                horizontalLineTo(16f)
                verticalLineToRelative(-0.969f)
                horizontalLineToRelative(-0.5f)
                verticalLineTo(15f)
                horizontalLineToRelative(-0.469f)
                verticalLineToRelative(0.031f)
                horizontalLineTo(15f)
                verticalLineToRelative(0.469f)
                close()
            }
        }.build()
        
        return _BorderInner!!
    }

private var _BorderInner: ImageVector? = null

