package com.composables.icons.bootstrap.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.bootstrap.Bootstrap
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Bootstrap.Outline.BorderLeft: ImageVector
    get() {
        if (_BorderLeft != null) return _BorderLeft!!
        
        _BorderLeft = ImageVector.Builder(
            name = "border-left",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 16f,
            viewportHeight = 16f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(0f, 0f)
                verticalLineToRelative(16f)
                horizontalLineToRelative(1f)
                verticalLineTo(0f)
                close()
                moveToRelative(1.906f, 1f)
                horizontalLineToRelative(0.938f)
                verticalLineTo(0f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineTo(0f)
                horizontalLineTo(3.78f)
                verticalLineToRelative(1f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineTo(0f)
                horizontalLineToRelative(-0.938f)
                close()
                moveTo(7.531f, 0.969f)
                verticalLineTo(1f)
                horizontalLineToRelative(0.938f)
                verticalLineTo(0.969f)
                horizontalLineTo(8.5f)
                verticalLineTo(0.5f)
                horizontalLineToRelative(-0.031f)
                verticalLineTo(0f)
                horizontalLineTo(7.53f)
                verticalLineToRelative(0.5f)
                horizontalLineTo(7.5f)
                verticalLineToRelative(0.469f)
                close()
                moveTo(9.406f, 1f)
                horizontalLineToRelative(0.938f)
                verticalLineTo(0f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineTo(0f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineTo(0f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.469f)
                verticalLineTo(0.969f)
                horizontalLineToRelative(0.5f)
                verticalLineTo(0f)
                horizontalLineToRelative(-0.969f)
                verticalLineToRelative(0.5f)
                horizontalLineTo(15f)
                verticalLineToRelative(0.469f)
                horizontalLineToRelative(0.031f)
                close()
                moveTo(7.5f, 1.906f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.938f)
                close()
                moveToRelative(7.5f, 0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.938f)
                close()
                moveTo(7.5f, 3.781f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineTo(3.78f)
                horizontalLineToRelative(-1f)
                close()
                moveToRelative(7.5f, 0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineTo(3.78f)
                horizontalLineToRelative(-1f)
                close()
                moveTo(7.5f, 5.656f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.938f)
                close()
                moveToRelative(7.5f, 0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.938f)
                close()
                moveTo(1.906f, 8.5f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineTo(3.78f)
                verticalLineToRelative(1f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(2.813f, 0f)
                verticalLineToRelative(-0.031f)
                horizontalLineTo(8.5f)
                verticalLineTo(7.53f)
                horizontalLineToRelative(-0.031f)
                verticalLineTo(7.5f)
                horizontalLineTo(7.53f)
                verticalLineToRelative(0.031f)
                horizontalLineTo(7.5f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(0.031f)
                verticalLineTo(8.5f)
                close()
                moveToRelative(0.937f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.469f)
                verticalLineToRelative(-0.031f)
                horizontalLineToRelative(0.5f)
                verticalLineTo(7.53f)
                horizontalLineToRelative(-0.5f)
                verticalLineTo(7.5f)
                horizontalLineToRelative(-0.469f)
                verticalLineToRelative(0.031f)
                horizontalLineTo(15f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(0.031f)
                close()
                moveTo(7.5f, 9.406f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.938f)
                close()
                moveToRelative(8.5f, 0.938f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(0.938f)
                close()
                moveToRelative(-8.5f, 0.937f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.938f)
                close()
                moveToRelative(8.5f, 0.938f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(0.938f)
                close()
                moveToRelative(-8.5f, 0.937f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.938f)
                close()
                moveToRelative(8.5f, 0.938f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(0.938f)
                close()
                moveTo(1.906f, 16f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineTo(3.78f)
                verticalLineToRelative(1f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, -0.5f)
                verticalLineToRelative(0.5f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-0.5f)
                horizontalLineTo(8.5f)
                verticalLineToRelative(-0.469f)
                horizontalLineToRelative(-0.031f)
                verticalLineTo(15f)
                horizontalLineTo(7.53f)
                verticalLineToRelative(0.031f)
                horizontalLineTo(7.5f)
                verticalLineToRelative(0.469f)
                close()
                moveToRelative(1.875f, 0.5f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, 0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.938f)
                close()
                moveToRelative(1.875f, -0.5f)
                verticalLineToRelative(0.5f)
                horizontalLineTo(16f)
                verticalLineToRelative(-0.969f)
                horizontalLineToRelative(-0.5f)
                verticalLineTo(15f)
                horizontalLineToRelative(-0.469f)
                verticalLineToRelative(0.031f)
                horizontalLineTo(15f)
                verticalLineToRelative(0.469f)
                close()
            }
        }.build()
        
        return _BorderLeft!!
    }

private var _BorderLeft: ImageVector? = null

