package com.composables.icons.bootstrap.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.bootstrap.Bootstrap
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Bootstrap.Outline.PlusSquareDotted: ImageVector
    get() {
        if (_PlusSquareDotted != null) return _PlusSquareDotted!!
        
        _PlusSquareDotted = ImageVector.Builder(
            name = "plus-square-dotted",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 16f,
            viewportHeight = 16f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(2.5f, 0f)
                quadToRelative(-0.25f, 0f, -0.487f, 0.048f)
                lineToRelative(0.194f, 0.98f)
                arcTo(1.5f, 1.5f, 0f, false, true, 2.5f, 1f)
                horizontalLineToRelative(0.458f)
                verticalLineTo(0f)
                close()
                moveToRelative(2.292f, 0f)
                horizontalLineToRelative(-0.917f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(0.917f)
                close()
                moveToRelative(1.833f, 0f)
                horizontalLineToRelative(-0.917f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(0.917f)
                close()
                moveToRelative(1.833f, 0f)
                horizontalLineToRelative(-0.916f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(0.916f)
                close()
                moveToRelative(1.834f, 0f)
                horizontalLineToRelative(-0.917f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(0.917f)
                close()
                moveToRelative(1.833f, 0f)
                horizontalLineToRelative(-0.917f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(0.917f)
                close()
                moveTo(13.5f, 0f)
                horizontalLineToRelative(-0.458f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(0.458f)
                quadToRelative(0.151f, 0f, 0.293f, 0.029f)
                lineToRelative(0.194f, -0.981f)
                arcTo(2.5f, 2.5f, 0f, false, false, 13.5f, 0f)
                moveToRelative(2.079f, 1.11f)
                arcToRelative(2.5f, 2.5f, 0f, false, false, -0.69f, -0.689f)
                lineToRelative(-0.556f, 0.831f)
                quadToRelative(0.248f, 0.167f, 0.415f, 0.415f)
                lineToRelative(0.83f, -0.556f)
                close()
                moveTo(1.11f, 0.421f)
                arcToRelative(2.5f, 2.5f, 0f, false, false, -0.689f, 0.69f)
                lineToRelative(0.831f, 0.556f)
                curveToRelative(0.11f, -0.164f, 0.251f, -0.305f, 0.415f, -0.415f)
                close()
                moveTo(16f, 2.5f)
                quadToRelative(0f, -0.25f, -0.048f, -0.487f)
                lineToRelative(-0.98f, 0.194f)
                quadToRelative(0.027f, 0.141f, 0.028f, 0.293f)
                verticalLineToRelative(0.458f)
                horizontalLineToRelative(1f)
                close()
                moveTo(0.048f, 2.013f)
                arcTo(2.5f, 2.5f, 0f, false, false, 0f, 2.5f)
                verticalLineToRelative(0.458f)
                horizontalLineToRelative(1f)
                verticalLineTo(2.5f)
                quadToRelative(0f, -0.151f, 0.029f, -0.293f)
                close()
                moveTo(0f, 3.875f)
                verticalLineToRelative(0.917f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.917f)
                close()
                moveToRelative(16f, 0.917f)
                verticalLineToRelative(-0.917f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(0.917f)
                close()
                moveTo(0f, 5.708f)
                verticalLineToRelative(0.917f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.917f)
                close()
                moveToRelative(16f, 0.917f)
                verticalLineToRelative(-0.917f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(0.917f)
                close()
                moveTo(0f, 7.542f)
                verticalLineToRelative(0.916f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.916f)
                close()
                moveToRelative(15f, 0.916f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.916f)
                horizontalLineToRelative(-1f)
                close()
                moveTo(0f, 9.375f)
                verticalLineToRelative(0.917f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.917f)
                close()
                moveToRelative(16f, 0.917f)
                verticalLineToRelative(-0.917f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(0.917f)
                close()
                moveToRelative(-16f, 0.916f)
                verticalLineToRelative(0.917f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.917f)
                close()
                moveToRelative(16f, 0.917f)
                verticalLineToRelative(-0.917f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(0.917f)
                close()
                moveToRelative(-16f, 0.917f)
                verticalLineToRelative(0.458f)
                quadToRelative(0f, 0.25f, 0.048f, 0.487f)
                lineToRelative(0.98f, -0.194f)
                arcTo(1.5f, 1.5f, 0f, false, true, 1f, 13.5f)
                verticalLineToRelative(-0.458f)
                close()
                moveToRelative(16f, 0.458f)
                verticalLineToRelative(-0.458f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(0.458f)
                quadToRelative(0f, 0.151f, -0.029f, 0.293f)
                lineToRelative(0.981f, 0.194f)
                quadTo(16f, 13.75f, 16f, 13.5f)
                moveTo(0.421f, 14.89f)
                curveToRelative(0.183f, 0.272f, 0.417f, 0.506f, 0.69f, 0.689f)
                lineToRelative(0.556f, -0.831f)
                arcToRelative(1.5f, 1.5f, 0f, false, true, -0.415f, -0.415f)
                close()
                moveToRelative(14.469f, 0.689f)
                curveToRelative(0.272f, -0.183f, 0.506f, -0.417f, 0.689f, -0.69f)
                lineToRelative(-0.831f, -0.556f)
                curveToRelative(-0.11f, 0.164f, -0.251f, 0.305f, -0.415f, 0.415f)
                lineToRelative(0.556f, 0.83f)
                close()
                moveToRelative(-12.877f, 0.373f)
                quadTo(2.25f, 16f, 2.5f, 16f)
                horizontalLineToRelative(0.458f)
                verticalLineToRelative(-1f)
                horizontalLineTo(2.5f)
                quadToRelative(-0.151f, 0f, -0.293f, -0.029f)
                close()
                moveTo(13.5f, 16f)
                quadToRelative(0.25f, 0f, 0.487f, -0.048f)
                lineToRelative(-0.194f, -0.98f)
                arcTo(1.5f, 1.5f, 0f, false, true, 13.5f, 15f)
                horizontalLineToRelative(-0.458f)
                verticalLineToRelative(1f)
                close()
                moveToRelative(-9.625f, 0f)
                horizontalLineToRelative(0.917f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.917f)
                close()
                moveToRelative(1.833f, 0f)
                horizontalLineToRelative(0.917f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.917f)
                close()
                moveToRelative(1.834f, -1f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(0.916f)
                verticalLineToRelative(-1f)
                close()
                moveToRelative(1.833f, 1f)
                horizontalLineToRelative(0.917f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.917f)
                close()
                moveToRelative(1.833f, 0f)
                horizontalLineToRelative(0.917f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-0.917f)
                close()
                moveTo(8.5f, 4.5f)
                arcToRelative(0.5f, 0.5f, 0f, false, false, -1f, 0f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(-3f)
                arcToRelative(0.5f, 0.5f, 0f, false, false, 0f, 1f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(3f)
                arcToRelative(0.5f, 0.5f, 0f, false, false, 1f, 0f)
                verticalLineToRelative(-3f)
                horizontalLineToRelative(3f)
                arcToRelative(0.5f, 0.5f, 0f, false, false, 0f, -1f)
                horizontalLineToRelative(-3f)
                close()
            }
        }.build()
        
        return _PlusSquareDotted!!
    }

private var _PlusSquareDotted: ImageVector? = null

