package com.composables.icons.materialsymbols.outlinedfilled

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.OutlinedFilled.Glyphs: ImageVector
    get() {
        if (_Glyphs != null) return _Glyphs!!
        
        _Glyphs = ImageVector.Builder(
            name = "glyphs",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(224f, 82f)
                horizontalLineToRelative(78f)
                lineToRelative(135f, 360f)
                horizontalLineToRelative(-75f)
                lineToRelative(-30f, -86f)
                horizontalLineTo(194f)
                lineToRelative(-30f, 86f)
                horizontalLineTo(89f)
                lineToRelative(135f, -360f)
                close()
                moveToRelative(5f, 402f)
                quadToRelative(42f, 0f, 71f, 29f)
                reflectiveQuadToRelative(29f, 71f)
                quadToRelative(0f, 20f, -7.5f, 38.5f)
                reflectiveQuadTo(300f, 655f)
                lineToRelative(-15f, 14f)
                lineToRelative(28f, 28f)
                lineToRelative(57f, -56f)
                lineToRelative(57f, 57f)
                lineToRelative(-56f, 56f)
                lineToRelative(56f, 57f)
                lineToRelative(-57f, 56f)
                lineToRelative(-56f, -56f)
                lineToRelative(-42f, 42f)
                quadToRelative(-15f, 15f, -34f, 22.5f)
                reflectiveQuadTo(198f, 883f)
                quadToRelative(-42f, 0f, -70f, -29.5f)
                reflectiveQuadTo(100f, 782f)
                quadToRelative(0f, -20f, 8f, -38.5f)
                reflectiveQuadToRelative(22f, -32.5f)
                lineToRelative(42f, -42f)
                lineToRelative(-14f, -14f)
                quadToRelative(-14f, -14f, -22f, -32f)
                reflectiveQuadToRelative(-8f, -38f)
                quadToRelative(0f, -42f, 29.5f, -71.5f)
                reflectiveQuadTo(229f, 484f)
                close()
                moveToRelative(0f, 242f)
                lineToRelative(-43f, 42f)
                quadToRelative(-3f, 3f, -4f, 6.5f)
                reflectiveQuadToRelative(-1f, 7.5f)
                quadToRelative(0f, 8f, 5.5f, 14f)
                reflectiveQuadToRelative(13.5f, 6f)
                quadToRelative(4f, 0f, 7.5f, -1.5f)
                reflectiveQuadToRelative(6.5f, -4.5f)
                lineToRelative(43f, -42f)
                lineToRelative(-28f, -28f)
                close()
                moveToRelative(-1f, -162f)
                quadToRelative(-8f, 0f, -13.5f, 6f)
                reflectiveQuadToRelative(-5.5f, 14f)
                quadToRelative(0f, 4f, 1f, 7.5f)
                reflectiveQuadToRelative(4f, 6.5f)
                lineToRelative(15f, 14f)
                lineToRelative(13f, -13f)
                quadToRelative(3f, -3f, 4.5f, -6.5f)
                reflectiveQuadToRelative(1.5f, -7.5f)
                quadToRelative(0f, -8f, -6f, -14.5f)
                reflectiveQuadToRelative(-14f, -6.5f)
                close()
                moveToRelative(33f, -404f)
                lineToRelative(-46f, 134f)
                horizontalLineToRelative(96f)
                lineToRelative(-46f, -134f)
                horizontalLineToRelative(-4f)
                close()
                moveToRelative(438f, -105f)
                quadToRelative(8f, 13f, 13.5f, 27f)
                reflectiveQuadToRelative(9.5f, 28f)
                lineToRelative(-43f, 13f)
                horizontalLineToRelative(201f)
                verticalLineToRelative(80f)
                horizontalLineToRelative(-67f)
                quadToRelative(-11f, 33f, -28.5f, 62.5f)
                reflectiveQuadTo(744f, 320f)
                quadToRelative(27f, 16f, 56f, 26.5f)
                reflectiveQuadToRelative(60f, 18.5f)
                lineToRelative(-19f, 77f)
                quadToRelative(-43f, -11f, -83.5f, -27f)
                reflectiveQuadTo(680f, 374f)
                quadToRelative(-37f, 24f, -77.5f, 40.5f)
                reflectiveQuadTo(519f, 442f)
                lineToRelative(-18f, -77f)
                quadToRelative(30f, -8f, 59f, -18.5f)
                reflectiveQuadToRelative(56f, -26.5f)
                quadToRelative(-23f, -25f, -40.5f, -54.5f)
                reflectiveQuadTo(548f, 203f)
                horizontalLineToRelative(-68f)
                verticalLineToRelative(-80f)
                horizontalLineToRelative(176f)
                quadToRelative(-3f, -13f, -8f, -25.5f)
                reflectiveQuadTo(638f, 73f)
                lineToRelative(61f, -18f)
                close()
                moveToRelative(104f, 444f)
                lineToRelative(57f, 56f)
                lineTo(549f, 866f)
                lineToRelative(-57f, -56f)
                lineToRelative(311f, -311f)
                close()
                moveToRelative(-223f, 23f)
                quadToRelative(25f, 0f, 42.5f, 17.5f)
                reflectiveQuadTo(640f, 582f)
                quadToRelative(0f, 25f, -17.5f, 42.5f)
                reflectiveQuadTo(580f, 642f)
                quadToRelative(-25f, 0f, -42.5f, -17.5f)
                reflectiveQuadTo(520f, 582f)
                quadToRelative(0f, -25f, 17.5f, -42.5f)
                reflectiveQuadTo(580f, 522f)
                close()
                moveToRelative(53f, -319f)
                quadToRelative(8f, 19f, 20f, 36f)
                reflectiveQuadToRelative(27f, 32f)
                quadToRelative(15f, -15f, 27f, -32f)
                reflectiveQuadToRelative(21f, -36f)
                horizontalLineToRelative(-95f)
                close()
                moveToRelative(147f, 519f)
                quadToRelative(25f, 0f, 42.5f, 17.5f)
                reflectiveQuadTo(840f, 782f)
                quadToRelative(0f, 25f, -17.5f, 42.5f)
                reflectiveQuadTo(780f, 842f)
                quadToRelative(-25f, 0f, -42.5f, -17.5f)
                reflectiveQuadTo(720f, 782f)
                quadToRelative(0f, -25f, 17.5f, -42.5f)
                reflectiveQuadTo(780f, 722f)
                close()
            }
        }.build()
        
        return _Glyphs!!
    }

private var _Glyphs: ImageVector? = null

