package com.composables.icons.materialsymbols.outlinedfilled

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.OutlinedFilled.Hand_bones: ImageVector
    get() {
        if (_Hand_bones != null) return _Hand_bones!!
        
        _Hand_bones = ImageVector.Builder(
            name = "hand_bones",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(183f, 580f)
                quadToRelative(-8f, 4f, -16.5f, 0.5f)
                reflectiveQuadTo(155f, 569f)
                lineToRelative(-30f, -80f)
                quadToRelative(-5f, -14f, -4.5f, -27.5f)
                reflectiveQuadTo(133f, 443f)
                quadToRelative(25f, -10f, 46.5f, 7f)
                reflectiveQuadToRelative(32.5f, 44f)
                lineToRelative(16f, 43f)
                quadToRelative(3f, 8f, 0.5f, 14.5f)
                reflectiveQuadTo(219f, 562f)
                lineToRelative(-36f, 18f)
                close()
                moveTo(433f, 880f)
                quadToRelative(-17f, 0f, -33.5f, -7f)
                reflectiveQuadTo(372f, 853f)
                lineTo(210f, 666f)
                quadToRelative(-11f, -13f, -10f, -29f)
                reflectiveQuadToRelative(14f, -27f)
                quadToRelative(13f, -11f, 29f, -9.5f)
                reflectiveQuadToRelative(27f, 13.5f)
                lineToRelative(90f, 103f)
                quadToRelative(0f, -8f, 2f, -15.5f)
                reflectiveQuadToRelative(6f, -15.5f)
                lineToRelative(-46f, -132f)
                quadToRelative(-5f, -16f, 2f, -31f)
                reflectiveQuadToRelative(23f, -20f)
                quadToRelative(16f, -5f, 31f, 2f)
                reflectiveQuadToRelative(20f, 23f)
                lineToRelative(39f, 112f)
                horizontalLineToRelative(23f)
                verticalLineToRelative(-120f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(500f, 480f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(540f, 520f)
                verticalLineToRelative(120f)
                horizontalLineToRelative(24f)
                lineToRelative(21f, -89f)
                quadToRelative(4f, -17f, 17.5f, -25.5f)
                reflectiveQuadTo(633f, 521f)
                quadToRelative(17f, 4f, 25.5f, 17.5f)
                reflectiveQuadTo(663f, 569f)
                lineToRelative(-16f, 71f)
                quadToRelative(5f, 1f, 10.5f, 2f)
                reflectiveQuadToRelative(10.5f, 3f)
                lineToRelative(15f, -39f)
                quadToRelative(6f, -16f, 21f, -23f)
                reflectiveQuadToRelative(31f, -1f)
                quadToRelative(15f, 6f, 21.5f, 21f)
                reflectiveQuadToRelative(0.5f, 31f)
                lineToRelative(-37f, 98f)
                verticalLineToRelative(68f)
                quadToRelative(0f, 33f, -23.5f, 56.5f)
                reflectiveQuadTo(640f, 880f)
                horizontalLineTo(433f)
                close()
                moveTo(311f, 261f)
                quadToRelative(-8f, 1f, -14.5f, -4.5f)
                reflectiveQuadTo(289f, 243f)
                lineToRelative(-9f, -79f)
                quadToRelative(-2f, -17f, 8.5f, -29.5f)
                reflectiveQuadTo(316f, 120f)
                quadToRelative(17f, -2f, 29.5f, 8.5f)
                reflectiveQuadTo(360f, 156f)
                lineToRelative(8f, 79f)
                quadToRelative(1f, 8f, -4.5f, 14.5f)
                reflectiveQuadTo(350f, 257f)
                lineToRelative(-39f, 4f)
                close()
                moveToRelative(22f, 204f)
                quadToRelative(-9f, 2f, -16.5f, -3f)
                reflectiveQuadToRelative(-8.5f, -14f)
                lineToRelative(-12f, -104f)
                quadToRelative(-2f, -17f, 8.5f, -29.5f)
                reflectiveQuadTo(332f, 300f)
                quadToRelative(17f, -2f, 29.5f, 8.5f)
                reflectiveQuadTo(376f, 336f)
                lineToRelative(11f, 97f)
                quadToRelative(1f, 8f, -3f, 14f)
                reflectiveQuadToRelative(-12f, 8f)
                lineToRelative(-39f, 10f)
                close()
                moveToRelative(147f, -25f)
                quadToRelative(-8f, 0f, -14f, -6f)
                reflectiveQuadToRelative(-6f, -14f)
                verticalLineToRelative(-100f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(500f, 280f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(540f, 320f)
                verticalLineToRelative(100f)
                quadToRelative(0f, 8f, -6f, 14f)
                reflectiveQuadToRelative(-14f, 6f)
                horizontalLineToRelative(-40f)
                close()
                moveToRelative(0f, -200f)
                quadToRelative(-8f, 0f, -14f, -6f)
                reflectiveQuadToRelative(-6f, -14f)
                verticalLineToRelative(-100f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(500f, 80f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(540f, 120f)
                verticalLineToRelative(100f)
                quadToRelative(0f, 8f, -6f, 14f)
                reflectiveQuadToRelative(-14f, 6f)
                horizontalLineToRelative(-40f)
                close()
                moveToRelative(175f, 246f)
                lineToRelative(-40f, -10f)
                quadToRelative(-8f, -2f, -12f, -8f)
                reflectiveQuadToRelative(-3f, -14f)
                lineToRelative(11f, -98f)
                quadToRelative(2f, -17f, 14.5f, -27.5f)
                reflectiveQuadTo(655f, 320f)
                quadToRelative(17f, 2f, 27.5f, 14.5f)
                reflectiveQuadTo(691f, 364f)
                lineToRelative(-11f, 105f)
                quadToRelative(-1f, 9f, -8.5f, 14f)
                reflectiveQuadToRelative(-16.5f, 3f)
                close()
                moveToRelative(23f, -201f)
                lineToRelative(-40f, -4f)
                quadToRelative(-8f, -1f, -13.5f, -7.5f)
                reflectiveQuadTo(620f, 259f)
                lineToRelative(8f, -79f)
                quadToRelative(2f, -17f, 14.5f, -27.5f)
                reflectiveQuadTo(672f, 144f)
                quadToRelative(17f, 2f, 27.5f, 14.5f)
                reflectiveQuadTo(708f, 188f)
                lineToRelative(-8f, 79f)
                quadToRelative(-1f, 8f, -7.5f, 13.5f)
                reflectiveQuadTo(678f, 285f)
                close()
                moveToRelative(80f, 265f)
                lineToRelative(-39f, -12f)
                quadToRelative(-8f, -2f, -11.5f, -9f)
                reflectiveQuadToRelative(-1.5f, -15f)
                lineToRelative(15f, -56f)
                quadToRelative(5f, -16f, 19f, -24.5f)
                reflectiveQuadToRelative(30f, -3.5f)
                quadToRelative(16f, 5f, 24f, 18.5f)
                reflectiveQuadToRelative(4f, 29.5f)
                lineToRelative(-15f, 58f)
                quadToRelative(-2f, 8f, -9.5f, 12f)
                reflectiveQuadToRelative(-15.5f, 2f)
                close()
                moveToRelative(42f, -151f)
                lineToRelative(-39f, -10f)
                quadToRelative(-8f, -2f, -12f, -9.5f)
                reflectiveQuadToRelative(-2f, -15.5f)
                lineToRelative(13f, -46f)
                quadToRelative(7f, -24f, 17f, -45f)
                reflectiveQuadToRelative(31f, -16f)
                quadToRelative(25f, 6f, 30f, 33f)
                reflectiveQuadToRelative(-3f, 56f)
                lineToRelative(-11f, 39f)
                quadToRelative(-2f, 8f, -9f, 12f)
                reflectiveQuadToRelative(-15f, 2f)
                close()
            }
        }.build()
        
        return _Hand_bones!!
    }

private var _Hand_bones: ImageVector? = null

