package com.composables.icons.materialsymbols.outlinedfilled

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.OutlinedFilled.Nest_clock_farsight_digital: ImageVector
    get() {
        if (_Nest_clock_farsight_digital != null) return _Nest_clock_farsight_digital!!
        
        _Nest_clock_farsight_digital = ImageVector.Builder(
            name = "nest_clock_farsight_digital",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(265f, 556f)
                horizontalLineToRelative(24f)
                verticalLineToRelative(-152f)
                horizontalLineToRelative(-17f)
                lineToRelative(-45f, 32f)
                lineToRelative(13f, 19f)
                lineToRelative(25f, -18f)
                verticalLineToRelative(119f)
                close()
                moveToRelative(57f, 1f)
                horizontalLineToRelative(100f)
                verticalLineToRelative(-23f)
                horizontalLineToRelative(-66f)
                verticalLineToRelative(-2f)
                lineToRelative(39f, -40f)
                quadToRelative(12f, -12f, 18f, -24f)
                reflectiveQuadToRelative(6f, -24f)
                quadToRelative(0f, -20f, -13.5f, -32f)
                reflectiveQuadTo(371f, 400f)
                quadToRelative(-18f, 0f, -31f, 9f)
                reflectiveQuadToRelative(-18f, 25f)
                lineToRelative(21f, 10f)
                quadToRelative(4f, -10f, 11f, -15f)
                reflectiveQuadToRelative(17f, -5f)
                quadToRelative(11f, 0f, 17.5f, 5.5f)
                reflectiveQuadTo(395f, 445f)
                quadToRelative(0f, 12f, -17f, 31f)
                lineToRelative(-56f, 58f)
                verticalLineToRelative(23f)
                close()
                moveToRelative(141f, -1f)
                quadToRelative(8f, 0f, 13f, -5f)
                reflectiveQuadToRelative(5f, -13f)
                quadToRelative(0f, -8f, -5f, -13f)
                reflectiveQuadToRelative(-13f, -5f)
                quadToRelative(-8f, 0f, -13f, 5f)
                reflectiveQuadToRelative(-5f, 13f)
                quadToRelative(0f, 8f, 5f, 13f)
                reflectiveQuadToRelative(13f, 5f)
                close()
                moveToRelative(0f, -81f)
                quadToRelative(8f, 0f, 13f, -5f)
                reflectiveQuadToRelative(5f, -13f)
                quadToRelative(0f, -8f, -5f, -13f)
                reflectiveQuadToRelative(-13f, -5f)
                quadToRelative(-8f, 0f, -13f, 5f)
                reflectiveQuadToRelative(-5f, 13f)
                quadToRelative(0f, 8f, 5f, 13f)
                reflectiveQuadToRelative(13f, 5f)
                close()
                moveToRelative(92f, 85f)
                quadToRelative(23f, 0f, 37f, -13f)
                reflectiveQuadToRelative(14f, -33f)
                quadToRelative(0f, -14f, -7f, -23.5f)
                reflectiveQuadTo(580f, 476f)
                verticalLineToRelative(-1f)
                quadToRelative(10f, -5f, 15.5f, -13.5f)
                reflectiveQuadTo(601f, 442f)
                quadToRelative(0f, -17f, -14f, -29.5f)
                reflectiveQuadTo(553f, 400f)
                quadToRelative(-17f, 0f, -29.5f, 8.5f)
                reflectiveQuadTo(505f, 432f)
                lineToRelative(22f, 9f)
                quadToRelative(4f, -9f, 10.5f, -13.5f)
                reflectiveQuadTo(553f, 423f)
                quadToRelative(11f, 0f, 17f, 5.5f)
                reflectiveQuadToRelative(6f, 13.5f)
                quadToRelative(0f, 10f, -7.5f, 16.5f)
                reflectiveQuadTo(550f, 465f)
                horizontalLineToRelative(-12f)
                verticalLineToRelative(23f)
                horizontalLineToRelative(13f)
                quadToRelative(14f, 0f, 21.5f, 5.5f)
                reflectiveQuadTo(580f, 510f)
                quadToRelative(0f, 11f, -8f, 18.5f)
                reflectiveQuadToRelative(-20f, 7.5f)
                quadToRelative(-11f, 0f, -17.5f, -6f)
                reflectiveQuadTo(524f, 511f)
                lineToRelative(-23f, 9f)
                quadToRelative(6f, 19f, 20f, 29.5f)
                reflectiveQuadToRelative(34f, 10.5f)
                close()
                moveToRelative(125f, 0f)
                quadToRelative(22f, 0f, 37.5f, -15f)
                reflectiveQuadToRelative(15.5f, -37f)
                quadToRelative(0f, -20f, -13f, -34.5f)
                reflectiveQuadTo(687f, 459f)
                quadToRelative(-2f, 0f, -16f, 4f)
                lineToRelative(-1f, -1f)
                lineToRelative(35f, -48f)
                lineToRelative(-20f, -14f)
                lineToRelative(-39f, 56f)
                quadToRelative(-12f, 17f, -16f, 28f)
                reflectiveQuadToRelative(-4f, 21f)
                quadToRelative(0f, 23f, 15.5f, 39f)
                reflectiveQuadToRelative(38.5f, 16f)
                close()
                moveToRelative(-1f, -23f)
                quadToRelative(-12f, 0f, -20.5f, -8.5f)
                reflectiveQuadTo(650f, 508f)
                quadToRelative(0f, -12f, 8.5f, -20.5f)
                reflectiveQuadTo(679f, 479f)
                quadToRelative(12f, 0f, 20.5f, 8.5f)
                reflectiveQuadTo(708f, 508f)
                quadToRelative(0f, 12f, -8.5f, 20.5f)
                reflectiveQuadTo(679f, 537f)
                close()
                moveTo(480f, 880f)
                quadToRelative(-83f, 0f, -156f, -31.5f)
                reflectiveQuadTo(197f, 763f)
                quadToRelative(-54f, -54f, -85.5f, -127f)
                reflectiveQuadTo(80f, 480f)
                quadToRelative(0f, -83f, 31.5f, -156f)
                reflectiveQuadTo(197f, 197f)
                quadToRelative(54f, -54f, 127f, -85.5f)
                reflectiveQuadTo(480f, 80f)
                quadToRelative(83f, 0f, 156f, 31.5f)
                reflectiveQuadTo(763f, 197f)
                quadToRelative(54f, 54f, 85.5f, 127f)
                reflectiveQuadTo(880f, 480f)
                quadToRelative(0f, 83f, -31.5f, 156f)
                reflectiveQuadTo(763f, 763f)
                quadToRelative(-54f, 54f, -127f, 85.5f)
                reflectiveQuadTo(480f, 880f)
                close()
            }
        }.build()
        
        return _Nest_clock_farsight_digital!!
    }

private var _Nest_clock_farsight_digital: ImageVector? = null

