package com.composables.icons.materialicons.twotone

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialicons.MaterialIcons
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialIcons.Twotone.Kebab_dining: ImageVector
    get() {
        if (_Kebab_dining != null) return _Kebab_dining!!
        
        _Kebab_dining = ImageVector.Builder(
            name = "kebab_dining",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f
        ).apply {
            path(
                fill = SolidColor(Color.Transparent)
            ) {
                moveTo(0f, 0f)
                horizontalLineTo(24f)
                verticalLineTo(24f)
                horizontalLineTo(0f)
                verticalLineTo(0f)
                close()
            }
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(15.5f, 5f)
                curveTo(15.22f, 5f, 15f, 4.78f, 15f, 4.5f)
                reflectiveCurveTo(15.22f, 4f, 15.5f, 4f)
                horizontalLineToRelative(3f)
                curveTo(18.78f, 4f, 19f, 4.22f, 19f, 4.5f)
                reflectiveCurveTo(18.78f, 5f, 18.5f, 5f)
                horizontalLineTo(15.5f)
                close()
                moveTo(18.5f, 16f)
                curveToRelative(0.28f, 0f, 0.5f, 0.22f, 0.5f, 0.5f)
                reflectiveCurveTo(18.78f, 17f, 18.5f, 17f)
                horizontalLineToRelative(-3f)
                curveToRelative(-0.28f, 0f, -0.5f, -0.22f, -0.5f, -0.5f)
                reflectiveCurveToRelative(0.22f, -0.5f, 0.5f, -0.5f)
                horizontalLineTo(18.5f)
                close()
                moveTo(19f, 10f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(-4f)
                verticalLineToRelative(-1f)
                horizontalLineTo(19f)
                close()
                moveTo(5.5f, 5f)
                curveTo(5.22f, 5f, 5f, 4.78f, 5f, 4.5f)
                reflectiveCurveTo(5.22f, 4f, 5.5f, 4f)
                horizontalLineToRelative(3f)
                curveTo(8.78f, 4f, 9f, 4.22f, 9f, 4.5f)
                reflectiveCurveTo(8.78f, 5f, 8.5f, 5f)
                horizontalLineTo(5.5f)
                close()
                moveTo(8.5f, 16f)
                curveTo(8.78f, 16f, 9f, 16.22f, 9f, 16.5f)
                reflectiveCurveTo(8.78f, 17f, 8.5f, 17f)
                horizontalLineToRelative(-3f)
                curveTo(5.22f, 17f, 5f, 16.78f, 5f, 16.5f)
                reflectiveCurveTo(5.22f, 16f, 5.5f, 16f)
                horizontalLineTo(8.5f)
                close()
                moveTo(9f, 10f)
                verticalLineToRelative(1f)
                horizontalLineTo(5f)
                verticalLineToRelative(-1f)
                horizontalLineTo(9f)
                close()
            }
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(17.75f, 7f)
                horizontalLineToRelative(0.75f)
                curveTo(19.88f, 7f, 21f, 5.88f, 21f, 4.5f)
                curveTo(21f, 3.12f, 19.88f, 2f, 18.5f, 2f)
                horizontalLineToRelative(-0.75f)
                verticalLineTo(1f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1f)
                horizontalLineTo(15.5f)
                curveTo(14.12f, 2f, 13f, 3.12f, 13f, 4.5f)
                curveTo(13f, 5.88f, 14.12f, 7f, 15.5f, 7f)
                horizontalLineToRelative(0.75f)
                verticalLineToRelative(1f)
                horizontalLineTo(13f)
                verticalLineToRelative(5f)
                horizontalLineToRelative(3.25f)
                verticalLineToRelative(1f)
                horizontalLineTo(15.5f)
                curveToRelative(-1.38f, 0f, -2.5f, 1.12f, -2.5f, 2.5f)
                curveToRelative(0f, 1.38f, 1.12f, 2.5f, 2.5f, 2.5f)
                horizontalLineToRelative(0.75f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(0.75f)
                curveToRelative(1.38f, 0f, 2.5f, -1.12f, 2.5f, -2.5f)
                curveToRelative(0f, -1.38f, -1.12f, -2.5f, -2.5f, -2.5f)
                horizontalLineToRelative(-0.75f)
                verticalLineToRelative(-1f)
                horizontalLineTo(21f)
                verticalLineTo(8f)
                horizontalLineToRelative(-3.25f)
                verticalLineTo(7f)
                close()
                moveTo(15.5f, 5f)
                curveTo(15.22f, 5f, 15f, 4.78f, 15f, 4.5f)
                reflectiveCurveTo(15.22f, 4f, 15.5f, 4f)
                horizontalLineToRelative(3f)
                curveTo(18.78f, 4f, 19f, 4.22f, 19f, 4.5f)
                reflectiveCurveTo(18.78f, 5f, 18.5f, 5f)
                horizontalLineTo(15.5f)
                close()
                moveTo(18.5f, 16f)
                curveToRelative(0.28f, 0f, 0.5f, 0.22f, 0.5f, 0.5f)
                reflectiveCurveTo(18.78f, 17f, 18.5f, 17f)
                horizontalLineToRelative(-3f)
                curveToRelative(-0.28f, 0f, -0.5f, -0.22f, -0.5f, -0.5f)
                reflectiveCurveToRelative(0.22f, -0.5f, 0.5f, -0.5f)
                horizontalLineTo(18.5f)
                close()
                moveTo(19f, 10f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(-4f)
                verticalLineToRelative(-1f)
                horizontalLineTo(19f)
                close()
                moveTo(7.75f, 7f)
                horizontalLineTo(8.5f)
                curveTo(9.88f, 7f, 11f, 5.88f, 11f, 4.5f)
                curveTo(11f, 3.12f, 9.88f, 2f, 8.5f, 2f)
                horizontalLineTo(7.75f)
                verticalLineTo(1f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1f)
                horizontalLineTo(5.5f)
                curveTo(4.12f, 2f, 3f, 3.12f, 3f, 4.5f)
                curveTo(3f, 5.88f, 4.12f, 7f, 5.5f, 7f)
                horizontalLineToRelative(0.75f)
                verticalLineToRelative(1f)
                horizontalLineTo(3f)
                verticalLineToRelative(5f)
                horizontalLineToRelative(3.25f)
                verticalLineToRelative(1f)
                horizontalLineTo(5.5f)
                curveTo(4.12f, 14f, 3f, 15.12f, 3f, 16.5f)
                curveTo(3f, 17.88f, 4.12f, 19f, 5.5f, 19f)
                horizontalLineToRelative(0.75f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-4f)
                horizontalLineTo(8.5f)
                curveToRelative(1.38f, 0f, 2.5f, -1.12f, 2.5f, -2.5f)
                curveToRelative(0f, -1.38f, -1.12f, -2.5f, -2.5f, -2.5f)
                horizontalLineTo(7.75f)
                verticalLineToRelative(-1f)
                horizontalLineTo(11f)
                verticalLineTo(8f)
                horizontalLineTo(7.75f)
                verticalLineTo(7f)
                close()
                moveTo(5.5f, 5f)
                curveTo(5.22f, 5f, 5f, 4.78f, 5f, 4.5f)
                reflectiveCurveTo(5.22f, 4f, 5.5f, 4f)
                horizontalLineToRelative(3f)
                curveTo(8.78f, 4f, 9f, 4.22f, 9f, 4.5f)
                reflectiveCurveTo(8.78f, 5f, 8.5f, 5f)
                horizontalLineTo(5.5f)
                close()
                moveTo(8.5f, 16f)
                curveTo(8.78f, 16f, 9f, 16.22f, 9f, 16.5f)
                reflectiveCurveTo(8.78f, 17f, 8.5f, 17f)
                horizontalLineToRelative(-3f)
                curveTo(5.22f, 17f, 5f, 16.78f, 5f, 16.5f)
                reflectiveCurveTo(5.22f, 16f, 5.5f, 16f)
                horizontalLineTo(8.5f)
                close()
                moveTo(9f, 10f)
                verticalLineToRelative(1f)
                horizontalLineTo(5f)
                verticalLineToRelative(-1f)
                horizontalLineTo(9f)
                close()
            }
        }.build()
        
        return _Kebab_dining!!
    }

private var _Kebab_dining: ImageVector? = null

