package com.composables.icons.materialsymbols.outlined

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Outlined.Hvac_max_defrost: ImageVector
    get() {
        if (_Hvac_max_defrost != null) return _Hvac_max_defrost!!
        
        _Hvac_max_defrost = ImageVector.Builder(
            name = "hvac_max_defrost",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(120f, 880f)
                verticalLineToRelative(-240f)
                horizontalLineToRelative(52f)
                lineToRelative(68f, 182f)
                horizontalLineToRelative(2f)
                lineToRelative(70f, -182f)
                horizontalLineToRelative(50f)
                verticalLineToRelative(240f)
                horizontalLineToRelative(-37f)
                verticalLineToRelative(-134f)
                lineToRelative(2f, -44f)
                horizontalLineToRelative(-2f)
                lineTo(257f, 880f)
                horizontalLineToRelative(-31f)
                lineToRelative(-68f, -178f)
                horizontalLineToRelative(-2f)
                lineToRelative(2f, 44f)
                verticalLineToRelative(134f)
                horizontalLineToRelative(-38f)
                close()
                moveToRelative(275f, 0f)
                lineToRelative(90f, -240f)
                horizontalLineToRelative(43f)
                lineToRelative(90f, 240f)
                horizontalLineToRelative(-42f)
                lineToRelative(-22f, -61f)
                horizontalLineToRelative(-97f)
                lineToRelative(-21f, 61f)
                horizontalLineToRelative(-41f)
                close()
                moveToRelative(235f, 0f)
                lineToRelative(79f, -125f)
                lineToRelative(-74f, -115f)
                horizontalLineToRelative(46f)
                lineToRelative(53f, 86f)
                horizontalLineToRelative(2f)
                lineToRelative(52f, -86f)
                horizontalLineToRelative(46f)
                lineToRelative(-74f, 115f)
                lineToRelative(80f, 125f)
                horizontalLineToRelative(-46f)
                lineToRelative(-58f, -93f)
                horizontalLineToRelative(-2f)
                lineToRelative(-59f, 93f)
                horizontalLineToRelative(-45f)
                close()
                moveToRelative(-160f, -96f)
                horizontalLineToRelative(71f)
                lineToRelative(-34f, -100f)
                horizontalLineToRelative(-2f)
                lineToRelative(-35f, 100f)
                close()
                moveToRelative(10f, -704f)
                quadToRelative(100f, 0f, 208.5f, 16f)
                reflectiveQuadTo(926f, 147f)
                lineToRelative(-72f, 381f)
                lineToRelative(-78f, -15f)
                lineToRelative(58f, -307f)
                quadToRelative(-104f, -24f, -190f, -35f)
                reflectiveQuadToRelative(-164f, -11f)
                quadToRelative(-78f, 0f, -164f, 11f)
                reflectiveQuadToRelative(-190f, 35f)
                lineToRelative(58f, 307f)
                lineToRelative(-78f, 15f)
                lineToRelative(-72f, -381f)
                quadToRelative(129f, -35f, 237.5f, -51f)
                reflectiveQuadTo(480f, 80f)
                close()
                moveToRelative(201f, 502f)
                lineToRelative(-66f, -44f)
                lineToRelative(13f, -21f)
                quadToRelative(6f, -9f, 9f, -18.5f)
                reflectiveQuadToRelative(3f, -20.5f)
                quadToRelative(0f, -14f, -5f, -27f)
                reflectiveQuadToRelative(-15f, -23f)
                quadToRelative(-21f, -21f, -32.5f, -48.5f)
                reflectiveQuadTo(576f, 322f)
                quadToRelative(0f, -23f, 6.5f, -44f)
                reflectiveQuadToRelative(18.5f, -40f)
                lineToRelative(13f, -20f)
                lineToRelative(67f, 44f)
                lineToRelative(-14f, 21f)
                quadToRelative(-6f, 9f, -8.5f, 18.5f)
                reflectiveQuadTo(656f, 322f)
                quadToRelative(0f, 14f, 5f, 27f)
                reflectiveQuadToRelative(15f, 23f)
                quadToRelative(21f, 21f, 32.5f, 48.5f)
                reflectiveQuadTo(720f, 478f)
                quadToRelative(0f, 23f, -6.5f, 44f)
                reflectiveQuadTo(695f, 562f)
                lineToRelative(-14f, 20f)
                close()
                moveToRelative(-168f, 0f)
                lineToRelative(-66f, -44f)
                lineToRelative(13f, -21f)
                quadToRelative(6f, -9f, 9f, -18.5f)
                reflectiveQuadToRelative(3f, -20.5f)
                quadToRelative(0f, -14f, -5f, -27f)
                reflectiveQuadToRelative(-15f, -23f)
                quadToRelative(-21f, -21f, -32.5f, -48.5f)
                reflectiveQuadTo(408f, 322f)
                quadToRelative(0f, -23f, 6.5f, -44f)
                reflectiveQuadToRelative(18.5f, -40f)
                lineToRelative(13f, -20f)
                lineToRelative(67f, 44f)
                lineToRelative(-14f, 21f)
                quadToRelative(-6f, 9f, -8.5f, 18.5f)
                reflectiveQuadTo(488f, 322f)
                quadToRelative(0f, 14f, 5f, 27f)
                reflectiveQuadToRelative(15f, 23f)
                quadToRelative(21f, 21f, 32.5f, 48.5f)
                reflectiveQuadTo(552f, 478f)
                quadToRelative(0f, 23f, -6.5f, 44f)
                reflectiveQuadTo(527f, 562f)
                lineToRelative(-14f, 20f)
                close()
                moveToRelative(-167f, 0f)
                lineToRelative(-67f, -44f)
                lineToRelative(14f, -21f)
                quadToRelative(6f, -9f, 9f, -18.5f)
                reflectiveQuadToRelative(3f, -20.5f)
                quadToRelative(0f, -14f, -5.5f, -27f)
                reflectiveQuadTo(284f, 428f)
                quadToRelative(-21f, -21f, -32.5f, -48.5f)
                reflectiveQuadTo(240f, 322f)
                quadToRelative(0f, -23f, 6f, -44f)
                reflectiveQuadToRelative(19f, -40f)
                lineToRelative(14f, -20f)
                lineToRelative(67f, 44f)
                lineToRelative(-14f, 21f)
                quadToRelative(-6f, 8f, -9f, 18f)
                reflectiveQuadToRelative(-3f, 21f)
                quadToRelative(0f, 14f, 5f, 27f)
                reflectiveQuadToRelative(15f, 23f)
                quadToRelative(21f, 21f, 32.5f, 48.5f)
                reflectiveQuadTo(384f, 478f)
                quadToRelative(0f, 23f, -6.5f, 44f)
                reflectiveQuadTo(359f, 562f)
                lineToRelative(-13f, 20f)
                close()
            }
        }.build()
        
        return _Hvac_max_defrost!!
    }

private var _Hvac_max_defrost: ImageVector? = null

