package com.composables.icons.materialsymbols.outlined

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Outlined.Okonomiyaki: ImageVector
    get() {
        if (_Okonomiyaki != null) return _Okonomiyaki!!
        
        _Okonomiyaki = ImageVector.Builder(
            name = "okonomiyaki",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(480f, 881f)
                quadToRelative(-14f, 0f, -27.5f, -4.5f)
                reflectiveQuadTo(428f, 864f)
                lineToRelative(-36f, -26f)
                quadToRelative(-11f, -8f, -24f, -12.5f)
                reflectiveQuadToRelative(-27f, -4.5f)
                horizontalLineToRelative(-45f)
                quadToRelative(-29f, 0f, -51.5f, -17f)
                reflectiveQuadTo(213f, 760f)
                lineToRelative(-14f, -42f)
                quadToRelative(-5f, -14f, -13f, -25f)
                reflectiveQuadToRelative(-19f, -19f)
                lineToRelative(-36f, -26f)
                quadToRelative(-23f, -17f, -31f, -44f)
                reflectiveQuadToRelative(0f, -54f)
                lineToRelative(13f, -42f)
                quadToRelative(4f, -14f, 4f, -27f)
                reflectiveQuadToRelative(-4f, -27f)
                lineToRelative(-13f, -43f)
                quadToRelative(-8f, -27f, 0f, -54f)
                reflectiveQuadToRelative(31f, -44f)
                lineToRelative(36f, -26f)
                quadToRelative(11f, -8f, 19f, -19f)
                reflectiveQuadToRelative(13f, -25f)
                lineToRelative(14f, -42f)
                quadToRelative(9f, -27f, 31.5f, -44f)
                reflectiveQuadToRelative(51.5f, -17f)
                horizontalLineToRelative(45f)
                quadToRelative(14f, 0f, 27f, -4f)
                reflectiveQuadToRelative(24f, -12f)
                lineToRelative(36f, -27f)
                quadToRelative(11f, -8f, 24.5f, -12.5f)
                reflectiveQuadTo(480f, 80f)
                quadToRelative(14f, 0f, 27.5f, 4.5f)
                reflectiveQuadTo(532f, 97f)
                lineToRelative(36f, 27f)
                quadToRelative(11f, 8f, 24f, 12f)
                reflectiveQuadToRelative(27f, 4f)
                horizontalLineToRelative(45f)
                quadToRelative(29f, 0f, 51.5f, 17f)
                reflectiveQuadToRelative(31.5f, 44f)
                lineToRelative(14f, 42f)
                quadToRelative(5f, 13f, 12.5f, 24.5f)
                reflectiveQuadTo(792f, 287f)
                lineToRelative(36f, 26f)
                quadToRelative(23f, 17f, 32f, 44f)
                reflectiveQuadToRelative(0f, 54f)
                lineToRelative(-14f, 43f)
                quadToRelative(-5f, 14f, -5f, 27f)
                reflectiveQuadToRelative(5f, 27f)
                lineToRelative(14f, 42f)
                quadToRelative(9f, 27f, 0f, 54f)
                reflectiveQuadToRelative(-32f, 44f)
                lineToRelative(-36f, 26f)
                quadToRelative(-11f, 8f, -18.5f, 19.5f)
                reflectiveQuadTo(761f, 718f)
                lineToRelative(-14f, 42f)
                quadToRelative(-9f, 27f, -31.5f, 44f)
                reflectiveQuadTo(664f, 821f)
                horizontalLineToRelative(-45f)
                quadToRelative(-14f, 0f, -27f, 4.5f)
                reflectiveQuadTo(568f, 838f)
                lineToRelative(-36f, 26f)
                quadToRelative(-11f, 8f, -24.5f, 12.5f)
                reflectiveQuadTo(480f, 881f)
                close()
                moveToRelative(-6f, -719f)
                quadToRelative(-9f, 7f, -18f, 13f)
                reflectiveQuadToRelative(-18f, 13f)
                quadToRelative(-21f, 16f, -46.5f, 24f)
                reflectiveQuadToRelative(-51.5f, 8f)
                horizontalLineToRelative(-45f)
                quadToRelative(-2f, 0f, -4f, 1.5f)
                reflectiveQuadToRelative(-3f, 3.5f)
                quadToRelative(-4f, 11f, -7f, 21.5f)
                reflectiveQuadToRelative(-7f, 21.5f)
                quadToRelative(-8f, 25f, -23f, 46.5f)
                reflectiveQuadTo(214f, 351f)
                quadToRelative(-9f, 7f, -18f, 13.5f)
                reflectiveQuadTo(178f, 378f)
                quadToRelative(-2f, 2f, -3f, 4f)
                reflectiveQuadToRelative(0f, 4f)
                quadToRelative(3f, 11f, 6.5f, 21f)
                reflectiveQuadToRelative(6.5f, 21f)
                quadToRelative(8f, 26f, 8f, 52f)
                reflectiveQuadToRelative(-8f, 52f)
                quadToRelative(-3f, 11f, -6.5f, 21f)
                reflectiveQuadToRelative(-6.5f, 21f)
                quadToRelative(-1f, 2f, 0f, 4.5f)
                reflectiveQuadToRelative(3f, 4.5f)
                quadToRelative(9f, 7f, 18f, 13f)
                reflectiveQuadToRelative(18f, 13f)
                quadToRelative(21f, 16f, 36.5f, 37.5f)
                reflectiveQuadTo(274f, 693f)
                quadToRelative(4f, 11f, 7f, 21f)
                reflectiveQuadToRelative(7f, 21f)
                quadToRelative(1f, 2f, 3.5f, 3.5f)
                reflectiveQuadToRelative(4.5f, 1.5f)
                horizontalLineToRelative(44f)
                quadToRelative(27f, 0f, 52f, 8f)
                reflectiveQuadToRelative(47f, 24f)
                quadToRelative(9f, 7f, 18f, 13.5f)
                reflectiveQuadToRelative(18f, 13.5f)
                quadToRelative(1f, 1f, 5f, 0.5f)
                lineToRelative(4f, -0.5f)
                quadToRelative(9f, -7f, 18f, -13.5f)
                reflectiveQuadToRelative(18f, -13.5f)
                quadToRelative(22f, -15f, 47f, -23.5f)
                reflectiveQuadToRelative(51f, -8.5f)
                horizontalLineToRelative(45f)
                quadToRelative(2f, 0f, 4f, -1.5f)
                reflectiveQuadToRelative(3f, -3.5f)
                quadToRelative(4f, -11f, 7f, -21f)
                reflectiveQuadToRelative(7f, -21f)
                quadToRelative(8f, -26f, 23.5f, -47f)
                reflectiveQuadToRelative(37.5f, -37f)
                quadToRelative(9f, -7f, 18f, -13f)
                reflectiveQuadToRelative(18f, -13f)
                quadToRelative(2f, -2f, 3f, -4.5f)
                reflectiveQuadToRelative(0f, -4.5f)
                quadToRelative(-4f, -11f, -7f, -21f)
                reflectiveQuadToRelative(-7f, -21f)
                quadToRelative(-8f, -26f, -8f, -52f)
                reflectiveQuadToRelative(8f, -52f)
                quadToRelative(4f, -11f, 7f, -21f)
                reflectiveQuadToRelative(6f, -21f)
                quadToRelative(1f, -2f, 0f, -4f)
                reflectiveQuadToRelative(-3f, -4f)
                quadToRelative(-9f, -6f, -18f, -13f)
                lineToRelative(-18f, -14f)
                quadToRelative(-21f, -16f, -36.5f, -37f)
                reflectiveQuadTo(684f, 268f)
                quadToRelative(-4f, -11f, -7f, -21.5f)
                reflectiveQuadToRelative(-7f, -21.5f)
                quadToRelative(-1f, -2f, -3.5f, -3.5f)
                reflectiveQuadTo(662f, 220f)
                horizontalLineToRelative(-44f)
                quadToRelative(-27f, 0f, -52f, -8f)
                reflectiveQuadToRelative(-47f, -24f)
                quadToRelative(-9f, -7f, -18f, -13.5f)
                reflectiveQuadTo(483f, 162f)
                quadToRelative(-2f, -2f, -4.5f, -2f)
                reflectiveQuadToRelative(-4.5f, 2f)
                close()
                moveToRelative(-87f, 109f)
                lineToRelative(-99f, 99f)
                quadToRelative(-30f, 29f, -29.5f, 71f)
                reflectiveQuadToRelative(29.5f, 71f)
                quadToRelative(29f, 29f, 70.5f, 29f)
                reflectiveQuadToRelative(70.5f, -29f)
                lineToRelative(113f, -114f)
                quadToRelative(6f, -6f, 14f, -6f)
                reflectiveQuadToRelative(14f, 6f)
                quadToRelative(6f, 6f, 6f, 14.5f)
                reflectiveQuadToRelative(-6f, 14.5f)
                lineToRelative(-84f, 85f)
                quadToRelative(-29f, 29f, -30f, 70.5f)
                reflectiveQuadToRelative(28f, 70.5f)
                quadToRelative(29f, 30f, 71f, 30f)
                reflectiveQuadToRelative(72f, -30f)
                lineToRelative(43f, -42f)
                lineToRelative(-57f, -57f)
                lineToRelative(-43f, 42f)
                quadToRelative(-6f, 6f, -14f, 6f)
                reflectiveQuadToRelative(-14f, -6f)
                quadToRelative(-6f, -6f, -6f, -14f)
                reflectiveQuadToRelative(6f, -14f)
                lineToRelative(85f, -85f)
                quadToRelative(29f, -29f, 29f, -70.5f)
                reflectiveQuadTo(627f, 342f)
                quadToRelative(-29f, -29f, -71f, -29f)
                reflectiveQuadToRelative(-71f, 29f)
                lineTo(372f, 455f)
                quadToRelative(-6f, 6f, -14f, 6f)
                reflectiveQuadToRelative(-14f, -6f)
                quadToRelative(-6f, -6f, -6f, -14f)
                reflectiveQuadToRelative(6f, -14f)
                lineToRelative(99f, -99f)
                lineToRelative(-56f, -57f)
                close()
                moveToRelative(93f, 209f)
                close()
            }
        }.build()
        
        return _Okonomiyaki!!
    }

private var _Okonomiyaki: ImageVector? = null

