package com.composables.icons.fontawesome.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.fontawesome.FontAwesome
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val FontAwesome.Brands.Shirtsinbulk: ImageVector
    get() {
        if (_Shirtsinbulk != null) return _Shirtsinbulk!!
        
        _Shirtsinbulk = ImageVector.Builder(
            name = "shirtsinbulk",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 448f,
            viewportHeight = 512f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(100f, 410.3f)
                lineToRelative(30.6f, 13.4f)
                lineToRelative(4.4f, -9.9f)
                lineToRelative(-30.6f, -13.4f)
                close()
                moveToRelative(39.4f, 17.5f)
                lineToRelative(30.6f, 13.4f)
                lineToRelative(4.4f, -9.9f)
                lineToRelative(-30.6f, -13.4f)
                close()
                moveToRelative(172.1f, -14f)
                lineToRelative(4.4f, 9.9f)
                lineToRelative(30.6f, -13.4f)
                lineToRelative(-4.4f, -9.9f)
                close()
                moveTo(179.1f, 445f)
                lineToRelative(30.3f, 13.7f)
                lineToRelative(4.4f, -9.9f)
                lineToRelative(-30.3f, -13.4f)
                close()
                moveTo(60.4f, 392.8f)
                lineTo(91f, 406.2f)
                lineToRelative(4.4f, -9.6f)
                lineToRelative(-30.6f, -13.7f)
                close()
                moveToRelative(211.4f, 38.5f)
                lineToRelative(4.4f, 9.9f)
                lineToRelative(30.6f, -13.4f)
                lineToRelative(-4.4f, -9.9f)
                close()
                moveToRelative(-39.3f, 17.5f)
                lineToRelative(4.4f, 9.9f)
                lineToRelative(30.6f, -13.7f)
                lineToRelative(-4.4f, -9.6f)
                close()
                moveToRelative(118.4f, -52.2f)
                lineToRelative(4.4f, 9.6f)
                lineToRelative(30.6f, -13.4f)
                lineToRelative(-4.4f, -9.9f)
                close()
                moveTo(170f, 46.6f)
                horizontalLineToRelative(-33.5f)
                verticalLineToRelative(10.5f)
                horizontalLineTo(170f)
                close()
                moveToRelative(-47.2f, 0f)
                horizontalLineTo(89.2f)
                verticalLineToRelative(10.5f)
                horizontalLineToRelative(33.5f)
                close()
                moveToRelative(-47.3f, 0f)
                horizontalLineTo(42.3f)
                verticalLineToRelative(10.5f)
                horizontalLineToRelative(33.3f)
                close()
                moveToRelative(141.5f, 0f)
                horizontalLineToRelative(-33.2f)
                verticalLineToRelative(10.5f)
                horizontalLineTo(217f)
                close()
                moveToRelative(94.5f, 0f)
                horizontalLineTo(278f)
                verticalLineToRelative(10.5f)
                horizontalLineToRelative(33.5f)
                close()
                moveToRelative(47.3f, 0f)
                horizontalLineToRelative(-33.5f)
                verticalLineToRelative(10.5f)
                horizontalLineToRelative(33.5f)
                close()
                moveToRelative(-94.6f, 0f)
                horizontalLineTo(231f)
                verticalLineToRelative(10.5f)
                horizontalLineToRelative(33.2f)
                close()
                moveToRelative(141.5f, 0f)
                horizontalLineToRelative(-33.3f)
                verticalLineToRelative(10.5f)
                horizontalLineToRelative(33.3f)
                close()
                moveTo(52.8f, 351.1f)
                horizontalLineTo(42f)
                verticalLineToRelative(33.5f)
                horizontalLineToRelative(10.8f)
                close()
                moveToRelative(70f, -215.9f)
                horizontalLineTo(89.2f)
                verticalLineToRelative(10.5f)
                horizontalLineToRelative(33.5f)
                close()
                moveToRelative(-70f, 10.6f)
                horizontalLineToRelative(22.8f)
                verticalLineToRelative(-10.5f)
                horizontalLineTo(42f)
                verticalLineToRelative(33.5f)
                horizontalLineToRelative(10.8f)
                close()
                moveToRelative(168.9f, 228.6f)
                curveToRelative(50.5f, 0f, 91.3f, -40.8f, 91.3f, -91.3f)
                curveToRelative(0f, -50.2f, -40.8f, -91.3f, -91.3f, -91.3f)
                curveToRelative(-50.2f, 0f, -91.3f, 41.1f, -91.3f, 91.3f)
                curveToRelative(0f, 50.5f, 41.1f, 91.3f, 91.3f, 91.3f)
                close()
                moveToRelative(-48.2f, -111.1f)
                curveToRelative(0f, -25.4f, 29.5f, -31.8f, 49.6f, -31.8f)
                curveToRelative(16.9f, 0f, 29.2f, 5.8f, 44.3f, 12f)
                lineToRelative(-8.8f, 16.9f)
                horizontalLineToRelative(-0.9f)
                curveToRelative(-6.4f, -9.9f, -24.8f, -13.1f, -35.6f, -13.1f)
                curveToRelative(-9f, 0f, -29.8f, 1.8f, -29.8f, 14.9f)
                curveToRelative(0f, 21.6f, 78.5f, -10.2f, 78.5f, 37.9f)
                curveToRelative(0f, 25.4f, -31.5f, 31.2f, -51f, 31.2f)
                curveToRelative(-18.1f, 0f, -32.4f, -2.9f, -47.2f, -12.2f)
                lineToRelative(9f, -18.4f)
                horizontalLineToRelative(0.9f)
                curveToRelative(6.1f, 12.2f, 23.6f, 14.9f, 35.9f, 14.9f)
                curveToRelative(8.7f, 0f, 32.7f, -1.2f, 32.7f, -14.3f)
                curveToRelative(0f, -26.1f, -77.6f, 6.3f, -77.6f, -38f)
                close()
                moveTo(52.8f, 178.4f)
                horizontalLineTo(42f)
                verticalLineTo(212f)
                horizontalLineToRelative(10.8f)
                close()
                moveToRelative(342.4f, 206.2f)
                horizontalLineTo(406f)
                verticalLineToRelative(-33.5f)
                horizontalLineToRelative(-10.8f)
                close()
                moveTo(52.8f, 307.9f)
                horizontalLineTo(42f)
                verticalLineToRelative(33.5f)
                horizontalLineToRelative(10.8f)
                close()
                moveTo(0f, 3.7f)
                verticalLineToRelative(406f)
                lineToRelative(221.7f, 98.6f)
                lineTo(448f, 409.7f)
                verticalLineTo(3.7f)
                close()
                moveToRelative(418.8f, 387.1f)
                lineTo(222f, 476.5f)
                lineTo(29.2f, 390.8f)
                verticalLineTo(120.7f)
                horizontalLineToRelative(389.7f)
                verticalLineToRelative(270.1f)
                close()
                moveToRelative(0f, -299.3f)
                horizontalLineTo(29.2f)
                verticalLineTo(32.9f)
                horizontalLineToRelative(389.7f)
                verticalLineToRelative(58.6f)
                close()
                moveToRelative(-366f, 130.1f)
                horizontalLineTo(42f)
                verticalLineToRelative(33.5f)
                horizontalLineToRelative(10.8f)
                close()
                moveToRelative(0f, 43.2f)
                horizontalLineTo(42f)
                verticalLineToRelative(33.5f)
                horizontalLineToRelative(10.8f)
                close()
                moveTo(170f, 135.2f)
                horizontalLineToRelative(-33.5f)
                verticalLineToRelative(10.5f)
                horizontalLineTo(170f)
                close()
                moveToRelative(225.2f, 163.1f)
                horizontalLineTo(406f)
                verticalLineToRelative(-33.5f)
                horizontalLineToRelative(-10.8f)
                close()
                moveToRelative(0f, -43.2f)
                horizontalLineTo(406f)
                verticalLineToRelative(-33.5f)
                horizontalLineToRelative(-10.8f)
                close()
                moveTo(217f, 135.2f)
                horizontalLineToRelative(-33.2f)
                verticalLineToRelative(10.5f)
                horizontalLineTo(217f)
                close()
                moveTo(395.2f, 212f)
                horizontalLineTo(406f)
                verticalLineToRelative(-33.5f)
                horizontalLineToRelative(-10.8f)
                close()
                moveToRelative(0f, 129.5f)
                horizontalLineTo(406f)
                verticalLineTo(308f)
                horizontalLineToRelative(-10.8f)
                close()
                moveToRelative(-131f, -206.3f)
                horizontalLineTo(231f)
                verticalLineToRelative(10.5f)
                horizontalLineToRelative(33.2f)
                close()
                moveToRelative(47.3f, 0f)
                horizontalLineTo(278f)
                verticalLineToRelative(10.5f)
                horizontalLineToRelative(33.5f)
                close()
                moveToRelative(83.7f, 33.6f)
                horizontalLineTo(406f)
                verticalLineToRelative(-33.5f)
                horizontalLineToRelative(-33.5f)
                verticalLineToRelative(10.5f)
                horizontalLineToRelative(22.8f)
                close()
                moveToRelative(-36.4f, -33.6f)
                horizontalLineToRelative(-33.5f)
                verticalLineToRelative(10.5f)
                horizontalLineToRelative(33.5f)
                close()
            }
        }.build()
        
        return _Shirtsinbulk!!
    }

private var _Shirtsinbulk: ImageVector? = null

