package com.composables.icons.fontawesome.brands

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.fontawesome.FontAwesome
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val FontAwesome.Brands.Uniregistry: ImageVector
    get() {
        if (_Uniregistry != null) return _Uniregistry!!
        
        _Uniregistry = ImageVector.Builder(
            name = "uniregistry",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 384f,
            viewportHeight = 512f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(192f, 480f)
                curveToRelative(39.5f, 0f, 76.2f, -11.8f, 106.8f, -32.2f)
                horizontalLineTo(85.3f)
                curveTo(115.8f, 468.2f, 152.5f, 480f, 192f, 480f)
                close()
                moveToRelative(-89.1f, -193.1f)
                verticalLineToRelative(-12.4f)
                horizontalLineTo(0f)
                verticalLineToRelative(12.4f)
                curveToRelative(0f, 2.5f, 0f, 5f, 0.1f, 7.4f)
                horizontalLineToRelative(103.1f)
                curveToRelative(-0.2f, -2.4f, -0.3f, -4.9f, -0.3f, -7.4f)
                close()
                moveToRelative(20.5f, 57f)
                horizontalLineTo(8.5f)
                curveToRelative(2.6f, 8.5f, 5.8f, 16.8f, 9.6f, 24.8f)
                horizontalLineToRelative(138.3f)
                curveToRelative(-12.9f, -5.7f, -24.1f, -14.2f, -33f, -24.8f)
                close()
                moveToRelative(-17.7f, -34.7f)
                horizontalLineTo(1.3f)
                curveToRelative(0.9f, 7.6f, 2.2f, 15f, 3.9f, 22.3f)
                horizontalLineToRelative(109.7f)
                curveToRelative(-4f, -6.9f, -7.2f, -14.4f, -9.2f, -22.3f)
                close()
                moveToRelative(-2.8f, -69.3f)
                horizontalLineTo(0f)
                verticalLineToRelative(17.3f)
                horizontalLineToRelative(102.9f)
                close()
                moveToRelative(0f, -173.2f)
                horizontalLineTo(0f)
                verticalLineToRelative(4.9f)
                horizontalLineToRelative(102.9f)
                close()
                moveToRelative(0f, -34.7f)
                horizontalLineTo(0f)
                verticalLineToRelative(2.5f)
                horizontalLineToRelative(102.9f)
                close()
                moveToRelative(0f, 69.3f)
                horizontalLineTo(0f)
                verticalLineToRelative(7.4f)
                horizontalLineToRelative(102.9f)
                close()
                moveToRelative(0f, 104f)
                horizontalLineTo(0f)
                verticalLineToRelative(14.8f)
                horizontalLineToRelative(102.9f)
                close()
                moveToRelative(0f, -69.3f)
                horizontalLineTo(0f)
                verticalLineToRelative(9.9f)
                horizontalLineToRelative(102.9f)
                close()
                moveToRelative(0f, 34.6f)
                horizontalLineTo(0f)
                verticalLineTo(183f)
                horizontalLineToRelative(102.9f)
                close()
                moveToRelative(166.2f, 160.9f)
                horizontalLineToRelative(109.7f)
                curveToRelative(1.8f, -7.3f, 3.1f, -14.7f, 3.9f, -22.3f)
                horizontalLineTo(278.3f)
                curveToRelative(-2.1f, 7.9f, -5.2f, 15.4f, -9.2f, 22.3f)
                close()
                moveToRelative(12f, -185.7f)
                horizontalLineTo(384f)
                verticalLineTo(136f)
                horizontalLineTo(281.1f)
                close()
                moveToRelative(0f, 37.2f)
                horizontalLineTo(384f)
                verticalLineToRelative(-12.4f)
                horizontalLineTo(281.1f)
                close()
                moveToRelative(0f, -74.3f)
                horizontalLineTo(384f)
                verticalLineToRelative(-7.4f)
                horizontalLineTo(281.1f)
                close()
                moveToRelative(0f, -76.7f)
                verticalLineToRelative(2.5f)
                horizontalLineTo(384f)
                verticalLineTo(32f)
                close()
                moveToRelative(-203f, 410.9f)
                horizontalLineToRelative(227.7f)
                curveToRelative(11.8f, -8.7f, 22.7f, -18.6f, 32.2f, -29.7f)
                horizontalLineTo(44.9f)
                curveToRelative(9.6f, 11f, 21.4f, 21f, 33.2f, 29.7f)
                close()
                moveToRelative(203f, -371.3f)
                horizontalLineTo(384f)
                verticalLineToRelative(-4.9f)
                horizontalLineTo(281.1f)
                close()
                moveToRelative(0f, 148.5f)
                horizontalLineTo(384f)
                verticalLineToRelative(-14.8f)
                horizontalLineTo(281.1f)
                close()
                moveTo(38.8f, 405.7f)
                horizontalLineToRelative(305.3f)
                curveToRelative(6.7f, -8.5f, 12.6f, -17.6f, 17.8f, -27.2f)
                horizontalLineTo(23f)
                curveToRelative(5.2f, 9.6f, 9.2f, 18.7f, 15.8f, 27.2f)
                close()
                moveToRelative(188.8f, -37.1f)
                horizontalLineTo(367f)
                curveToRelative(3.7f, -8f, 5.8f, -16.2f, 8.5f, -24.8f)
                horizontalLineToRelative(-115f)
                curveToRelative(-8.8f, 10.7f, -20.1f, 19.2f, -32.9f, 24.8f)
                close()
                moveToRelative(53.5f, -81.7f)
                curveToRelative(0f, 2.5f, -0.1f, 5f, -0.4f, 7.4f)
                horizontalLineToRelative(103.1f)
                curveToRelative(0.1f, -2.5f, 0.2f, -4.9f, 0.2f, -7.4f)
                verticalLineToRelative(-12.4f)
                horizontalLineTo(281.1f)
                close()
                moveToRelative(0f, -29.7f)
                horizontalLineTo(384f)
                verticalLineToRelative(-17.3f)
                horizontalLineTo(281.1f)
                close()
            }
        }.build()
        
        return _Uniregistry!!
    }

private var _Uniregistry: ImageVector? = null

