package com.composables.icons.heroicons.mini

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.heroicons.Heroicons
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Heroicons.Mini.QrCode: ImageVector
    get() {
        if (_QrCode != null) return _QrCode!!
        
        _QrCode = ImageVector.Builder(
            name = "qr-code",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 20f,
            viewportHeight = 20f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(3.75f, 2f)
                arcTo(1.75f, 1.75f, 0f, false, false, 2f, 3.75f)
                verticalLineToRelative(3.5f)
                curveTo(2f, 8.216f, 2.784f, 9f, 3.75f, 9f)
                horizontalLineToRelative(3.5f)
                arcTo(1.75f, 1.75f, 0f, false, false, 9f, 7.25f)
                verticalLineToRelative(-3.5f)
                arcTo(1.75f, 1.75f, 0f, false, false, 7.25f, 2f)
                horizontalLineToRelative(-3.5f)
                close()
                moveTo(3.5f, 3.75f)
                arcToRelative(0.25f, 0.25f, 0f, false, true, 0.25f, -0.25f)
                horizontalLineToRelative(3.5f)
                arcToRelative(0.25f, 0.25f, 0f, false, true, 0.25f, 0.25f)
                verticalLineToRelative(3.5f)
                arcToRelative(0.25f, 0.25f, 0f, false, true, -0.25f, 0.25f)
                horizontalLineToRelative(-3.5f)
                arcToRelative(0.25f, 0.25f, 0f, false, true, -0.25f, -0.25f)
                verticalLineToRelative(-3.5f)
                close()
                moveTo(3.75f, 11f)
                arcTo(1.75f, 1.75f, 0f, false, false, 2f, 12.75f)
                verticalLineToRelative(3.5f)
                curveToRelative(0f, 0.966f, 0.784f, 1.75f, 1.75f, 1.75f)
                horizontalLineToRelative(3.5f)
                arcTo(1.75f, 1.75f, 0f, false, false, 9f, 16.25f)
                verticalLineToRelative(-3.5f)
                arcTo(1.75f, 1.75f, 0f, false, false, 7.25f, 11f)
                horizontalLineToRelative(-3.5f)
                close()
                moveToRelative(-0.25f, 1.75f)
                arcToRelative(0.25f, 0.25f, 0f, false, true, 0.25f, -0.25f)
                horizontalLineToRelative(3.5f)
                arcToRelative(0.25f, 0.25f, 0f, false, true, 0.25f, 0.25f)
                verticalLineToRelative(3.5f)
                arcToRelative(0.25f, 0.25f, 0f, false, true, -0.25f, 0.25f)
                horizontalLineToRelative(-3.5f)
                arcToRelative(0.25f, 0.25f, 0f, false, true, -0.25f, -0.25f)
                verticalLineToRelative(-3.5f)
                close()
                moveToRelative(7.5f, -9f)
                curveToRelative(0f, -0.966f, 0.784f, -1.75f, 1.75f, -1.75f)
                horizontalLineToRelative(3.5f)
                curveToRelative(0.966f, 0f, 1.75f, 0.784f, 1.75f, 1.75f)
                verticalLineToRelative(3.5f)
                arcTo(1.75f, 1.75f, 0f, false, true, 16.25f, 9f)
                horizontalLineToRelative(-3.5f)
                arcTo(1.75f, 1.75f, 0f, false, true, 11f, 7.25f)
                verticalLineToRelative(-3.5f)
                close()
                moveToRelative(1.75f, -0.25f)
                arcToRelative(0.25f, 0.25f, 0f, false, false, -0.25f, 0.25f)
                verticalLineToRelative(3.5f)
                curveToRelative(0f, 0.138f, 0.112f, 0.25f, 0.25f, 0.25f)
                horizontalLineToRelative(3.5f)
                arcToRelative(0.25f, 0.25f, 0f, false, false, 0.25f, -0.25f)
                verticalLineToRelative(-3.5f)
                arcToRelative(0.25f, 0.25f, 0f, false, false, -0.25f, -0.25f)
                horizontalLineToRelative(-3.5f)
                close()
                moveToRelative(-7.26f, 1f)
                arcToRelative(1f, 1f, 0f, false, false, -1f, 1f)
                verticalLineToRelative(0.01f)
                arcToRelative(1f, 1f, 0f, false, false, 1f, 1f)
                horizontalLineToRelative(0.01f)
                arcToRelative(1f, 1f, 0f, false, false, 1f, -1f)
                verticalLineTo(5.5f)
                arcToRelative(1f, 1f, 0f, false, false, -1f, -1f)
                horizontalLineToRelative(-0.01f)
                close()
                moveToRelative(9f, 0f)
                arcToRelative(1f, 1f, 0f, false, false, -1f, 1f)
                verticalLineToRelative(0.01f)
                arcToRelative(1f, 1f, 0f, false, false, 1f, 1f)
                horizontalLineToRelative(0.01f)
                arcToRelative(1f, 1f, 0f, false, false, 1f, -1f)
                verticalLineTo(5.5f)
                arcToRelative(1f, 1f, 0f, false, false, -1f, -1f)
                horizontalLineToRelative(-0.01f)
                close()
                moveToRelative(-9f, 9f)
                arcToRelative(1f, 1f, 0f, false, false, -1f, 1f)
                verticalLineToRelative(0.01f)
                arcToRelative(1f, 1f, 0f, false, false, 1f, 1f)
                horizontalLineToRelative(0.01f)
                arcToRelative(1f, 1f, 0f, false, false, 1f, -1f)
                verticalLineToRelative(-0.01f)
                arcToRelative(1f, 1f, 0f, false, false, -1f, -1f)
                horizontalLineToRelative(-0.01f)
                close()
                moveToRelative(9f, 0f)
                arcToRelative(1f, 1f, 0f, false, false, -1f, 1f)
                verticalLineToRelative(0.01f)
                arcToRelative(1f, 1f, 0f, false, false, 1f, 1f)
                horizontalLineToRelative(0.01f)
                arcToRelative(1f, 1f, 0f, false, false, 1f, -1f)
                verticalLineToRelative(-0.01f)
                arcToRelative(1f, 1f, 0f, false, false, -1f, -1f)
                horizontalLineToRelative(-0.01f)
                close()
                moveToRelative(-3.5f, -1.5f)
                arcToRelative(1f, 1f, 0f, false, true, 1f, -1f)
                horizontalLineTo(12f)
                arcToRelative(1f, 1f, 0f, false, true, 1f, 1f)
                verticalLineToRelative(0.01f)
                arcToRelative(1f, 1f, 0f, false, true, -1f, 1f)
                horizontalLineToRelative(-0.01f)
                arcToRelative(1f, 1f, 0f, false, true, -1f, -1f)
                verticalLineTo(12f)
                close()
                moveToRelative(6f, -1f)
                arcToRelative(1f, 1f, 0f, false, false, -1f, 1f)
                verticalLineToRelative(0.01f)
                arcToRelative(1f, 1f, 0f, false, false, 1f, 1f)
                horizontalLineTo(17f)
                arcToRelative(1f, 1f, 0f, false, false, 1f, -1f)
                verticalLineTo(12f)
                arcToRelative(1f, 1f, 0f, false, false, -1f, -1f)
                horizontalLineToRelative(-0.01f)
                close()
                moveToRelative(-1f, 6f)
                arcToRelative(1f, 1f, 0f, false, true, 1f, -1f)
                horizontalLineTo(17f)
                arcToRelative(1f, 1f, 0f, false, true, 1f, 1f)
                verticalLineToRelative(0.01f)
                arcToRelative(1f, 1f, 0f, false, true, -1f, 1f)
                horizontalLineToRelative(-0.01f)
                arcToRelative(1f, 1f, 0f, false, true, -1f, -1f)
                verticalLineTo(17f)
                close()
                moveToRelative(-4f, -1f)
                arcToRelative(1f, 1f, 0f, false, false, -1f, 1f)
                verticalLineToRelative(0.01f)
                arcToRelative(1f, 1f, 0f, false, false, 1f, 1f)
                horizontalLineTo(12f)
                arcToRelative(1f, 1f, 0f, false, false, 1f, -1f)
                verticalLineTo(17f)
                arcToRelative(1f, 1f, 0f, false, false, -1f, -1f)
                horizontalLineToRelative(-0.01f)
                close()
            }
        }.build()
        
        return _QrCode!!
    }

private var _QrCode: ImageVector? = null

