package com.composables.icons.materialsymbols.sharp

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Sharp.Bath_outdoor: ImageVector
    get() {
        if (_Bath_outdoor != null) return _Bath_outdoor!!
        
        _Bath_outdoor = ImageVector.Builder(
            name = "bath_outdoor",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(240f, 451f)
                verticalLineToRelative(93f)
                quadToRelative(-20f, 14f, -30f, 28.5f)
                reflectiveQuadTo(200f, 600f)
                quadToRelative(0f, 6f, 1.5f, 12f)
                reflectiveQuadToRelative(5.5f, 12f)
                lineToRelative(33f, 16f)
                horizontalLineToRelative(90f)
                lineToRelative(6f, 17f)
                lineToRelative(44f, -17f)
                horizontalLineToRelative(160f)
                lineToRelative(29f, 38f)
                lineToRelative(107f, -16f)
                lineToRelative(44f, -62f)
                horizontalLineToRelative(40f)
                quadToRelative(0f, -13f, -10f, -27.5f)
                reflectiveQuadTo(720f, 544f)
                verticalLineToRelative(-93f)
                quadToRelative(58f, 29f, 89f, 67.5f)
                reflectiveQuadToRelative(31f, 81.5f)
                lineToRelative(40f, 60f)
                lineToRelative(-40f, 120f)
                horizontalLineTo(716f)
                lineToRelative(4f, 20f)
                lineToRelative(-100f, 40f)
                horizontalLineTo(340f)
                lineToRelative(-10f, -26f)
                lineToRelative(-110f, 26f)
                lineTo(80f, 740f)
                verticalLineToRelative(-100f)
                lineToRelative(42f, -21f)
                quadToRelative(-1f, -5f, -1.5f, -9.5f)
                reflectiveQuadToRelative(-0.5f, -9.5f)
                quadToRelative(0f, -43f, 31f, -81.5f)
                reflectiveQuadToRelative(89f, -67.5f)
                close()
                moveToRelative(-78f, 272f)
                lineToRelative(37f, -37f)
                lineToRelative(-39f, -19f)
                lineToRelative(-20f, 10f)
                verticalLineToRelative(31f)
                lineToRelative(22f, 15f)
                close()
                moveToRelative(73f, 52f)
                lineToRelative(75f, -18f)
                lineToRelative(-22f, -57f)
                horizontalLineToRelative(-18f)
                lineToRelative(-57f, 57f)
                lineToRelative(22f, 18f)
                close()
                moveToRelative(147f, 5f)
                horizontalLineToRelative(121f)
                lineToRelative(27f, -54f)
                lineToRelative(-20f, -26f)
                horizontalLineTo(392f)
                lineToRelative(-34f, 14f)
                lineToRelative(24f, 66f)
                close()
                moveToRelative(190f, 0f)
                horizontalLineToRelative(36f)
                lineToRelative(42f, -17f)
                lineToRelative(-7f, -35f)
                lineToRelative(-45f, 7f)
                lineToRelative(-26f, 45f)
                close()
                moveToRelative(138f, -60f)
                horizontalLineToRelative(87f)
                lineToRelative(17f, -51f)
                lineToRelative(-6f, -9f)
                horizontalLineToRelative(-57f)
                lineToRelative(-41f, 60f)
                close()
                moveTo(270f, 520f)
                quadToRelative(5f, -15f, 7.5f, -28.5f)
                reflectiveQuadTo(280f, 462f)
                quadToRelative(0f, -30f, -15f, -52f)
                reflectiveQuadToRelative(-34f, -47f)
                quadToRelative(-19f, -25f, -34f, -55.5f)
                reflectiveQuadTo(182f, 229f)
                quadToRelative(0f, -15f, 1.5f, -32f)
                reflectiveQuadToRelative(5.5f, -37f)
                horizontalLineToRelative(81f)
                quadToRelative(-5f, 23f, -6.5f, 38f)
                reflectiveQuadToRelative(-1.5f, 28f)
                quadToRelative(0f, 37f, 15.5f, 61.5f)
                reflectiveQuadTo(311f, 336f)
                quadToRelative(18f, 24f, 33.5f, 53f)
                reflectiveQuadToRelative(15.5f, 75f)
                quadToRelative(0f, 14f, -2f, 28f)
                reflectiveQuadToRelative(-6f, 28f)
                horizontalLineToRelative(-82f)
                close()
                moveToRelative(160f, 0f)
                quadToRelative(5f, -15f, 7.5f, -28.5f)
                reflectiveQuadTo(440f, 462f)
                quadToRelative(0f, -30f, -15f, -52f)
                reflectiveQuadToRelative(-34f, -47f)
                quadToRelative(-19f, -25f, -34f, -55.5f)
                reflectiveQuadTo(342f, 229f)
                quadToRelative(0f, -15f, 1.5f, -32f)
                reflectiveQuadToRelative(5.5f, -37f)
                horizontalLineToRelative(81f)
                quadToRelative(-5f, 23f, -7f, 38f)
                reflectiveQuadToRelative(-2f, 28f)
                quadToRelative(0f, 37f, 15.5f, 61.5f)
                reflectiveQuadTo(470f, 336f)
                quadToRelative(18f, 24f, 33.5f, 53f)
                reflectiveQuadToRelative(15.5f, 75f)
                quadToRelative(0f, 14f, -1.5f, 28f)
                reflectiveQuadToRelative(-5.5f, 28f)
                horizontalLineToRelative(-82f)
                close()
                moveToRelative(160f, 0f)
                quadToRelative(5f, -15f, 7.5f, -28.5f)
                reflectiveQuadTo(600f, 462f)
                quadToRelative(0f, -30f, -15f, -52f)
                reflectiveQuadToRelative(-34f, -47f)
                quadToRelative(-19f, -25f, -34f, -55.5f)
                reflectiveQuadTo(502f, 229f)
                quadToRelative(0f, -15f, 1.5f, -32f)
                reflectiveQuadToRelative(5.5f, -37f)
                horizontalLineToRelative(81f)
                quadToRelative(-5f, 23f, -7f, 38f)
                reflectiveQuadToRelative(-2f, 28f)
                quadToRelative(0f, 37f, 15.5f, 61.5f)
                reflectiveQuadTo(630f, 336f)
                quadToRelative(18f, 24f, 33.5f, 53f)
                reflectiveQuadToRelative(15.5f, 75f)
                quadToRelative(0f, 14f, -1.5f, 28f)
                reflectiveQuadToRelative(-5.5f, 28f)
                horizontalLineToRelative(-82f)
                close()
            }
        }.build()
        
        return _Bath_outdoor!!
    }

private var _Bath_outdoor: ImageVector? = null

