package com.composables.icons.materialsymbols.sharp

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Sharp.Letter_switch: ImageVector
    get() {
        if (_Letter_switch != null) return _Letter_switch!!
        
        _Letter_switch = ImageVector.Builder(
            name = "letter_switch",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(600f, 880f)
                verticalLineToRelative(-240f)
                horizontalLineToRelative(80f)
                verticalLineToRelative(111f)
                quadToRelative(42f, -60f, 61f, -129.5f)
                reflectiveQuadTo(760f, 480f)
                quadToRelative(0f, -72f, -19f, -141.5f)
                reflectiveQuadTo(680f, 209f)
                verticalLineToRelative(111f)
                horizontalLineToRelative(-80f)
                verticalLineToRelative(-240f)
                horizontalLineToRelative(240f)
                verticalLineToRelative(80f)
                horizontalLineToRelative(-97f)
                quadToRelative(50f, 70f, 73.5f, 152f)
                reflectiveQuadTo(840f, 480f)
                quadToRelative(0f, 86f, -23.5f, 168f)
                reflectiveQuadTo(743f, 800f)
                horizontalLineToRelative(97f)
                verticalLineToRelative(80f)
                horizontalLineTo(600f)
                close()
                moveTo(306f, 678f)
                horizontalLineToRelative(-70f)
                verticalLineToRelative(48f)
                horizontalLineToRelative(70f)
                verticalLineToRelative(-48f)
                close()
                moveToRelative(118f, 0f)
                horizontalLineToRelative(-70f)
                verticalLineToRelative(48f)
                horizontalLineToRelative(70f)
                verticalLineToRelative(-48f)
                close()
                moveToRelative(-1f, -169f)
                verticalLineToRelative(30f)
                horizontalLineToRelative(79f)
                verticalLineToRelative(44f)
                horizontalLineToRelative(-79f)
                verticalLineToRelative(35f)
                horizontalLineToRelative(-43f)
                verticalLineToRelative(-35f)
                horizontalLineTo(279f)
                verticalLineToRelative(35f)
                horizontalLineToRelative(-43f)
                verticalLineToRelative(-35f)
                horizontalLineToRelative(-79f)
                verticalLineToRelative(-44f)
                horizontalLineToRelative(79f)
                verticalLineToRelative(-30f)
                horizontalLineToRelative(43f)
                verticalLineToRelative(30f)
                horizontalLineToRelative(101f)
                verticalLineToRelative(-30f)
                horizontalLineToRelative(43f)
                close()
                moveTo(174f, 880f)
                quadToRelative(-5f, -12f, -12.5f, -23.5f)
                reflectiveQuadTo(144f, 836f)
                quadToRelative(42f, -6f, 81.5f, -18.5f)
                reflectiveQuadTo(288f, 770f)
                horizontalLineTo(152f)
                verticalLineToRelative(-43f)
                horizontalLineToRelative(40f)
                verticalLineToRelative(-92f)
                horizontalLineToRelative(113f)
                verticalLineToRelative(-39f)
                horizontalLineToRelative(48f)
                verticalLineToRelative(39f)
                horizontalLineToRelative(118f)
                verticalLineToRelative(92f)
                horizontalLineToRelative(35f)
                verticalLineToRelative(43f)
                horizontalLineTo(370f)
                quadToRelative(29f, 29f, 66f, 46f)
                reflectiveQuadToRelative(79f, 20f)
                quadToRelative(-8f, 10f, -14.5f, 21f)
                reflectiveQuadTo(489f, 880f)
                quadToRelative(-47f, -5f, -87.5f, -27.5f)
                reflectiveQuadTo(332f, 792f)
                quadToRelative(-25f, 40f, -68.5f, 58.5f)
                reflectiveQuadTo(174f, 880f)
                close()
                moveToRelative(35f, -464f)
                lineToRelative(-48f, -22f)
                quadToRelative(29f, -41f, 48.5f, -86f)
                reflectiveQuadToRelative(30.5f, -93f)
                horizontalLineToRelative(-79f)
                verticalLineToRelative(-52f)
                horizontalLineToRelative(91f)
                quadToRelative(4f, -20f, 6f, -41f)
                reflectiveQuadToRelative(3f, -42f)
                lineToRelative(53f, 18f)
                quadToRelative(0f, 18f, -4f, 35f)
                reflectiveQuadToRelative(-9f, 34f)
                horizontalLineToRelative(31f)
                quadToRelative(29f, 0f, 49f, 22.5f)
                reflectiveQuadToRelative(21f, 52.5f)
                quadToRelative(1f, 36f, -4.5f, 71f)
                reflectiveQuadTo(380f, 382f)
                quadToRelative(-3f, 9f, -9.5f, 17f)
                reflectiveQuadTo(356f, 412f)
                quadToRelative(-8f, 5f, -18f, 8f)
                reflectiveQuadToRelative(-20f, 1f)
                lineToRelative(-48f, -9f)
                lineToRelative(-8f, -48f)
                horizontalLineToRelative(48f)
                quadToRelative(9f, 0f, 18f, -2.5f)
                reflectiveQuadToRelative(12f, -10.5f)
                quadToRelative(9f, -26f, 11.5f, -53.5f)
                reflectiveQuadTo(353f, 242f)
                quadToRelative(0f, -14f, -10.5f, -24.5f)
                reflectiveQuadTo(318f, 207f)
                horizontalLineToRelative(-26f)
                quadToRelative(-13f, 55f, -33.5f, 107.5f)
                reflectiveQuadTo(209f, 416f)
                close()
                moveToRelative(241f, -284f)
                quadToRelative(21f, 34f, 38.5f, 70f)
                reflectiveQuadToRelative(31.5f, 74f)
                lineToRelative(-52f, 22f)
                quadToRelative(-8f, -39f, -25f, -75.5f)
                reflectiveQuadTo(402f, 154f)
                lineToRelative(48f, -22f)
                close()
            }
        }.build()
        
        return _Letter_switch!!
    }

private var _Letter_switch: ImageVector? = null

