package com.composables.icons.materialsymbols.sharp

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Sharp.Reg_logo_ift: ImageVector
    get() {
        if (_Reg_logo_ift != null) return _Reg_logo_ift!!
        
        _Reg_logo_ift = ImageVector.Builder(
            name = "reg_logo_ift",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(243f, 614f)
                quadToRelative(-13f, 2f, -26f, 1.5f)
                reflectiveQuadToRelative(-27f, -2.5f)
                quadToRelative(-64f, -8f, -107f, -56f)
                reflectiveQuadTo(40f, 444f)
                quadToRelative(0f, -70f, 40f, -110f)
                reflectiveQuadToRelative(94f, -23f)
                quadToRelative(13f, -21f, 31f, -31.5f)
                reflectiveQuadToRelative(40f, -10.5f)
                quadToRelative(57f, 0f, 104f, 54.5f)
                reflectiveQuadTo(396f, 443f)
                quadToRelative(0f, 65f, -46.5f, 117f)
                reflectiveQuadTo(243f, 614f)
                quadToRelative(51f, -6f, 78f, -34.5f)
                reflectiveQuadToRelative(22f, -68.5f)
                quadToRelative(-1f, -8f, -3.5f, -16f)
                reflectiveQuadToRelative(-6.5f, -19f)
                quadToRelative(9f, -15f, 13.5f, -32f)
                reflectiveQuadToRelative(4.5f, -34f)
                quadToRelative(0f, -48f, -34.5f, -88f)
                reflectiveQuadTo(239f, 282f)
                quadToRelative(-18f, 0f, -30.5f, 7.5f)
                reflectiveQuadTo(185f, 316f)
                quadToRelative(-23f, -12f, -16f, -8f)
                reflectiveQuadToRelative(5f, 3f)
                quadToRelative(-13f, 20f, -20.5f, 43f)
                reflectiveQuadTo(141f, 412f)
                quadToRelative(-13f, 14f, -20f, 32.5f)
                reflectiveQuadToRelative(-7f, 40.5f)
                quadToRelative(0f, 32f, 16f, 59.5f)
                reflectiveQuadToRelative(44f, 42.5f)
                quadToRelative(14f, 14f, 31.5f, 21f)
                reflectiveQuadToRelative(37.5f, 6f)
                close()
                moveToRelative(76f, -74f)
                quadToRelative(0f, 26f, -23f, 43.5f)
                reflectiveQuadTo(236f, 601f)
                quadToRelative(-17f, 0f, -32.5f, -3.5f)
                reflectiveQuadTo(174f, 587f)
                quadToRelative(-17f, -18f, -26.5f, -51f)
                reflectiveQuadToRelative(-9.5f, -76f)
                quadToRelative(0f, -12f, 0.5f, -25f)
                reflectiveQuadToRelative(2.5f, -23f)
                quadToRelative(5f, -5f, 10f, -9f)
                reflectiveQuadToRelative(10f, -6f)
                quadToRelative(-1f, 6f, -1f, 12.5f)
                verticalLineToRelative(12.5f)
                quadToRelative(0f, 55f, 20f, 85.5f)
                reflectiveQuadToRelative(55f, 30.5f)
                quadToRelative(19f, 0f, 37.5f, -8.5f)
                reflectiveQuadTo(311f, 504f)
                quadToRelative(5f, 11f, 6.5f, 19.5f)
                reflectiveQuadTo(319f, 540f)
                close()
                moveToRelative(-8f, -36f)
                quadToRelative(-13f, -31f, -38.5f, -59.5f)
                reflectiveQuadTo(218f, 401f)
                quadToRelative(-15f, -8f, -29.5f, -9f)
                reflectiveQuadToRelative(-27.5f, 5f)
                quadToRelative(2f, -24f, 8.5f, -44.5f)
                reflectiveQuadTo(185f, 316f)
                quadToRelative(34f, 8f, 82f, 60.5f)
                reflectiveQuadTo(333f, 477f)
                quadToRelative(-5f, 8f, -10f, 14.5f)
                reflectiveQuadTo(311f, 504f)
                close()
                moveToRelative(173f, 186f)
                verticalLineToRelative(-183f)
                horizontalLineToRelative(-39f)
                verticalLineToRelative(-51f)
                horizontalLineToRelative(102f)
                verticalLineToRelative(234f)
                horizontalLineToRelative(-63f)
                close()
                moveToRelative(30f, -256f)
                quadToRelative(-16f, 0f, -26.5f, -11f)
                reflectiveQuadTo(477f, 396f)
                quadToRelative(0f, -16f, 10.5f, -26.5f)
                reflectiveQuadTo(514f, 359f)
                quadToRelative(16f, 0f, 26.5f, 10.5f)
                reflectiveQuadTo(551f, 396f)
                quadToRelative(0f, 16f, -10.5f, 27f)
                reflectiveQuadTo(514f, 434f)
                close()
                moveToRelative(108f, 256f)
                verticalLineToRelative(-184f)
                horizontalLineToRelative(-39f)
                verticalLineToRelative(-51f)
                horizontalLineToRelative(39f)
                verticalLineToRelative(-17f)
                quadToRelative(0f, -37f, 18f, -56f)
                reflectiveQuadToRelative(54f, -19f)
                quadToRelative(14f, 0f, 25f, 1.5f)
                reflectiveQuadToRelative(21f, 4.5f)
                verticalLineToRelative(51f)
                quadToRelative(-19f, -6f, -28f, -4f)
                quadToRelative(-14f, 0f, -21f, 7f)
                reflectiveQuadToRelative(-7f, 21f)
                verticalLineToRelative(11f)
                horizontalLineToRelative(56f)
                verticalLineToRelative(51f)
                horizontalLineToRelative(-54f)
                verticalLineToRelative(184f)
                horizontalLineToRelative(-64f)
                close()
                moveToRelative(252f, 0f)
                quadToRelative(-36f, 0f, -54f, -18.5f)
                reflectiveQuadTo(802f, 615f)
                verticalLineToRelative(-108f)
                horizontalLineToRelative(-36f)
                verticalLineToRelative(-51f)
                horizontalLineToRelative(36f)
                verticalLineToRelative(-93f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(93f)
                horizontalLineToRelative(54f)
                verticalLineToRelative(51f)
                horizontalLineToRelative(-56f)
                verticalLineToRelative(102f)
                quadToRelative(0f, 14f, 6.5f, 21.5f)
                reflectiveQuadTo(891f, 638f)
                quadToRelative(5f, 0f, 20f, -3f)
                verticalLineToRelative(52f)
                quadToRelative(-11f, 2f, -17f, 2.5f)
                reflectiveQuadToRelative(-20f, 0.5f)
                close()
            }
        }.build()
        
        return _Reg_logo_ift!!
    }

private var _Reg_logo_ift: ImageVector? = null

