package com.composables.icons.materialsymbols.sharp

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Sharp.Smart_ventilation: ImageVector
    get() {
        if (_Smart_ventilation != null) return _Smart_ventilation!!
        
        _Smart_ventilation = ImageVector.Builder(
            name = "smart_ventilation",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(350f, 920f)
                quadToRelative(-39f, 0f, -66.5f, -27.5f)
                reflectiveQuadTo(256f, 826f)
                quadToRelative(0f, -23f, 11f, -44f)
                reflectiveQuadToRelative(31f, -34f)
                quadToRelative(20f, -14f, 33f, -35f)
                reflectiveQuadToRelative(18f, -45f)
                quadToRelative(-4f, -2f, -8.5f, -4f)
                reflectiveQuadToRelative(-8.5f, -4f)
                lineToRelative(-88f, 31f)
                quadToRelative(-14f, 5f, -28.5f, 9f)
                reflectiveQuadToRelative(-29.5f, 4f)
                quadToRelative(-69f, 0f, -107.5f, -56f)
                reflectiveQuadTo(40f, 510f)
                quadToRelative(0f, -43f, 27f, -68.5f)
                reflectiveQuadToRelative(66f, -25.5f)
                quadToRelative(23f, 0f, 44f, 11f)
                reflectiveQuadToRelative(34f, 31f)
                quadToRelative(14f, 20f, 35.5f, 32.5f)
                reflectiveQuadTo(292f, 508f)
                lineToRelative(4f, -8f)
                lineToRelative(4f, -8f)
                lineToRelative(-31f, -88f)
                quadToRelative(-5f, -14f, -9f, -28f)
                reflectiveQuadToRelative(-4f, -29f)
                quadToRelative(0f, -69f, 55.5f, -108f)
                reflectiveQuadTo(450f, 200f)
                quadToRelative(44f, 0f, 69f, 27.5f)
                reflectiveQuadToRelative(25f, 66.5f)
                quadToRelative(0f, 23f, -11f, 44f)
                reflectiveQuadToRelative(-31f, 34f)
                quadToRelative(-20f, 14f, -33f, 35f)
                reflectiveQuadToRelative(-18f, 45f)
                quadToRelative(4f, 2f, 8.5f, 4f)
                reflectiveQuadToRelative(8.5f, 4f)
                lineToRelative(88f, -31f)
                quadToRelative(14f, -5f, 28.5f, -9f)
                reflectiveQuadToRelative(29.5f, -4f)
                quadToRelative(69f, 0f, 107.5f, 59.5f)
                reflectiveQuadTo(760f, 610f)
                quadToRelative(0f, 39f, -27f, 66.5f)
                reflectiveQuadTo(667f, 704f)
                quadToRelative(-23f, 0f, -44f, -10.5f)
                reflectiveQuadTo(589f, 663f)
                quadToRelative(-14f, -20f, -35.5f, -33f)
                reflectiveQuadTo(508f, 612f)
                lineToRelative(-4f, 8f)
                lineToRelative(-4f, 8f)
                lineToRelative(31f, 89f)
                quadToRelative(5f, 14f, 9f, 26.5f)
                reflectiveQuadToRelative(4f, 26.5f)
                quadToRelative(1f, 77f, -58f, 113.5f)
                reflectiveQuadTo(350f, 920f)
                close()
                moveToRelative(50f, -320f)
                quadToRelative(17f, 0f, 28.5f, -11.5f)
                reflectiveQuadTo(440f, 560f)
                quadToRelative(0f, -17f, -11.5f, -28.5f)
                reflectiveQuadTo(400f, 520f)
                quadToRelative(-17f, 0f, -28.5f, 11.5f)
                reflectiveQuadTo(360f, 560f)
                quadToRelative(0f, 17f, 11.5f, 28.5f)
                reflectiveQuadTo(400f, 600f)
                close()
                moveToRelative(-28f, -156f)
                close()
                moveToRelative(-88f, 144f)
                close()
                moveToRelative(144f, 88f)
                close()
                moveToRelative(88f, -144f)
                close()
                moveToRelative(-147f, -88f)
                horizontalLineToRelative(3f)
                quadToRelative(5f, -42f, 28f, -79f)
                reflectiveQuadToRelative(58f, -60f)
                quadToRelative(3f, -2f, 4.5f, -4.5f)
                reflectiveQuadToRelative(1.5f, -6.5f)
                quadToRelative(0f, -6f, -4f, -10f)
                reflectiveQuadToRelative(-10f, -4f)
                quadToRelative(-42f, 0f, -78f, 15.5f)
                reflectiveQuadTo(336f, 346f)
                quadToRelative(0f, 7f, 2f, 12.5f)
                reflectiveQuadToRelative(4f, 11.5f)
                lineToRelative(27f, 74f)
                close()
                moveTo(186f, 624f)
                quadToRelative(10f, 0f, 24f, -6f)
                lineToRelative(75f, -27f)
                lineToRelative(-0.5f, -1.5f)
                lineToRelative(-0.5f, -1.5f)
                quadToRelative(-42f, -5f, -78.5f, -28f)
                reflectiveQuadTo(146f, 502f)
                quadToRelative(-2f, -3f, -5f, -4.5f)
                reflectiveQuadToRelative(-7f, -1.5f)
                quadToRelative(-6f, 0f, -10f, 4f)
                reflectiveQuadToRelative(-4f, 10f)
                quadToRelative(0f, 42f, 16f, 78f)
                reflectiveQuadToRelative(50f, 36f)
                close()
                moveToRelative(164f, 216f)
                quadToRelative(43f, 0f, 78.5f, -16f)
                reflectiveQuadToRelative(35.5f, -50f)
                quadToRelative(0f, -9f, -6f, -25f)
                lineToRelative(-27f, -74f)
                lineToRelative(-1.5f, 0.5f)
                lineToRelative(-1.5f, 0.5f)
                quadToRelative(-6f, 42f, -28f, 78.5f)
                reflectiveQuadTo(342f, 814f)
                quadToRelative(-3f, 2f, -5f, 6f)
                reflectiveQuadToRelative(-1f, 8f)
                quadToRelative(1f, 6f, 5f, 9f)
                reflectiveQuadToRelative(9f, 3f)
                close()
                moveToRelative(316f, -216f)
                quadToRelative(6f, 0f, 10f, -4f)
                reflectiveQuadToRelative(4f, -10f)
                quadToRelative(0f, -42f, -15.5f, -77.5f)
                reflectiveQuadTo(614f, 496f)
                quadToRelative(-10f, 0f, -24f, 6f)
                lineToRelative(-74f, 27f)
                verticalLineToRelative(3f)
                quadToRelative(42f, 5f, 79f, 28f)
                reflectiveQuadToRelative(60f, 58f)
                quadToRelative(2f, 3f, 4.5f, 4.5f)
                reflectiveQuadToRelative(6.5f, 1.5f)
                close()
                moveToRelative(74f, -224f)
                quadToRelative(0f, -75f, -52.5f, -127.5f)
                reflectiveQuadTo(560f, 220f)
                quadToRelative(75f, 0f, 127.5f, -52.5f)
                reflectiveQuadTo(740f, 40f)
                quadToRelative(0f, 75f, 52.5f, 127.5f)
                reflectiveQuadTo(920f, 220f)
                quadToRelative(-75f, 0f, -127.5f, 52.5f)
                reflectiveQuadTo(740f, 400f)
                close()
            }
        }.build()
        
        return _Smart_ventilation!!
    }

private var _Smart_ventilation: ImageVector? = null

