package com.composables.icons.materialsymbols.sharp

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Sharp.Ulna_radius: ImageVector
    get() {
        if (_Ulna_radius != null) return _Ulna_radius!!
        
        _Ulna_radius = ImageVector.Builder(
            name = "ulna_radius",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(720f, 878f)
                quadToRelative(-22f, 0f, -42.5f, -8.5f)
                reflectiveQuadTo(643f, 847f)
                lineToRelative(-4.5f, -4.5f)
                lineToRelative(-4.5f, -4.5f)
                horizontalLineToRelative(-94f)
                quadToRelative(-42f, 0f, -71f, -29.5f)
                reflectiveQuadTo(440f, 737f)
                quadToRelative(0f, -23f, 10f, -43.5f)
                reflectiveQuadToRelative(30f, -36.5f)
                lineToRelative(40f, -32f)
                verticalLineToRelative(-222f)
                lineToRelative(-62f, -88f)
                quadToRelative(-9f, -13f, -13.5f, -28f)
                reflectiveQuadToRelative(-4.5f, -29f)
                quadToRelative(0f, -42f, 29f, -71f)
                reflectiveQuadToRelative(71f, -29f)
                horizontalLineToRelative(200f)
                quadToRelative(42f, 0f, 70.5f, 28.5f)
                reflectiveQuadTo(839f, 257f)
                quadToRelative(0f, 15f, -4f, 29f)
                reflectiveQuadToRelative(-13f, 27f)
                lineToRelative(-62f, 90f)
                verticalLineToRelative(224f)
                lineToRelative(39f, 39f)
                quadToRelative(20f, 20f, 30.5f, 43.5f)
                reflectiveQuadTo(840f, 758f)
                quadToRelative(0f, 50f, -35f, 85f)
                reflectiveQuadToRelative(-85f, 35f)
                close()
                moveToRelative(0f, -80f)
                quadToRelative(17f, 0f, 28.5f, -11.5f)
                reflectiveQuadTo(760f, 758f)
                quadToRelative(0f, -15f, -8.5f, -25f)
                lineToRelative(-8.5f, -10f)
                lineToRelative(-39f, -39f)
                quadToRelative(-12f, -12f, -18f, -27f)
                reflectiveQuadToRelative(-6f, -30f)
                verticalLineToRelative(-223f)
                quadToRelative(0f, -12f, 3.5f, -24f)
                reflectiveQuadToRelative(10.5f, -22f)
                lineToRelative(62f, -89f)
                quadToRelative(2f, -3f, 4f, -12f)
                quadToRelative(0f, -8f, -6f, -13.5f)
                reflectiveQuadToRelative(-14f, -5.5f)
                horizontalLineTo(540f)
                quadToRelative(-8f, 0f, -14f, 6f)
                reflectiveQuadToRelative(-6f, 14f)
                quadToRelative(0f, 3f, 1f, 5.5f)
                reflectiveQuadToRelative(3f, 5.5f)
                lineToRelative(62f, 89f)
                quadToRelative(7f, 10f, 10.5f, 21.5f)
                reflectiveQuadTo(600f, 404f)
                verticalLineToRelative(221f)
                quadToRelative(0f, 18f, -8f, 34.5f)
                reflectiveQuadTo(570f, 687f)
                lineToRelative(-40f, 33f)
                quadToRelative(-5f, 4f, -7.5f, 8.5f)
                reflectiveQuadTo(520f, 739f)
                quadToRelative(0f, 8f, 5.5f, 13.5f)
                reflectiveQuadTo(540f, 758f)
                horizontalLineToRelative(89f)
                quadToRelative(18f, 0f, 32f, 6.5f)
                reflectiveQuadToRelative(30f, 22.5f)
                quadToRelative(5f, 5f, 12.5f, 8f)
                reflectiveQuadToRelative(16.5f, 3f)
                close()
                moveToRelative(-367f, 28f)
                quadToRelative(-11f, 5f, -22.5f, 7.5f)
                reflectiveQuadTo(307f, 836f)
                quadToRelative(-45f, 0f, -76f, -30.5f)
                reflectiveQuadTo(200f, 731f)
                verticalLineToRelative(-364f)
                lineToRelative(-70f, -147f)
                quadToRelative(-5f, -10f, -7.5f, -21f)
                reflectiveQuadToRelative(-2.5f, -22f)
                quadToRelative(0f, -42f, 29f, -70.5f)
                reflectiveQuadToRelative(71f, -28.5f)
                horizontalLineToRelative(180f)
                verticalLineToRelative(80f)
                quadToRelative(42f, 0f, 71f, 29f)
                reflectiveQuadToRelative(29f, 71f)
                quadToRelative(0f, 17f, -5f, 31.5f)
                reflectiveQuadTo(480f, 317f)
                lineToRelative(-40f, 54f)
                verticalLineToRelative(200f)
                lineToRelative(43f, 65f)
                quadToRelative(8f, 13f, 12.5f, 27.5f)
                reflectiveQuadTo(500f, 692f)
                quadToRelative(0f, 29f, -15f, 53f)
                reflectiveQuadToRelative(-40f, 36f)
                lineToRelative(-92f, 45f)
                close()
                moveToRelative(-35f, -72f)
                lineToRelative(91f, -45f)
                quadToRelative(5f, -2f, 8f, -7f)
                reflectiveQuadToRelative(3f, -10f)
                lineToRelative(-4f, -12f)
                lineToRelative(-36f, -55f)
                quadToRelative(-10f, -15f, -15f, -32.5f)
                reflectiveQuadToRelative(-5f, -34.5f)
                verticalLineToRelative(-174f)
                quadToRelative(0f, -20f, 6f, -38f)
                reflectiveQuadToRelative(18f, -34f)
                lineToRelative(32f, -42f)
                quadToRelative(2f, -3f, 4f, -12f)
                quadToRelative(0f, -8f, -6f, -14f)
                reflectiveQuadToRelative(-14f, -6f)
                horizontalLineToRelative(-40f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(320f, 198f)
                verticalLineToRelative(-40f)
                horizontalLineTo(220f)
                quadToRelative(-8f, 0f, -14f, 5.5f)
                reflectiveQuadToRelative(-6f, 13.5f)
                quadToRelative(0f, -1f, 2f, 9f)
                lineToRelative(66f, 138f)
                quadToRelative(6f, 12f, 9f, 25f)
                reflectiveQuadToRelative(3f, 27f)
                verticalLineToRelative(355f)
                quadToRelative(0f, 11f, 8f, 18.5f)
                reflectiveQuadToRelative(19f, 7.5f)
                quadToRelative(3f, 0f, 11f, -3f)
                close()
                moveToRelative(322f, -236f)
                close()
                moveToRelative(-330f, -61f)
                close()
            }
        }.build()
        
        return _Ulna_radius!!
    }

private var _Ulna_radius: ImageVector? = null

