package com.composables.icons.materialsymbols.roundedfilled

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.RoundedFilled.Bath_outdoor: ImageVector
    get() {
        if (_Bath_outdoor != null) return _Bath_outdoor!!
        
        _Bath_outdoor = ImageVector.Builder(
            name = "bath_outdoor",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(240f, 451f)
                verticalLineToRelative(93f)
                quadToRelative(-20f, 14f, -30f, 28.5f)
                reflectiveQuadTo(200f, 600f)
                quadToRelative(0f, 6f, 1.5f, 12f)
                reflectiveQuadToRelative(5.5f, 12f)
                lineToRelative(33f, 16f)
                horizontalLineToRelative(76f)
                quadToRelative(6f, 0f, 11.5f, 3.5f)
                reflectiveQuadToRelative(7.5f, 9.5f)
                lineToRelative(1f, 4f)
                lineToRelative(37f, -14f)
                quadToRelative(3f, -1f, 14f, -3f)
                horizontalLineToRelative(143f)
                quadToRelative(5f, 0f, 9f, 2f)
                reflectiveQuadToRelative(7f, 6f)
                lineToRelative(23f, 30f)
                lineToRelative(107f, -16f)
                lineToRelative(38f, -54f)
                quadToRelative(3f, -4f, 7f, -6f)
                reflectiveQuadToRelative(9f, -2f)
                horizontalLineToRelative(30f)
                quadToRelative(0f, -13f, -10f, -27.5f)
                reflectiveQuadTo(720f, 544f)
                verticalLineToRelative(-93f)
                quadToRelative(58f, 29f, 89f, 67.5f)
                reflectiveQuadToRelative(31f, 81.5f)
                lineToRelative(35f, 52f)
                quadToRelative(2f, 4f, 3f, 8f)
                reflectiveQuadToRelative(-1f, 9f)
                lineToRelative(-32f, 97f)
                quadToRelative(-2f, 6f, -7f, 10f)
                reflectiveQuadToRelative(-12f, 4f)
                horizontalLineTo(716f)
                lineToRelative(1f, 4f)
                quadToRelative(2f, 7f, -1.5f, 13f)
                reflectiveQuadToRelative(-10.5f, 9f)
                lineToRelative(-78f, 31f)
                quadToRelative(-2f, 1f, -15f, 3f)
                horizontalLineTo(354f)
                quadToRelative(-6f, 0f, -11.5f, -3.5f)
                reflectiveQuadTo(335f, 827f)
                lineToRelative(-5f, -13f)
                lineToRelative(-101f, 24f)
                quadToRelative(-5f, 1f, -8.5f, 0f)
                reflectiveQuadToRelative(-7.5f, -3f)
                lineTo(88f, 746f)
                quadToRelative(-4f, -3f, -6f, -7f)
                reflectiveQuadToRelative(-2f, -9f)
                verticalLineToRelative(-78f)
                quadToRelative(0f, -6f, 3f, -11f)
                reflectiveQuadToRelative(8f, -7f)
                lineToRelative(31f, -15f)
                quadToRelative(-1f, -5f, -1.5f, -9.5f)
                reflectiveQuadToRelative(-0.5f, -9.5f)
                quadToRelative(0f, -43f, 31f, -81.5f)
                reflectiveQuadToRelative(89f, -67.5f)
                close()
                moveToRelative(-9f, -88f)
                quadToRelative(-22f, -29f, -35.5f, -63f)
                reflectiveQuadTo(182f, 229f)
                verticalLineToRelative(-14f)
                quadToRelative(0f, -7f, 1f, -14f)
                quadToRelative(2f, -17f, 12.5f, -29f)
                reflectiveQuadToRelative(27.5f, -12f)
                quadToRelative(18f, 0f, 30f, 12f)
                reflectiveQuadToRelative(10f, 29f)
                quadToRelative(-1f, 6f, -1.5f, 12.5f)
                reflectiveQuadTo(261f, 226f)
                quadToRelative(0f, 31f, 15f, 58f)
                reflectiveQuadToRelative(34f, 52f)
                quadToRelative(21f, 29f, 35f, 61f)
                reflectiveQuadToRelative(14f, 67f)
                verticalLineToRelative(15f)
                quadToRelative(-1f, 17f, -12f, 29f)
                reflectiveQuadToRelative(-28f, 12f)
                quadToRelative(-17f, 0f, -29.5f, -11.5f)
                reflectiveQuadTo(279f, 480f)
                quadToRelative(1f, -5f, 1f, -9f)
                verticalLineToRelative(-9f)
                quadToRelative(0f, -29f, -16f, -52.5f)
                reflectiveQuadTo(231f, 363f)
                close()
                moveToRelative(160f, 0f)
                quadToRelative(-22f, -29f, -35.5f, -63f)
                reflectiveQuadTo(342f, 229f)
                verticalLineToRelative(-14f)
                quadToRelative(0f, -7f, 1f, -14f)
                quadToRelative(2f, -17f, 12.5f, -29f)
                reflectiveQuadToRelative(27.5f, -12f)
                quadToRelative(18f, 0f, 30f, 12f)
                reflectiveQuadToRelative(10f, 29f)
                quadToRelative(-1f, 6f, -1.5f, 12.5f)
                reflectiveQuadTo(421f, 226f)
                quadToRelative(0f, 31f, 15f, 58f)
                reflectiveQuadToRelative(34f, 52f)
                quadToRelative(21f, 29f, 35f, 61f)
                reflectiveQuadToRelative(14f, 67f)
                verticalLineToRelative(15f)
                quadToRelative(-1f, 17f, -12f, 29f)
                reflectiveQuadToRelative(-28f, 12f)
                quadToRelative(-17f, 0f, -29.5f, -11.5f)
                reflectiveQuadTo(439f, 480f)
                quadToRelative(1f, -5f, 1f, -9f)
                verticalLineToRelative(-9f)
                quadToRelative(0f, -29f, -16f, -52.5f)
                reflectiveQuadTo(391f, 363f)
                close()
                moveToRelative(160f, 0f)
                quadToRelative(-22f, -29f, -35.5f, -63f)
                reflectiveQuadTo(502f, 229f)
                verticalLineToRelative(-14f)
                quadToRelative(0f, -7f, 1f, -14f)
                quadToRelative(2f, -17f, 12.5f, -29f)
                reflectiveQuadToRelative(27.5f, -12f)
                quadToRelative(18f, 0f, 30f, 12f)
                reflectiveQuadToRelative(10f, 29f)
                quadToRelative(-1f, 6f, -1.5f, 12.5f)
                reflectiveQuadTo(581f, 226f)
                quadToRelative(0f, 31f, 15f, 58f)
                reflectiveQuadToRelative(34f, 52f)
                quadToRelative(21f, 29f, 35f, 61f)
                reflectiveQuadToRelative(14f, 67f)
                verticalLineToRelative(15f)
                quadToRelative(-1f, 17f, -12f, 29f)
                reflectiveQuadToRelative(-28f, 12f)
                quadToRelative(-17f, 0f, -29.5f, -11.5f)
                reflectiveQuadTo(599f, 480f)
                quadToRelative(1f, -5f, 1f, -9f)
                verticalLineToRelative(-9f)
                quadToRelative(0f, -29f, -16f, -52.5f)
                reflectiveQuadTo(551f, 363f)
                close()
            }
        }.build()
        
        return _Bath_outdoor!!
    }

private var _Bath_outdoor: ImageVector? = null

