package com.composables.icons.materialsymbols.roundedfilled

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.RoundedFilled.Bring_your_own_ip: ImageVector
    get() {
        if (_Bring_your_own_ip != null) return _Bring_your_own_ip!!
        
        _Bring_your_own_ip = ImageVector.Builder(
            name = "bring_your_own_ip",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(480f, 880f)
                quadToRelative(-83f, 0f, -156f, -31.5f)
                reflectiveQuadTo(197f, 763f)
                quadToRelative(-54f, -54f, -85.5f, -127f)
                reflectiveQuadTo(80f, 480f)
                quadToRelative(0f, -83f, 31.5f, -156f)
                reflectiveQuadTo(197f, 197f)
                quadToRelative(54f, -54f, 127f, -85.5f)
                reflectiveQuadTo(480f, 80f)
                quadToRelative(10f, 0f, 22f, 0.5f)
                reflectiveQuadToRelative(22f, 1.5f)
                quadToRelative(17f, 2f, 26f, 14f)
                reflectiveQuadToRelative(9f, 30f)
                quadToRelative(0f, 17f, -11f, 27.5f)
                reflectiveQuadToRelative(-28f, 8.5f)
                quadToRelative(-10f, -1f, -20f, -0.5f)
                reflectiveQuadToRelative(-20f, 0.5f)
                quadToRelative(-26f, 36f, -45f, 75.5f)
                reflectiveQuadTo(404f, 320f)
                horizontalLineToRelative(76f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(520f, 360f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(480f, 400f)
                horizontalLineToRelative(-94f)
                quadToRelative(-3f, 20f, -4.5f, 40f)
                reflectiveQuadToRelative(-1.5f, 40f)
                quadToRelative(0f, 20f, 1.5f, 40f)
                reflectiveQuadToRelative(4.5f, 40f)
                horizontalLineToRelative(188f)
                quadToRelative(3f, -20f, 4.5f, -40f)
                reflectiveQuadToRelative(1.5f, -40f)
                verticalLineToRelative(-19f)
                quadToRelative(0f, -9f, -1f, -19f)
                quadToRelative(-2f, -16f, 9.5f, -29f)
                reflectiveQuadToRelative(27.5f, -13f)
                quadToRelative(17f, 0f, 29f, 10f)
                reflectiveQuadToRelative(14f, 27f)
                quadToRelative(1f, 10f, 1f, 21.5f)
                verticalLineToRelative(21.5f)
                quadToRelative(0f, 20f, -1.5f, 40f)
                reflectiveQuadToRelative(-4.5f, 40f)
                horizontalLineToRelative(136f)
                quadToRelative(5f, -20f, 7.5f, -40f)
                reflectiveQuadToRelative(2.5f, -40f)
                verticalLineToRelative(-18f)
                quadToRelative(0f, -8f, -2f, -18f)
                quadToRelative(-2f, -16f, 9f, -30f)
                reflectiveQuadToRelative(27f, -14f)
                quadToRelative(18f, 0f, 30f, 9.5f)
                reflectiveQuadToRelative(14f, 26.5f)
                quadToRelative(1f, 10f, 1.5f, 22f)
                reflectiveQuadToRelative(0.5f, 22f)
                quadToRelative(0f, 83f, -31.5f, 156f)
                reflectiveQuadTo(763f, 763f)
                quadToRelative(-54f, 54f, -127f, 85.5f)
                reflectiveQuadTo(480f, 880f)
                close()
                moveTo(170f, 560f)
                horizontalLineToRelative(136f)
                quadToRelative(-3f, -20f, -4.5f, -40f)
                reflectiveQuadToRelative(-1.5f, -40f)
                quadToRelative(0f, -20f, 1.5f, -40f)
                reflectiveQuadToRelative(4.5f, -40f)
                horizontalLineTo(170f)
                quadToRelative(-5f, 20f, -7.5f, 40f)
                reflectiveQuadToRelative(-2.5f, 40f)
                quadToRelative(0f, 20f, 2.5f, 40f)
                reflectiveQuadToRelative(7.5f, 40f)
                close()
                moveToRelative(34f, -240f)
                horizontalLineToRelative(118f)
                quadToRelative(9f, -37f, 22.5f, -72.5f)
                reflectiveQuadTo(376f, 178f)
                quadToRelative(-55f, 18f, -99f, 54.5f)
                reflectiveQuadTo(204f, 320f)
                close()
                moveToRelative(496f, 0f)
                quadToRelative(-25f, 0f, -42.5f, -17.5f)
                reflectiveQuadTo(640f, 260f)
                verticalLineToRelative(-120f)
                quadToRelative(0f, -25f, 17.5f, -42.5f)
                reflectiveQuadTo(700f, 80f)
                horizontalLineToRelative(120f)
                quadToRelative(25f, 0f, 42.5f, 17.5f)
                reflectiveQuadTo(880f, 140f)
                verticalLineToRelative(120f)
                quadToRelative(0f, 25f, -17.5f, 42.5f)
                reflectiveQuadTo(820f, 320f)
                horizontalLineTo(700f)
                close()
                moveToRelative(80f, -120f)
                horizontalLineToRelative(40f)
                quadToRelative(8f, 0f, 14f, -6f)
                reflectiveQuadToRelative(6f, -14f)
                verticalLineToRelative(-40f)
                quadToRelative(0f, -8f, -6f, -14f)
                reflectiveQuadToRelative(-14f, -6f)
                horizontalLineToRelative(-40f)
                quadToRelative(-8f, 0f, -14f, 6f)
                reflectiveQuadToRelative(-6f, 14f)
                verticalLineToRelative(40f)
                quadToRelative(0f, 8f, 6f, 14f)
                reflectiveQuadToRelative(14f, 6f)
                close()
                moveTo(376f, 782f)
                quadToRelative(-18f, -34f, -31.5f, -69.5f)
                reflectiveQuadTo(322f, 640f)
                horizontalLineTo(204f)
                quadToRelative(29f, 51f, 73f, 87.5f)
                reflectiveQuadToRelative(99f, 54.5f)
                close()
                moveToRelative(104f, 16f)
                quadToRelative(26f, -36f, 45f, -75.5f)
                reflectiveQuadToRelative(31f, -82.5f)
                horizontalLineTo(404f)
                quadToRelative(12f, 43f, 31f, 82.5f)
                reflectiveQuadToRelative(45f, 75.5f)
                close()
                moveToRelative(104f, -16f)
                quadToRelative(55f, -18f, 99f, -54.5f)
                reflectiveQuadToRelative(73f, -87.5f)
                horizontalLineTo(638f)
                quadToRelative(-9f, 37f, -22.5f, 72.5f)
                reflectiveQuadTo(584f, 782f)
                close()
            }
        }.build()
        
        return _Bring_your_own_ip!!
    }

private var _Bring_your_own_ip: ImageVector? = null

