package com.composables.icons.materialsymbols.roundedfilled

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.RoundedFilled.Engineering: ImageVector
    get() {
        if (_Engineering != null) return _Engineering!!
        
        _Engineering = ImageVector.Builder(
            name = "engineering",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(42f, 800f)
                verticalLineToRelative(-72f)
                quadToRelative(0f, -33f, 17f, -62f)
                reflectiveQuadToRelative(47f, -44f)
                quadToRelative(51f, -26f, 115f, -44f)
                reflectiveQuadToRelative(141f, -18f)
                quadToRelative(77f, 0f, 141f, 18f)
                reflectiveQuadToRelative(115f, 44f)
                quadToRelative(30f, 15f, 47f, 44f)
                reflectiveQuadToRelative(17f, 62f)
                verticalLineToRelative(72f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(642f, 840f)
                horizontalLineTo(82f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(42f, 800f)
                close()
                moveToRelative(320f, -280f)
                quadToRelative(-66f, 0f, -113f, -47f)
                reflectiveQuadToRelative(-47f, -113f)
                horizontalLineToRelative(-10f)
                quadToRelative(-9f, 0f, -14.5f, -5.5f)
                reflectiveQuadTo(172f, 340f)
                quadToRelative(0f, -9f, 5.5f, -14.5f)
                reflectiveQuadTo(192f, 320f)
                horizontalLineToRelative(10f)
                quadToRelative(0f, -45f, 22f, -81f)
                reflectiveQuadToRelative(58f, -57f)
                verticalLineToRelative(38f)
                quadToRelative(0f, 9f, 5.5f, 14.5f)
                reflectiveQuadTo(302f, 240f)
                quadToRelative(9f, 0f, 14.5f, -5.5f)
                reflectiveQuadTo(322f, 220f)
                verticalLineToRelative(-54f)
                quadToRelative(9f, -3f, 19f, -4.5f)
                reflectiveQuadToRelative(21f, -1.5f)
                quadToRelative(11f, 0f, 21f, 1.5f)
                reflectiveQuadToRelative(19f, 4.5f)
                verticalLineToRelative(54f)
                quadToRelative(0f, 9f, 5.5f, 14.5f)
                reflectiveQuadTo(422f, 240f)
                quadToRelative(9f, 0f, 14.5f, -5.5f)
                reflectiveQuadTo(442f, 220f)
                verticalLineToRelative(-38f)
                quadToRelative(36f, 21f, 58f, 57f)
                reflectiveQuadToRelative(22f, 81f)
                horizontalLineToRelative(10f)
                quadToRelative(9f, 0f, 14.5f, 5.5f)
                reflectiveQuadTo(552f, 340f)
                quadToRelative(0f, 9f, -5.5f, 14.5f)
                reflectiveQuadTo(532f, 360f)
                horizontalLineToRelative(-10f)
                quadToRelative(0f, 66f, -47f, 113f)
                reflectiveQuadToRelative(-113f, 47f)
                close()
                moveToRelative(0f, -80f)
                quadToRelative(33f, 0f, 56.5f, -23.5f)
                reflectiveQuadTo(442f, 360f)
                horizontalLineTo(282f)
                quadToRelative(0f, 33f, 23.5f, 56.5f)
                reflectiveQuadTo(362f, 440f)
                close()
                moveToRelative(297f, 144f)
                lineToRelative(-3f, -14f)
                quadToRelative(-6f, -2f, -11.5f, -4.5f)
                reflectiveQuadTo(634f, 558f)
                lineToRelative(-12f, 4f)
                quadToRelative(-7f, 2f, -13.5f, 0f)
                reflectiveQuadToRelative(-10.5f, -9f)
                lineToRelative(-4f, -7f)
                quadToRelative(-4f, -6f, -2.5f, -13f)
                reflectiveQuadToRelative(6.5f, -12f)
                lineToRelative(10f, -9f)
                verticalLineToRelative(-24f)
                lineToRelative(-10f, -9f)
                quadToRelative(-5f, -5f, -6.5f, -12f)
                reflectiveQuadToRelative(2.5f, -13f)
                lineToRelative(4f, -7f)
                quadToRelative(4f, -7f, 10.5f, -9f)
                reflectiveQuadToRelative(13.5f, 0f)
                lineToRelative(12f, 4f)
                quadToRelative(4f, -4f, 10f, -7f)
                reflectiveQuadToRelative(12f, -5f)
                lineToRelative(3f, -14f)
                quadToRelative(2f, -7f, 7f, -11.5f)
                reflectiveQuadToRelative(12f, -4.5f)
                horizontalLineToRelative(8f)
                quadToRelative(7f, 0f, 12f, 4.5f)
                reflectiveQuadToRelative(7f, 11.5f)
                lineToRelative(3f, 14f)
                quadToRelative(6f, 2f, 12f, 5f)
                reflectiveQuadToRelative(10f, 7f)
                lineToRelative(12f, -4f)
                quadToRelative(7f, -2f, 13.5f, 0f)
                reflectiveQuadToRelative(10.5f, 9f)
                lineToRelative(4f, 7f)
                quadToRelative(4f, 6f, 2.5f, 13f)
                reflectiveQuadToRelative(-6.5f, 12f)
                lineToRelative(-10f, 9f)
                verticalLineToRelative(24f)
                lineToRelative(10f, 9f)
                quadToRelative(5f, 5f, 6.5f, 12f)
                reflectiveQuadToRelative(-2.5f, 13f)
                lineToRelative(-4f, 7f)
                quadToRelative(-4f, 7f, -10.5f, 9f)
                reflectiveQuadToRelative(-13.5f, 0f)
                lineToRelative(-12f, -4f)
                quadToRelative(-5f, 5f, -10.5f, 7.5f)
                reflectiveQuadTo(708f, 570f)
                lineToRelative(-3f, 14f)
                quadToRelative(-2f, 7f, -7f, 11.5f)
                reflectiveQuadToRelative(-12f, 4.5f)
                horizontalLineToRelative(-8f)
                quadToRelative(-7f, 0f, -12f, -4.5f)
                reflectiveQuadToRelative(-7f, -11.5f)
                close()
                moveToRelative(23f, -54f)
                quadToRelative(12f, 0f, 21f, -9f)
                reflectiveQuadToRelative(9f, -21f)
                quadToRelative(0f, -12f, -9f, -21f)
                reflectiveQuadToRelative(-21f, -9f)
                quadToRelative(-12f, 0f, -21f, 9f)
                reflectiveQuadToRelative(-9f, 21f)
                quadToRelative(0f, 12f, 9f, 21f)
                reflectiveQuadToRelative(21f, 9f)
                close()
                moveToRelative(68f, -152f)
                lineToRelative(-4f, -20f)
                quadToRelative(-9f, -3f, -16.5f, -7.5f)
                reflectiveQuadTo(716f, 340f)
                lineToRelative(-21f, 7f)
                quadToRelative(-9f, 3f, -18f, -0.5f)
                reflectiveQuadTo(663f, 335f)
                lineToRelative(-6f, -10f)
                quadToRelative(-5f, -8f, -3.5f, -17.5f)
                reflectiveQuadTo(663f, 291f)
                lineToRelative(17f, -15f)
                quadToRelative(-2f, -5f, -2f, -8f)
                verticalLineToRelative(-16f)
                quadToRelative(0f, -3f, 2f, -8f)
                lineToRelative(-17f, -15f)
                quadToRelative(-8f, -7f, -9.5f, -16.5f)
                reflectiveQuadTo(657f, 195f)
                lineToRelative(6f, -10f)
                quadToRelative(5f, -8f, 14f, -11.5f)
                reflectiveQuadToRelative(18f, -0.5f)
                lineToRelative(21f, 7f)
                quadToRelative(6f, -6f, 13.5f, -10.5f)
                reflectiveQuadTo(746f, 162f)
                lineToRelative(4f, -20f)
                quadToRelative(2f, -10f, 9.5f, -16f)
                reflectiveQuadToRelative(17.5f, -6f)
                horizontalLineToRelative(10f)
                quadToRelative(10f, 0f, 17.5f, 6f)
                reflectiveQuadToRelative(9.5f, 16f)
                lineToRelative(4f, 20f)
                quadToRelative(9f, 3f, 16.5f, 7.5f)
                reflectiveQuadTo(848f, 180f)
                lineToRelative(21f, -7f)
                quadToRelative(9f, -3f, 18f, 0.5f)
                reflectiveQuadToRelative(14f, 11.5f)
                lineToRelative(6f, 10f)
                quadToRelative(5f, 8f, 3.5f, 17.5f)
                reflectiveQuadTo(901f, 229f)
                lineToRelative(-17f, 15f)
                quadToRelative(2f, 5f, 2f, 8f)
                verticalLineToRelative(16f)
                quadToRelative(0f, 3f, -2f, 8f)
                lineToRelative(17f, 15f)
                quadToRelative(8f, 7f, 9.5f, 16.5f)
                reflectiveQuadTo(907f, 325f)
                lineToRelative(-6f, 10f)
                quadToRelative(-5f, 8f, -14f, 11.5f)
                reflectiveQuadToRelative(-18f, 0.5f)
                lineToRelative(-21f, -7f)
                quadToRelative(-6f, 6f, -13.5f, 10.5f)
                reflectiveQuadTo(818f, 358f)
                lineToRelative(-4f, 20f)
                quadToRelative(-2f, 10f, -9.5f, 16f)
                reflectiveQuadToRelative(-17.5f, 6f)
                horizontalLineToRelative(-10f)
                quadToRelative(-10f, 0f, -17.5f, -6f)
                reflectiveQuadToRelative(-9.5f, -16f)
                close()
                moveToRelative(32f, -68f)
                quadToRelative(21f, 0f, 35.5f, -14.5f)
                reflectiveQuadTo(832f, 260f)
                quadToRelative(0f, -21f, -14.5f, -35.5f)
                reflectiveQuadTo(782f, 210f)
                quadToRelative(-21f, 0f, -35.5f, 14.5f)
                reflectiveQuadTo(732f, 260f)
                quadToRelative(0f, 21f, 14.5f, 35.5f)
                reflectiveQuadTo(782f, 310f)
                close()
            }
        }.build()
        
        return _Engineering!!
    }

private var _Engineering: ImageVector? = null

