package com.composables.icons.materialsymbols.roundedfilled

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.RoundedFilled.Hdr_auto_select: ImageVector
    get() {
        if (_Hdr_auto_select != null) return _Hdr_auto_select!!
        
        _Hdr_auto_select = ImageVector.Builder(
            name = "hdr_auto_select",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(438f, 328f)
                lineToRelative(40f, -116f)
                horizontalLineToRelative(4f)
                lineToRelative(40f, 116f)
                horizontalLineToRelative(-84f)
                close()
                moveToRelative(42f, 232f)
                quadToRelative(-100f, 0f, -170f, -70f)
                reflectiveQuadToRelative(-70f, -170f)
                quadToRelative(0f, -100f, 70f, -170f)
                reflectiveQuadToRelative(170f, -70f)
                quadToRelative(100f, 0f, 170f, 70f)
                reflectiveQuadToRelative(70f, 170f)
                quadToRelative(0f, 100f, -70f, 170f)
                reflectiveQuadToRelative(-170f, 70f)
                close()
                moveToRelative(-56f, -192f)
                horizontalLineToRelative(112f)
                lineToRelative(21f, 58f)
                quadToRelative(2f, 7f, 8f, 10.5f)
                reflectiveQuadToRelative(13f, 3.5f)
                quadToRelative(12f, 0f, 18.5f, -9.5f)
                reflectiveQuadTo(598f, 410f)
                lineToRelative(-88f, -235f)
                quadToRelative(-2f, -7f, -8f, -11f)
                reflectiveQuadToRelative(-14f, -4f)
                horizontalLineToRelative(-18f)
                quadToRelative(-8f, 0f, -14f, 4f)
                reflectiveQuadToRelative(-8f, 11f)
                lineToRelative(-87f, 235f)
                quadToRelative(-4f, 11f, 2.5f, 20.5f)
                reflectiveQuadTo(382f, 440f)
                quadToRelative(8f, 0f, 13.5f, -4f)
                reflectiveQuadToRelative(7.5f, -11f)
                lineToRelative(21f, -57f)
                close()
                moveToRelative(396f, 432f)
                horizontalLineToRelative(-50f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(740f, 770f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(770f, 740f)
                horizontalLineToRelative(50f)
                verticalLineToRelative(-50f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(850f, 660f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(880f, 690f)
                verticalLineToRelative(50f)
                horizontalLineToRelative(50f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(960f, 770f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(930f, 800f)
                horizontalLineToRelative(-50f)
                verticalLineToRelative(50f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(850f, 880f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(820f, 850f)
                verticalLineToRelative(-50f)
                close()
                moveToRelative(-300f, 50f)
                verticalLineToRelative(-180f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(550f, 640f)
                horizontalLineToRelative(110f)
                quadToRelative(24f, 0f, 42f, 18f)
                reflectiveQuadToRelative(18f, 42f)
                verticalLineToRelative(40f)
                quadToRelative(0f, 23f, -10.5f, 35.5f)
                reflectiveQuadTo(684f, 796f)
                lineToRelative(20f, 46f)
                quadToRelative(6f, 14f, -2f, 26f)
                reflectiveQuadToRelative(-24f, 12f)
                quadToRelative(-8f, 0f, -15f, -4f)
                reflectiveQuadToRelative(-10f, -12f)
                lineToRelative(-29f, -64f)
                horizontalLineToRelative(-44f)
                verticalLineToRelative(50f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(550f, 880f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(520f, 850f)
                close()
                moveToRelative(60f, -110f)
                horizontalLineToRelative(80f)
                verticalLineToRelative(-40f)
                horizontalLineToRelative(-80f)
                verticalLineToRelative(40f)
                close()
                moveTo(60f, 780f)
                verticalLineToRelative(70f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(30f, 880f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(0f, 850f)
                verticalLineToRelative(-180f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(30f, 640f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(60f, 670f)
                verticalLineToRelative(50f)
                horizontalLineToRelative(80f)
                verticalLineToRelative(-50f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(170f, 640f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(200f, 670f)
                verticalLineToRelative(180f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(170f, 880f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(140f, 850f)
                verticalLineToRelative(-70f)
                horizontalLineTo(60f)
                close()
                moveToRelative(200f, 70f)
                verticalLineToRelative(-180f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(290f, 640f)
                horizontalLineToRelative(110f)
                quadToRelative(24f, 0f, 42f, 18f)
                reflectiveQuadToRelative(18f, 42f)
                verticalLineToRelative(120f)
                quadToRelative(0f, 24f, -18f, 42f)
                reflectiveQuadToRelative(-42f, 18f)
                horizontalLineTo(290f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(260f, 850f)
                close()
                moveToRelative(60f, -30f)
                horizontalLineToRelative(80f)
                verticalLineToRelative(-120f)
                horizontalLineToRelative(-80f)
                verticalLineToRelative(120f)
                close()
            }
        }.build()
        
        return _Hdr_auto_select!!
    }

private var _Hdr_auto_select: ImageVector? = null

