package com.composables.icons.materialsymbols.roundedfilled

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.RoundedFilled.Hvac_max_defrost: ImageVector
    get() {
        if (_Hvac_max_defrost != null) return _Hvac_max_defrost!!
        
        _Hvac_max_defrost = ImageVector.Builder(
            name = "hvac_max_defrost",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(236f, 880f)
                quadToRelative(-5f, 0f, -8f, -2.5f)
                reflectiveQuadToRelative(-5f, -6.5f)
                lineToRelative(-65f, -169f)
                horizontalLineToRelative(-2f)
                lineToRelative(2f, 44f)
                verticalLineToRelative(115f)
                quadToRelative(0f, 8f, -5.5f, 13.5f)
                reflectiveQuadTo(139f, 880f)
                quadToRelative(-8f, 0f, -13.5f, -5.5f)
                reflectiveQuadTo(120f, 861f)
                verticalLineToRelative(-197f)
                quadToRelative(0f, -10f, 7f, -17f)
                reflectiveQuadToRelative(17f, -7f)
                horizontalLineToRelative(11f)
                quadToRelative(8f, 0f, 13.5f, 4f)
                reflectiveQuadToRelative(8.5f, 11f)
                lineToRelative(63f, 167f)
                horizontalLineToRelative(2f)
                lineToRelative(63f, -166f)
                quadToRelative(3f, -8f, 9.5f, -12f)
                reflectiveQuadToRelative(14.5f, -4f)
                horizontalLineToRelative(8f)
                quadToRelative(11f, 0f, 18f, 7f)
                reflectiveQuadToRelative(7f, 18f)
                verticalLineToRelative(196f)
                quadToRelative(0f, 8f, -5f, 13.5f)
                reflectiveQuadTo(344f, 880f)
                quadToRelative(-8f, 0f, -13.5f, -5.5f)
                reflectiveQuadTo(325f, 861f)
                verticalLineToRelative(-115f)
                lineToRelative(2f, -44f)
                horizontalLineToRelative(-2f)
                lineTo(260f, 871f)
                quadToRelative(-2f, 4f, -5f, 6.5f)
                reflectiveQuadToRelative(-8f, 2.5f)
                horizontalLineToRelative(-11f)
                close()
                moveToRelative(221f, -61f)
                lineToRelative(-17f, 49f)
                quadToRelative(-2f, 5f, -6.5f, 8.5f)
                reflectiveQuadTo(423f, 880f)
                quadToRelative(-10f, 0f, -16f, -8.5f)
                reflectiveQuadToRelative(-2f, -17.5f)
                lineToRelative(75f, -201f)
                quadToRelative(2f, -6f, 7.5f, -9.5f)
                reflectiveQuadTo(499f, 640f)
                horizontalLineToRelative(15f)
                quadToRelative(6f, 0f, 11.5f, 3.5f)
                reflectiveQuadToRelative(7.5f, 9.5f)
                lineToRelative(75f, 201f)
                quadToRelative(4f, 10f, -1.5f, 18f)
                reflectiveQuadTo(590f, 880f)
                quadToRelative(-7f, 0f, -12f, -3.5f)
                reflectiveQuadToRelative(-7f, -9.5f)
                lineToRelative(-17f, -48f)
                horizontalLineToRelative(-97f)
                close()
                moveToRelative(277f, -32f)
                lineToRelative(-53f, 84f)
                quadToRelative(-2f, 4f, -6.5f, 6.5f)
                reflectiveQuadTo(665f, 880f)
                quadToRelative(-11f, 0f, -17f, -10f)
                reflectiveQuadToRelative(0f, -20f)
                lineToRelative(61f, -95f)
                lineToRelative(-55f, -86f)
                quadToRelative(-6f, -10f, -0.5f, -19.5f)
                reflectiveQuadTo(670f, 640f)
                quadToRelative(5f, 0f, 9f, 2f)
                reflectiveQuadToRelative(7f, 7f)
                lineToRelative(48f, 77f)
                horizontalLineToRelative(2f)
                lineToRelative(47f, -77f)
                quadToRelative(2f, -4f, 6.5f, -6.5f)
                reflectiveQuadToRelative(9.5f, -2.5f)
                quadToRelative(11f, 0f, 16.5f, 10f)
                reflectiveQuadToRelative(-0.5f, 20f)
                lineToRelative(-55f, 85f)
                lineToRelative(61f, 96f)
                quadToRelative(6f, 10f, 0.5f, 19.5f)
                reflectiveQuadTo(805f, 880f)
                quadToRelative(-5f, 0f, -9.5f, -2f)
                reflectiveQuadToRelative(-7.5f, -7f)
                lineToRelative(-52f, -84f)
                horizontalLineToRelative(-2f)
                close()
                moveToRelative(-264f, -3f)
                horizontalLineToRelative(71f)
                lineToRelative(-34f, -100f)
                horizontalLineToRelative(-2f)
                lineToRelative(-35f, 100f)
                close()
                moveTo(145f, 520f)
                quadToRelative(-17f, 3f, -30.5f, -6f)
                reflectiveQuadTo(98f, 488f)
                lineTo(42f, 188f)
                quadToRelative(-3f, -17f, 6.5f, -31.5f)
                reflectiveQuadTo(75f, 137f)
                quadToRelative(115f, -29f, 214.5f, -43f)
                reflectiveQuadTo(480f, 80f)
                quadToRelative(91f, 0f, 190.5f, 14f)
                reflectiveQuadTo(885f, 137f)
                quadToRelative(17f, 5f, 26.5f, 19.5f)
                reflectiveQuadTo(918f, 188f)
                lineToRelative(-56f, 300f)
                quadToRelative(-3f, 17f, -16.5f, 26f)
                reflectiveQuadToRelative(-30.5f, 6f)
                quadToRelative(-17f, -3f, -26f, -16f)
                reflectiveQuadToRelative(-6f, -30f)
                lineToRelative(51f, -268f)
                quadToRelative(-104f, -24f, -190f, -35f)
                reflectiveQuadToRelative(-164f, -11f)
                quadToRelative(-78f, 0f, -164f, 11f)
                reflectiveQuadToRelative(-190f, 35f)
                lineToRelative(51f, 268f)
                quadToRelative(3f, 17f, -6f, 30f)
                reflectiveQuadToRelative(-26f, 16f)
                close()
                moveToRelative(495f, -42f)
                quadToRelative(0f, -14f, -5f, -27f)
                reflectiveQuadToRelative(-15f, -23f)
                quadToRelative(-21f, -21f, -32.5f, -48.5f)
                reflectiveQuadTo(576f, 322f)
                quadToRelative(0f, -23f, 6.5f, -44f)
                reflectiveQuadToRelative(18.5f, -40f)
                lineToRelative(13f, -20f)
                quadToRelative(9f, -14f, 25.5f, -17f)
                reflectiveQuadToRelative(30.5f, 6f)
                quadToRelative(14f, 9f, 17f, 25f)
                reflectiveQuadToRelative(-6f, 30f)
                lineToRelative(-14f, 21f)
                quadToRelative(-6f, 9f, -8.5f, 18.5f)
                reflectiveQuadTo(656f, 322f)
                quadToRelative(0f, 14f, 5f, 27f)
                reflectiveQuadToRelative(15f, 23f)
                quadToRelative(21f, 21f, 32.5f, 48.5f)
                reflectiveQuadTo(720f, 478f)
                quadToRelative(0f, 23f, -6.5f, 44f)
                reflectiveQuadTo(695f, 562f)
                lineToRelative(-14f, 20f)
                quadToRelative(-9f, 14f, -25f, 17f)
                reflectiveQuadToRelative(-30f, -6f)
                quadToRelative(-14f, -9f, -17f, -25f)
                reflectiveQuadToRelative(6f, -30f)
                lineToRelative(13f, -21f)
                quadToRelative(6f, -9f, 9f, -18.5f)
                reflectiveQuadToRelative(3f, -20.5f)
                close()
                moveToRelative(-168f, 0f)
                quadToRelative(0f, -14f, -5f, -27f)
                reflectiveQuadToRelative(-15f, -23f)
                quadToRelative(-21f, -21f, -32.5f, -48.5f)
                reflectiveQuadTo(408f, 322f)
                quadToRelative(0f, -23f, 6.5f, -44f)
                reflectiveQuadToRelative(18.5f, -40f)
                lineToRelative(13f, -20f)
                quadToRelative(9f, -14f, 25.5f, -17f)
                reflectiveQuadToRelative(30.5f, 6f)
                quadToRelative(14f, 9f, 17f, 25f)
                reflectiveQuadToRelative(-6f, 30f)
                lineToRelative(-14f, 21f)
                quadToRelative(-6f, 9f, -8.5f, 18.5f)
                reflectiveQuadTo(488f, 322f)
                quadToRelative(0f, 14f, 5f, 27f)
                reflectiveQuadToRelative(15f, 23f)
                quadToRelative(21f, 21f, 32.5f, 48.5f)
                reflectiveQuadTo(552f, 478f)
                quadToRelative(0f, 23f, -6.5f, 44f)
                reflectiveQuadTo(527f, 562f)
                lineToRelative(-14f, 20f)
                quadToRelative(-9f, 14f, -25f, 17f)
                reflectiveQuadToRelative(-30f, -6f)
                quadToRelative(-14f, -9f, -17f, -25f)
                reflectiveQuadToRelative(6f, -30f)
                lineToRelative(13f, -21f)
                quadToRelative(6f, -9f, 9f, -18.5f)
                reflectiveQuadToRelative(3f, -20.5f)
                close()
                moveToRelative(-167f, 0f)
                quadToRelative(0f, -14f, -5.5f, -27f)
                reflectiveQuadTo(284f, 428f)
                quadToRelative(-21f, -21f, -32.5f, -48.5f)
                reflectiveQuadTo(240f, 322f)
                quadToRelative(0f, -23f, 6f, -44f)
                reflectiveQuadToRelative(19f, -40f)
                lineToRelative(14f, -20f)
                quadToRelative(9f, -14f, 25.5f, -17f)
                reflectiveQuadToRelative(30.5f, 6f)
                quadToRelative(14f, 9f, 17f, 25f)
                reflectiveQuadToRelative(-6f, 30f)
                lineToRelative(-14f, 21f)
                quadToRelative(-6f, 8f, -9f, 18f)
                reflectiveQuadToRelative(-3f, 21f)
                quadToRelative(0f, 14f, 5f, 27f)
                reflectiveQuadToRelative(15f, 23f)
                quadToRelative(21f, 21f, 32.5f, 48.5f)
                reflectiveQuadTo(384f, 478f)
                quadToRelative(0f, 23f, -6.5f, 44f)
                reflectiveQuadTo(359f, 562f)
                lineToRelative(-13f, 20f)
                quadToRelative(-9f, 14f, -25.5f, 17f)
                reflectiveQuadToRelative(-30.5f, -6f)
                quadToRelative(-14f, -9f, -17f, -25f)
                reflectiveQuadToRelative(6f, -30f)
                lineToRelative(14f, -21f)
                quadToRelative(6f, -9f, 9f, -18.5f)
                reflectiveQuadToRelative(3f, -20.5f)
                close()
            }
        }.build()
        
        return _Hvac_max_defrost!!
    }

private var _Hvac_max_defrost: ImageVector? = null

