package com.composables.icons.materialsymbols.roundedfilled

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.RoundedFilled.Language_chinese_cangjie: ImageVector
    get() {
        if (_Language_chinese_cangjie != null) return _Language_chinese_cangjie!!
        
        _Language_chinese_cangjie = ImageVector.Builder(
            name = "language_chinese_cangjie",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(197f, 553f)
                quadToRelative(-7f, 39f, -21.5f, 76.5f)
                reflectiveQuadTo(133f, 694f)
                quadToRelative(-8f, 8f, -18.5f, 7.5f)
                reflectiveQuadTo(96f, 694f)
                quadToRelative(-8f, -7f, -7.5f, -17f)
                reflectiveQuadToRelative(7.5f, -18f)
                quadToRelative(30f, -38f, 44.5f, -83.5f)
                reflectiveQuadTo(155f, 482f)
                verticalLineToRelative(-56f)
                quadToRelative(0f, -8f, 6f, -14f)
                reflectiveQuadToRelative(14f, -6f)
                horizontalLineToRelative(265f)
                quadToRelative(8f, 0f, 14f, 6f)
                reflectiveQuadToRelative(6f, 14f)
                verticalLineToRelative(107f)
                quadToRelative(0f, 8f, -6f, 14f)
                reflectiveQuadToRelative(-14f, 6f)
                horizontalLineTo(197f)
                close()
                moveToRelative(5f, -36f)
                horizontalLineToRelative(211f)
                verticalLineToRelative(-75f)
                horizontalLineTo(202f)
                verticalLineToRelative(75f)
                close()
                moveToRelative(104f, -222f)
                quadToRelative(-38f, 43f, -85f, 76.5f)
                reflectiveQuadTo(121f, 429f)
                quadToRelative(-10f, 5f, -20.5f, 2f)
                reflectiveQuadTo(84f, 420f)
                quadToRelative(-5f, -8f, -1.5f, -16f)
                reflectiveQuadTo(95f, 391f)
                quadToRelative(50f, -24f, 94f, -56f)
                reflectiveQuadToRelative(82f, -73f)
                quadToRelative(6f, -7f, 15f, -9.5f)
                reflectiveQuadToRelative(18f, -2.5f)
                quadToRelative(9f, 0f, 18f, 2.5f)
                reflectiveQuadToRelative(16f, 9.5f)
                quadToRelative(40f, 38f, 86.5f, 67f)
                reflectiveQuadToRelative(95.5f, 54f)
                quadToRelative(10f, 5f, 14f, 15f)
                reflectiveQuadToRelative(-2f, 18f)
                quadToRelative(-7f, 9f, -18f, 10.5f)
                reflectiveQuadToRelative(-22f, -3.5f)
                quadToRelative(-51f, -26f, -98.5f, -57f)
                reflectiveQuadTo(306f, 295f)
                close()
                moveToRelative(-89f, 415f)
                quadToRelative(-9f, 0f, -15.5f, -6.5f)
                reflectiveQuadTo(195f, 688f)
                verticalLineToRelative(-98f)
                quadToRelative(0f, -8f, 6f, -14f)
                reflectiveQuadToRelative(14f, -6f)
                horizontalLineToRelative(240f)
                quadToRelative(8f, 0f, 14f, 6f)
                reflectiveQuadToRelative(6f, 14f)
                verticalLineToRelative(98f)
                quadToRelative(0f, 9f, -6.5f, 15.5f)
                reflectiveQuadTo(453f, 710f)
                quadToRelative(-9f, 0f, -15.5f, -6.5f)
                reflectiveQuadTo(431f, 688f)
                verticalLineToRelative(-79f)
                horizontalLineTo(239f)
                verticalLineToRelative(79f)
                quadToRelative(0f, 9f, -6.5f, 15.5f)
                reflectiveQuadTo(217f, 710f)
                close()
                moveToRelative(167f, -323f)
                horizontalLineTo(231f)
                quadToRelative(-8f, 0f, -13f, -5f)
                reflectiveQuadToRelative(-5f, -13f)
                quadToRelative(0f, -8f, 5f, -13f)
                reflectiveQuadToRelative(13f, -5f)
                horizontalLineToRelative(153f)
                quadToRelative(8f, 0f, 13f, 5f)
                reflectiveQuadToRelative(5f, 13f)
                quadToRelative(0f, 8f, -5f, 13f)
                reflectiveQuadToRelative(-13f, 5f)
                close()
                moveTo(176f, 496f)
                verticalLineToRelative(-34f)
                horizontalLineToRelative(267f)
                verticalLineToRelative(34f)
                horizontalLineTo(176f)
                close()
                moveToRelative(33f, 199f)
                verticalLineToRelative(-38f)
                horizontalLineToRelative(242f)
                verticalLineToRelative(38f)
                horizontalLineTo(209f)
                close()
                moveToRelative(493f, -69f)
                quadToRelative(28f, 0f, 54.5f, -13f)
                reflectiveQuadToRelative(48.5f, -37f)
                verticalLineToRelative(-106f)
                quadToRelative(-23f, 3f, -42.5f, 7f)
                reflectiveQuadToRelative(-36.5f, 9f)
                quadToRelative(-45f, 14f, -67.5f, 35f)
                reflectiveQuadTo(636f, 570f)
                quadToRelative(0f, 26f, 18f, 41f)
                reflectiveQuadToRelative(48f, 15f)
                close()
                moveToRelative(-23f, 68f)
                quadToRelative(-57f, 0f, -90f, -32.5f)
                reflectiveQuadTo(556f, 573f)
                quadToRelative(0f, -52f, 33f, -85f)
                reflectiveQuadToRelative(106f, -53f)
                quadToRelative(23f, -6f, 50.5f, -11f)
                reflectiveQuadToRelative(59.5f, -9f)
                quadToRelative(-2f, -47f, -22f, -68.5f)
                reflectiveQuadTo(721f, 325f)
                quadToRelative(-21f, 0f, -41f, 6f)
                reflectiveQuadToRelative(-47f, 20f)
                quadToRelative(-12f, 7f, -25f, 4f)
                reflectiveQuadToRelative(-20f, -15f)
                quadToRelative(-7f, -12f, -3f, -25.5f)
                reflectiveQuadToRelative(16f, -20.5f)
                quadToRelative(31f, -17f, 66.5f, -27.5f)
                reflectiveQuadTo(740f, 256f)
                quadToRelative(71f, 0f, 108f, 44f)
                reflectiveQuadToRelative(37f, 128f)
                verticalLineToRelative(224f)
                quadToRelative(0f, 14f, -9.5f, 23.5f)
                reflectiveQuadTo(852f, 685f)
                horizontalLineToRelative(-5f)
                quadToRelative(-13f, 0f, -22f, -8.5f)
                reflectiveQuadTo(814f, 656f)
                lineToRelative(-2f, -16f)
                quadToRelative(-28f, 25f, -61.5f, 39.5f)
                reflectiveQuadTo(679f, 694f)
                close()
            }
        }.build()
        
        return _Language_chinese_cangjie!!
    }

private var _Language_chinese_cangjie: ImageVector? = null

