package com.composables.icons.materialsymbols.roundedfilled

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.RoundedFilled.Letter_switch: ImageVector
    get() {
        if (_Letter_switch != null) return _Letter_switch!!
        
        _Letter_switch = ImageVector.Builder(
            name = "letter_switch",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(640f, 880f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(600f, 840f)
                verticalLineToRelative(-160f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(640f, 640f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(680f, 680f)
                verticalLineToRelative(71f)
                quadToRelative(42f, -60f, 61f, -129.5f)
                reflectiveQuadTo(760f, 480f)
                quadToRelative(0f, -72f, -19f, -141.5f)
                reflectiveQuadTo(680f, 209f)
                verticalLineToRelative(71f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(640f, 320f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(600f, 280f)
                verticalLineToRelative(-160f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(640f, 80f)
                horizontalLineToRelative(160f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(840f, 120f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(800f, 160f)
                horizontalLineToRelative(-57f)
                quadToRelative(50f, 70f, 73.5f, 152f)
                reflectiveQuadTo(840f, 480f)
                quadToRelative(0f, 86f, -23.5f, 168f)
                reflectiveQuadTo(743f, 800f)
                horizontalLineToRelative(57f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(840f, 840f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(800f, 880f)
                horizontalLineTo(640f)
                close()
                moveTo(236f, 726f)
                horizontalLineToRelative(70f)
                verticalLineToRelative(-48f)
                horizontalLineToRelative(-70f)
                verticalLineToRelative(48f)
                close()
                moveToRelative(118f, 0f)
                horizontalLineToRelative(70f)
                verticalLineToRelative(-48f)
                horizontalLineToRelative(-70f)
                verticalLineToRelative(48f)
                close()
                moveToRelative(-96f, -108f)
                quadToRelative(-9f, 0f, -15.5f, -6.5f)
                reflectiveQuadTo(236f, 596f)
                verticalLineToRelative(-13f)
                horizontalLineToRelative(-57f)
                quadToRelative(-9f, 0f, -15.5f, -6.5f)
                reflectiveQuadTo(157f, 561f)
                quadToRelative(0f, -9f, 6.5f, -15.5f)
                reflectiveQuadTo(179f, 539f)
                horizontalLineToRelative(57f)
                verticalLineToRelative(-9f)
                quadToRelative(0f, -9f, 6.5f, -15f)
                reflectiveQuadToRelative(15.5f, -6f)
                quadToRelative(9f, 0f, 15f, 6f)
                reflectiveQuadToRelative(6f, 15f)
                verticalLineToRelative(9f)
                horizontalLineToRelative(101f)
                verticalLineToRelative(-9f)
                quadToRelative(0f, -9f, 6.5f, -15f)
                reflectiveQuadToRelative(15.5f, -6f)
                quadToRelative(9f, 0f, 15f, 6f)
                reflectiveQuadToRelative(6f, 15f)
                verticalLineToRelative(9f)
                horizontalLineToRelative(57f)
                quadToRelative(9f, 0f, 15.5f, 6.5f)
                reflectiveQuadTo(502f, 561f)
                quadToRelative(0f, 9f, -6.5f, 15.5f)
                reflectiveQuadTo(480f, 583f)
                horizontalLineToRelative(-57f)
                verticalLineToRelative(14f)
                quadToRelative(0f, 9f, -6f, 15f)
                reflectiveQuadToRelative(-15f, 6f)
                quadToRelative(-9f, 0f, -15.5f, -6.5f)
                reflectiveQuadTo(380f, 596f)
                verticalLineToRelative(-13f)
                horizontalLineTo(279f)
                verticalLineToRelative(14f)
                quadToRelative(0f, 9f, -6f, 15f)
                reflectiveQuadToRelative(-15f, 6f)
                close()
                moveToRelative(74f, 174f)
                quadToRelative(-21f, 34f, -56f, 52f)
                reflectiveQuadToRelative(-74f, 29f)
                quadToRelative(-12f, 3f, -24f, -0.5f)
                reflectiveQuadTo(159f, 858f)
                quadToRelative(-5f, -8f, -1f, -16.5f)
                reflectiveQuadToRelative(14f, -10.5f)
                quadToRelative(35f, -6f, 66f, -19f)
                reflectiveQuadToRelative(50f, -42f)
                horizontalLineTo(173f)
                quadToRelative(-9f, 0f, -15f, -6.5f)
                reflectiveQuadToRelative(-6f, -15.5f)
                quadToRelative(0f, -9f, 6.5f, -15f)
                reflectiveQuadToRelative(15.5f, -6f)
                horizontalLineToRelative(18f)
                verticalLineToRelative(-72f)
                quadToRelative(0f, -8f, 6f, -14f)
                reflectiveQuadToRelative(14f, -6f)
                horizontalLineToRelative(93f)
                verticalLineToRelative(-15f)
                quadToRelative(0f, -10f, 7f, -17f)
                reflectiveQuadToRelative(17f, -7f)
                quadToRelative(10f, 0f, 17f, 7f)
                reflectiveQuadToRelative(7f, 17f)
                verticalLineToRelative(15f)
                horizontalLineToRelative(98f)
                quadToRelative(8f, 0f, 14f, 6f)
                reflectiveQuadToRelative(6f, 14f)
                verticalLineToRelative(72f)
                horizontalLineToRelative(14f)
                quadToRelative(9f, 0f, 15f, 6f)
                reflectiveQuadToRelative(6f, 15f)
                quadToRelative(0f, 9f, -6f, 15.5f)
                reflectiveQuadToRelative(-15f, 6.5f)
                horizontalLineTo(370f)
                quadToRelative(24f, 24f, 53.5f, 39.5f)
                reflectiveQuadTo(487f, 832f)
                quadToRelative(10f, 2f, 15f, 10f)
                reflectiveQuadToRelative(0f, 16f)
                quadToRelative(-6f, 11f, -17.5f, 16f)
                reflectiveQuadTo(461f, 876f)
                quadToRelative(-38f, -9f, -71.5f, -30.5f)
                reflectiveQuadTo(332f, 792f)
                close()
                moveToRelative(-14f, -371f)
                lineToRelative(-32f, -6f)
                quadToRelative(-8f, -2f, -12.5f, -7.5f)
                reflectiveQuadTo(267f, 392f)
                quadToRelative(-2f, -11f, 5f, -19.5f)
                reflectiveQuadToRelative(18f, -8.5f)
                horizontalLineToRelative(20f)
                quadToRelative(9f, 0f, 18f, -2.5f)
                reflectiveQuadToRelative(12f, -10.5f)
                quadToRelative(9f, -26f, 11.5f, -53.5f)
                reflectiveQuadTo(353f, 242f)
                quadToRelative(0f, -14f, -10.5f, -24.5f)
                reflectiveQuadTo(318f, 207f)
                horizontalLineToRelative(-26f)
                quadToRelative(-11f, 48f, -28.5f, 93.5f)
                reflectiveQuadTo(223f, 390f)
                quadToRelative(-6f, 11f, -16.5f, 15.5f)
                reflectiveQuadTo(185f, 405f)
                quadToRelative(-10f, -5f, -12f, -15.5f)
                reflectiveQuadToRelative(4f, -20.5f)
                quadToRelative(22f, -36f, 38f, -74.5f)
                reflectiveQuadToRelative(25f, -79.5f)
                horizontalLineToRelative(-53f)
                quadToRelative(-11f, 0f, -18.5f, -7.5f)
                reflectiveQuadTo(161f, 189f)
                quadToRelative(0f, -11f, 7.5f, -18.5f)
                reflectiveQuadTo(187f, 163f)
                horizontalLineToRelative(65f)
                quadToRelative(2f, -14f, 3.5f, -27f)
                reflectiveQuadToRelative(3.5f, -27f)
                quadToRelative(1f, -11f, 10f, -17f)
                reflectiveQuadToRelative(19f, -3f)
                quadToRelative(12f, 4f, 18.5f, 14.5f)
                reflectiveQuadTo(311f, 126f)
                quadToRelative(-2f, 11f, -4.5f, 21f)
                reflectiveQuadToRelative(-5.5f, 20f)
                horizontalLineToRelative(31f)
                quadToRelative(29f, 0f, 49f, 22.5f)
                reflectiveQuadToRelative(21f, 52.5f)
                quadToRelative(1f, 36f, -4.5f, 71f)
                reflectiveQuadTo(380f, 382f)
                quadToRelative(-3f, 9f, -9.5f, 17f)
                reflectiveQuadTo(356f, 412f)
                quadToRelative(-8f, 5f, -18f, 8f)
                reflectiveQuadToRelative(-20f, 1f)
                close()
                moveToRelative(176f, -134f)
                quadToRelative(-11f, 5f, -20.5f, -1f)
                reflectiveQuadTo(460f, 269f)
                quadToRelative(-8f, -24f, -18f, -47f)
                reflectiveQuadToRelative(-24f, -44f)
                quadToRelative(-6f, -9f, -4f, -19.5f)
                reflectiveQuadToRelative(12f, -15.5f)
                quadToRelative(11f, -5f, 22f, -1.5f)
                reflectiveQuadToRelative(17f, 14.5f)
                quadToRelative(13f, 22f, 23.5f, 45.5f)
                reflectiveQuadTo(509f, 248f)
                quadToRelative(5f, 11f, 0.5f, 22.5f)
                reflectiveQuadTo(494f, 287f)
                close()
            }
        }.build()
        
        return _Letter_switch!!
    }

private var _Letter_switch: ImageVector? = null

