package com.composables.icons.materialsymbols.roundedfilled

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.RoundedFilled.Reduce_capacity: ImageVector
    get() {
        if (_Reduce_capacity != null) return _Reduce_capacity!!
        
        _Reduce_capacity = ImageVector.Builder(
            name = "reduce_capacity",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(120f, 880f)
                verticalLineToRelative(-23f)
                quadToRelative(0f, -24f, 13f, -44f)
                reflectiveQuadToRelative(36f, -30f)
                quadToRelative(26f, -11f, 53.5f, -17f)
                reflectiveQuadToRelative(57.5f, -6f)
                quadToRelative(30f, 0f, 57.5f, 6f)
                reflectiveQuadToRelative(53.5f, 17f)
                quadToRelative(23f, 10f, 36f, 30f)
                reflectiveQuadToRelative(13f, 44f)
                verticalLineToRelative(23f)
                horizontalLineTo(120f)
                close()
                moveToRelative(400f, 0f)
                verticalLineToRelative(-23f)
                quadToRelative(0f, -24f, 13f, -44f)
                reflectiveQuadToRelative(36f, -30f)
                quadToRelative(26f, -11f, 53.5f, -17f)
                reflectiveQuadToRelative(57.5f, -6f)
                quadToRelative(30f, 0f, 57.5f, 6f)
                reflectiveQuadToRelative(53.5f, 17f)
                quadToRelative(23f, 10f, 36f, 30f)
                reflectiveQuadToRelative(13f, 44f)
                verticalLineToRelative(23f)
                horizontalLineTo(520f)
                close()
                moveTo(280f, 720f)
                quadToRelative(-33f, 0f, -56.5f, -23.5f)
                reflectiveQuadTo(200f, 640f)
                quadToRelative(0f, -33f, 23.5f, -56.5f)
                reflectiveQuadTo(280f, 560f)
                quadToRelative(33f, 0f, 56.5f, 23.5f)
                reflectiveQuadTo(360f, 640f)
                quadToRelative(0f, 33f, -23.5f, 56.5f)
                reflectiveQuadTo(280f, 720f)
                close()
                moveToRelative(400f, 0f)
                quadToRelative(-33f, 0f, -56.5f, -23.5f)
                reflectiveQuadTo(600f, 640f)
                quadToRelative(0f, -33f, 23.5f, -56.5f)
                reflectiveQuadTo(680f, 560f)
                quadToRelative(33f, 0f, 56.5f, 23.5f)
                reflectiveQuadTo(760f, 640f)
                quadToRelative(0f, 33f, -23.5f, 56.5f)
                reflectiveQuadTo(680f, 720f)
                close()
                moveTo(510f, 525f)
                lineToRelative(27f, -27f)
                quadToRelative(9f, -8f, 21f, -8f)
                reflectiveQuadToRelative(21f, 9f)
                quadToRelative(9f, 9f, 9f, 21f)
                reflectiveQuadToRelative(-9f, 21f)
                lineToRelative(-71f, 71f)
                quadToRelative(-12f, 12f, -28f, 12f)
                reflectiveQuadToRelative(-28f, -12f)
                lineToRelative(-71f, -71f)
                quadToRelative(-9f, -9f, -9f, -21f)
                reflectiveQuadToRelative(9f, -21f)
                quadToRelative(9f, -9f, 21f, -8.5f)
                reflectiveQuadToRelative(21f, 8.5f)
                lineToRelative(27f, 26f)
                verticalLineToRelative(-55f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(480f, 440f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(510f, 470f)
                verticalLineToRelative(55f)
                close()
                moveTo(80f, 400f)
                verticalLineToRelative(-23f)
                quadToRelative(0f, -24f, 13f, -44f)
                reflectiveQuadToRelative(36f, -30f)
                quadToRelative(26f, -11f, 53.5f, -17f)
                reflectiveQuadToRelative(57.5f, -6f)
                quadToRelative(20f, 0f, 39.5f, 3f)
                reflectiveQuadToRelative(37.5f, 8f)
                quadToRelative(-17f, 17f, -27f, 39f)
                reflectiveQuadToRelative(-10f, 47f)
                verticalLineToRelative(23f)
                horizontalLineTo(80f)
                close()
                moveToRelative(240f, 0f)
                verticalLineToRelative(-23f)
                quadToRelative(0f, -24f, 13f, -44f)
                reflectiveQuadToRelative(36f, -30f)
                quadToRelative(26f, -11f, 53.5f, -17f)
                reflectiveQuadToRelative(57.5f, -6f)
                quadToRelative(30f, 0f, 57.5f, 6f)
                reflectiveQuadToRelative(53.5f, 17f)
                quadToRelative(23f, 10f, 36f, 30f)
                reflectiveQuadToRelative(13f, 44f)
                verticalLineToRelative(23f)
                horizontalLineTo(320f)
                close()
                moveToRelative(360f, 0f)
                verticalLineToRelative(-23f)
                quadToRelative(0f, -25f, -10f, -47f)
                reflectiveQuadToRelative(-27f, -39f)
                quadToRelative(18f, -5f, 37.5f, -8f)
                reflectiveQuadToRelative(39.5f, -3f)
                quadToRelative(30f, 0f, 57.5f, 6f)
                reflectiveQuadToRelative(53.5f, 17f)
                quadToRelative(23f, 10f, 36f, 30f)
                reflectiveQuadToRelative(13f, 44f)
                verticalLineToRelative(23f)
                horizontalLineTo(680f)
                close()
                moveTo(240f, 240f)
                quadToRelative(-33f, 0f, -56.5f, -23.5f)
                reflectiveQuadTo(160f, 160f)
                quadToRelative(0f, -33f, 23.5f, -56.5f)
                reflectiveQuadTo(240f, 80f)
                quadToRelative(33f, 0f, 56.5f, 23.5f)
                reflectiveQuadTo(320f, 160f)
                quadToRelative(0f, 33f, -23.5f, 56.5f)
                reflectiveQuadTo(240f, 240f)
                close()
                moveToRelative(240f, 0f)
                quadToRelative(-33f, 0f, -56.5f, -23.5f)
                reflectiveQuadTo(400f, 160f)
                quadToRelative(0f, -33f, 23.5f, -56.5f)
                reflectiveQuadTo(480f, 80f)
                quadToRelative(33f, 0f, 56.5f, 23.5f)
                reflectiveQuadTo(560f, 160f)
                quadToRelative(0f, 33f, -23.5f, 56.5f)
                reflectiveQuadTo(480f, 240f)
                close()
                moveToRelative(240f, 0f)
                quadToRelative(-33f, 0f, -56.5f, -23.5f)
                reflectiveQuadTo(640f, 160f)
                quadToRelative(0f, -33f, 23.5f, -56.5f)
                reflectiveQuadTo(720f, 80f)
                quadToRelative(33f, 0f, 56.5f, 23.5f)
                reflectiveQuadTo(800f, 160f)
                quadToRelative(0f, 33f, -23.5f, 56.5f)
                reflectiveQuadTo(720f, 240f)
                close()
            }
        }.build()
        
        return _Reduce_capacity!!
    }

private var _Reduce_capacity: ImageVector? = null

