package com.composables.icons.materialsymbols.roundedfilled

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.RoundedFilled.Settings_slow_motion: ImageVector
    get() {
        if (_Settings_slow_motion != null) return _Settings_slow_motion!!
        
        _Settings_slow_motion = ImageVector.Builder(
            name = "settings_slow_motion",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(423f, 880f)
                quadToRelative(-24f, 0f, -40f, -18.5f)
                reflectiveQuadTo(363f, 818f)
                lineToRelative(-9f, -66f)
                quadToRelative(-13f, -5f, -24.5f, -12f)
                reflectiveQuadTo(307f, 725f)
                lineToRelative(-62f, 26f)
                quadToRelative(-25f, 11f, -50f, 2f)
                reflectiveQuadToRelative(-39f, -32f)
                lineToRelative(-47f, -82f)
                quadToRelative(-14f, -23f, -8f, -49f)
                reflectiveQuadToRelative(27f, -43f)
                lineToRelative(53f, -40f)
                quadToRelative(-1f, -7f, -1f, -13.5f)
                verticalLineToRelative(-27f)
                quadToRelative(0f, -6.5f, 1f, -13.5f)
                lineToRelative(-53f, -40f)
                quadToRelative(-21f, -17f, -27f, -43f)
                reflectiveQuadToRelative(8f, -49f)
                lineToRelative(47f, -82f)
                quadToRelative(14f, -23f, 39f, -32f)
                reflectiveQuadToRelative(50f, 2f)
                lineToRelative(62f, 26f)
                quadToRelative(11f, -8f, 22.5f, -15f)
                reflectiveQuadToRelative(24.5f, -12f)
                lineToRelative(9f, -66f)
                quadToRelative(4f, -26f, 24f, -44f)
                reflectiveQuadToRelative(46f, -18f)
                horizontalLineToRelative(94f)
                quadToRelative(26f, 0f, 46f, 18f)
                reflectiveQuadToRelative(24f, 44f)
                lineToRelative(9f, 66f)
                quadToRelative(13f, 5f, 24.5f, 12f)
                reflectiveQuadToRelative(22.5f, 15f)
                lineToRelative(62f, -26f)
                quadToRelative(25f, -11f, 50f, -2f)
                reflectiveQuadToRelative(39f, 32f)
                lineToRelative(47f, 82f)
                quadToRelative(14f, 23f, 8f, 49f)
                reflectiveQuadToRelative(-27f, 43f)
                lineToRelative(-8f, 6f)
                quadToRelative(-8f, 6f, -17f, 6.5f)
                reflectiveQuadToRelative(-18f, -3.5f)
                quadToRelative(-21f, -9f, -42.5f, -14.5f)
                reflectiveQuadTo(702f, 401f)
                quadToRelative(-25f, -2f, -49.5f, 2f)
                reflectiveQuadToRelative(-49.5f, 7f)
                quadToRelative(-19f, -32f, -51f, -51f)
                reflectiveQuadToRelative(-70f, -19f)
                quadToRelative(-58f, 0f, -99f, 41f)
                reflectiveQuadToRelative(-41f, 99f)
                quadToRelative(0f, 38f, 19f, 70.5f)
                reflectiveQuadToRelative(52f, 51.5f)
                quadToRelative(-7f, 20f, -10f, 41f)
                reflectiveQuadToRelative(-3f, 42f)
                quadToRelative(0f, 42f, 13.5f, 81.5f)
                reflectiveQuadTo(451f, 841f)
                quadToRelative(8f, 12f, -1f, 25.5f)
                reflectiveQuadTo(423f, 880f)
                close()
                moveToRelative(231f, -130f)
                quadToRelative(-5f, 3f, -10.5f, 0.5f)
                reflectiveQuadTo(638f, 742f)
                verticalLineToRelative(-124f)
                quadToRelative(0f, -6f, 5.5f, -8.5f)
                reflectiveQuadToRelative(10.5f, 0.5f)
                lineToRelative(95f, 62f)
                quadToRelative(5f, 3f, 5f, 8f)
                reflectiveQuadToRelative(-5f, 8f)
                lineToRelative(-95f, 62f)
                close()
                moveToRelative(95f, 117f)
                quadToRelative(-11f, 4f, -21f, -2.5f)
                reflectiveQuadTo(715f, 845f)
                quadToRelative(-2f, -11f, 3.5f, -22f)
                reflectiveQuadToRelative(16.5f, -16f)
                quadToRelative(38f, -17f, 60.5f, -51f)
                reflectiveQuadToRelative(22.5f, -76f)
                quadToRelative(0f, -42f, -22.5f, -76f)
                reflectiveQuadTo(735f, 553f)
                quadToRelative(-12f, -5f, -17f, -16f)
                reflectiveQuadToRelative(-3f, -22f)
                quadToRelative(3f, -13f, 13f, -19.5f)
                reflectiveQuadToRelative(21f, -2.5f)
                quadToRelative(59f, 22f, 94f, 73f)
                reflectiveQuadToRelative(35f, 114f)
                quadToRelative(0f, 63f, -35f, 114f)
                reflectiveQuadToRelative(-94f, 73f)
                close()
                moveToRelative(-141f, -2f)
                quadToRelative(-20f, -8f, -37.5f, -19f)
                reflectiveQuadTo(538f, 820f)
                quadToRelative(-15f, -15f, -26f, -32.5f)
                reflectiveQuadTo(493f, 750f)
                quadToRelative(-4f, -11f, 2.5f, -21f)
                reflectiveQuadToRelative(18.5f, -13f)
                quadToRelative(11f, -2f, 21.5f, 4f)
                reflectiveQuadToRelative(15.5f, 17f)
                quadToRelative(5f, 12f, 12.5f, 22f)
                reflectiveQuadToRelative(16.5f, 19f)
                quadToRelative(9f, 9f, 19.5f, 16.5f)
                reflectiveQuadTo(621f, 807f)
                quadToRelative(11f, 5f, 16.5f, 16f)
                reflectiveQuadToRelative(3.5f, 22f)
                quadToRelative(-3f, 12f, -12.5f, 18f)
                reflectiveQuadTo(608f, 865f)
                close()
                moveToRelative(-94f, -221f)
                quadToRelative(-12f, -3f, -18.5f, -13f)
                reflectiveQuadToRelative(-2.5f, -21f)
                quadToRelative(8f, -20f, 19f, -37.5f)
                reflectiveQuadToRelative(26f, -32.5f)
                quadToRelative(15f, -15f, 32.5f, -26f)
                reflectiveQuadToRelative(37.5f, -19f)
                quadToRelative(11f, -4f, 20.5f, 2f)
                reflectiveQuadToRelative(12.5f, 18f)
                quadToRelative(2f, 11f, -3.5f, 22f)
                reflectiveQuadTo(621f, 553f)
                quadToRelative(-11f, 5f, -21.5f, 12.5f)
                reflectiveQuadTo(580f, 582f)
                quadToRelative(-9f, 9f, -16.5f, 19f)
                reflectiveQuadTo(551f, 623f)
                quadToRelative(-5f, 11f, -15.5f, 17f)
                reflectiveQuadToRelative(-21.5f, 4f)
                close()
            }
        }.build()
        
        return _Settings_slow_motion!!
    }

private var _Settings_slow_motion: ImageVector? = null

