package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Air_purifier_gen: ImageVector
    get() {
        if (_Air_purifier_gen != null) return _Air_purifier_gen!!
        
        _Air_purifier_gen = ImageVector.Builder(
            name = "air_purifier_gen",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(120f, 240f)
                quadToRelative(0f, -50f, 35f, -85f)
                reflectiveQuadToRelative(85f, -35f)
                horizontalLineToRelative(160f)
                quadToRelative(50f, 0f, 85f, 35f)
                reflectiveQuadToRelative(35f, 85f)
                verticalLineToRelative(560f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(480f, 840f)
                horizontalLineTo(160f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(120f, 800f)
                verticalLineToRelative(-560f)
                close()
                moveToRelative(280f, 360f)
                horizontalLineToRelative(40f)
                verticalLineToRelative(-200f)
                horizontalLineToRelative(-40f)
                verticalLineToRelative(200f)
                close()
                moveTo(200f, 760f)
                horizontalLineToRelative(240f)
                verticalLineToRelative(-80f)
                horizontalLineToRelative(-40f)
                quadToRelative(-33f, 0f, -56.5f, -23.5f)
                reflectiveQuadTo(320f, 600f)
                verticalLineToRelative(-200f)
                quadToRelative(0f, -33f, 23.5f, -56.5f)
                reflectiveQuadTo(400f, 320f)
                horizontalLineToRelative(40f)
                verticalLineToRelative(-80f)
                quadToRelative(0f, -17f, -11.5f, -28.5f)
                reflectiveQuadTo(400f, 200f)
                horizontalLineTo(240f)
                quadToRelative(-17f, 0f, -28.5f, 11.5f)
                reflectiveQuadTo(200f, 240f)
                verticalLineToRelative(520f)
                close()
                moveToRelative(488f, -217f)
                quadToRelative(-16f, 0f, -31.5f, -3f)
                reflectiveQuadToRelative(-31.5f, -8f)
                quadToRelative(-16f, -5f, -22.5f, -20f)
                reflectiveQuadToRelative(-1.5f, -32f)
                quadToRelative(5f, -15f, 19f, -22f)
                reflectiveQuadToRelative(30f, -2f)
                quadToRelative(11f, 3f, 20.5f, 5f)
                reflectiveQuadToRelative(18.5f, 2f)
                quadToRelative(12f, 0f, 24f, -4f)
                reflectiveQuadToRelative(25f, -12f)
                quadToRelative(24f, -17f, 48f, -23f)
                reflectiveQuadToRelative(46f, -6f)
                quadToRelative(15f, 0f, 31f, 2.5f)
                reflectiveQuadToRelative(32f, 7.5f)
                quadToRelative(16f, 5f, 23.5f, 20f)
                reflectiveQuadToRelative(2.5f, 32f)
                quadToRelative(-5f, 16f, -20f, 23f)
                reflectiveQuadToRelative(-31f, 2f)
                quadToRelative(-11f, -3f, -20.5f, -5f)
                reflectiveQuadToRelative(-17.5f, -2f)
                quadToRelative(-12f, 0f, -26.5f, 4.5f)
                reflectiveQuadTo(775f, 518f)
                quadToRelative(-21f, 14f, -42.5f, 19.5f)
                reflectiveQuadTo(688f, 543f)
                close()
                moveToRelative(1f, -156f)
                quadToRelative(-16f, 0f, -32f, -3f)
                reflectiveQuadToRelative(-32f, -8f)
                quadToRelative(-16f, -5f, -23f, -20f)
                reflectiveQuadToRelative(-2f, -32f)
                quadToRelative(5f, -15f, 19.5f, -22f)
                reflectiveQuadToRelative(30.5f, -2f)
                quadToRelative(11f, 4f, 21f, 5.5f)
                reflectiveQuadToRelative(18f, 1.5f)
                quadToRelative(12f, 0f, 24f, -3.5f)
                reflectiveQuadToRelative(25f, -12.5f)
                quadToRelative(25f, -17f, 48.5f, -23f)
                reflectiveQuadToRelative(45.5f, -6f)
                quadToRelative(16f, 0f, 31.5f, 2.5f)
                reflectiveQuadTo(895f, 272f)
                quadToRelative(16f, 5f, 23f, 20f)
                reflectiveQuadToRelative(2f, 32f)
                quadToRelative(-5f, 16f, -19.5f, 23f)
                reflectiveQuadToRelative(-30.5f, 2f)
                quadToRelative(-11f, -4f, -20.5f, -5.5f)
                reflectiveQuadTo(832f, 342f)
                quadToRelative(-13f, 0f, -26.5f, 4f)
                reflectiveQuadTo(775f, 362f)
                quadToRelative(-18f, 13f, -40.5f, 19f)
                reflectiveQuadToRelative(-45.5f, 6f)
                close()
                moveToRelative(0f, 312f)
                quadToRelative(-17f, 0f, -32.5f, -3f)
                reflectiveQuadToRelative(-31.5f, -8f)
                quadToRelative(-16f, -5f, -22.5f, -20f)
                reflectiveQuadToRelative(-1.5f, -32f)
                quadToRelative(5f, -15f, 19f, -22f)
                reflectiveQuadToRelative(30f, -2f)
                quadToRelative(11f, 3f, 21f, 5f)
                reflectiveQuadToRelative(18f, 2f)
                quadToRelative(12f, 0f, 24f, -3.5f)
                reflectiveQuadToRelative(25f, -12.5f)
                quadToRelative(23f, -16f, 49f, -22.5f)
                reflectiveQuadToRelative(46f, -6.5f)
                quadToRelative(15f, 0f, 30.5f, 2.5f)
                reflectiveQuadTo(895f, 584f)
                quadToRelative(16f, 5f, 23.5f, 20f)
                reflectiveQuadToRelative(2.5f, 32f)
                quadToRelative(-5f, 16f, -20f, 23f)
                reflectiveQuadToRelative(-31f, 2f)
                quadToRelative(-12f, -4f, -21f, -5.5f)
                reflectiveQuadToRelative(-17f, -1.5f)
                quadToRelative(-14f, 0f, -28.5f, 4.5f)
                reflectiveQuadTo(775f, 674f)
                quadToRelative(-17f, 12f, -39.5f, 18.5f)
                reflectiveQuadTo(689f, 699f)
                close()
                moveToRelative(-249f, 61f)
                verticalLineToRelative(-528.5f)
                verticalLineToRelative(8.5f)
                verticalLineToRelative(-8.5f)
                verticalLineTo(760f)
                close()
            }
        }.build()
        
        return _Air_purifier_gen!!
    }

private var _Air_purifier_gen: ImageVector? = null

