package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Boat_bus: ImageVector
    get() {
        if (_Boat_bus != null) return _Boat_bus!!
        
        _Boat_bus = ImageVector.Builder(
            name = "boat_bus",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(161f, 879f)
                quadToRelative(-17f, 1f, -29f, -11f)
                reflectiveQuadToRelative(-12f, -29f)
                quadToRelative(0f, -17f, 11f, -28.5f)
                reflectiveQuadToRelative(28f, -11.5f)
                quadToRelative(48f, -2f, 84.5f, -10f)
                reflectiveQuadToRelative(79.5f, -26f)
                quadToRelative(8f, -3f, 16f, -4.5f)
                reflectiveQuadToRelative(15f, 3.5f)
                quadToRelative(14f, 8f, 28f, 14.5f)
                reflectiveQuadToRelative(30f, 11.5f)
                quadToRelative(16f, 5f, 23.5f, 20.5f)
                reflectiveQuadTo(437f, 840f)
                quadToRelative(-5f, 15f, -19.5f, 22f)
                reflectiveQuadTo(387f, 864f)
                quadToRelative(-13f, -4f, -25f, -9f)
                reflectiveQuadToRelative(-24f, -11f)
                quadToRelative(-41f, 17f, -83f, 25f)
                reflectiveQuadToRelative(-94f, 10f)
                close()
                moveToRelative(259f, -799f)
                horizontalLineToRelative(120f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(580f, 120f)
                verticalLineToRelative(40f)
                horizontalLineToRelative(100f)
                quadToRelative(33f, 0f, 56.5f, 23.5f)
                reflectiveQuadTo(760f, 240f)
                verticalLineToRelative(41f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(720f, 321f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(680f, 281f)
                verticalLineToRelative(-41f)
                horizontalLineTo(280f)
                verticalLineToRelative(113f)
                lineToRelative(150f, -40f)
                quadToRelative(16f, -5f, 30f, 4f)
                reflectiveQuadToRelative(19f, 25f)
                quadToRelative(5f, 16f, -4f, 30f)
                reflectiveQuadToRelative(-25f, 19f)
                lineToRelative(-248f, 65f)
                lineToRelative(46f, 149f)
                quadToRelative(11f, -10f, 22.5f, -19.5f)
                reflectiveQuadTo(293f, 565f)
                lineToRelative(11f, -11f)
                quadToRelative(12f, -13f, 28.5f, -12.5f)
                reflectiveQuadTo(361f, 555f)
                quadToRelative(7f, 7f, 14.5f, 15.5f)
                reflectiveQuadTo(389f, 586f)
                quadToRelative(5f, 6f, 8f, 12.5f)
                reflectiveQuadToRelative(3f, 14.5f)
                quadToRelative(0f, 8f, -3f, 16f)
                reflectiveQuadToRelative(-10f, 14f)
                quadToRelative(-12f, 11f, -29f, 10f)
                reflectiveQuadToRelative(-28f, -13f)
                quadToRelative(-19f, 18f, -40.5f, 32.5f)
                reflectiveQuadTo(245f, 698f)
                quadToRelative(-18f, 8f, -36f, 1f)
                reflectiveQuadToRelative(-23f, -25f)
                lineToRelative(-73f, -234f)
                quadToRelative(-5f, -17f, 3f, -31f)
                reflectiveQuadToRelative(25f, -19f)
                lineToRelative(59f, -16f)
                verticalLineToRelative(-134f)
                quadToRelative(0f, -33f, 23.5f, -56.5f)
                reflectiveQuadTo(280f, 160f)
                horizontalLineToRelative(100f)
                verticalLineToRelative(-40f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(420f, 80f)
                close()
                moveToRelative(180f, 740f)
                verticalLineToRelative(20f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(560f, 880f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(520f, 840f)
                verticalLineToRelative(-31f)
                quadToRelative(-19f, -11f, -29.5f, -29f)
                reflectiveQuadTo(480f, 740f)
                verticalLineToRelative(-240f)
                quadToRelative(0f, -52f, 48f, -76f)
                reflectiveQuadToRelative(152f, -24f)
                quadToRelative(108f, 0f, 154f, 23f)
                reflectiveQuadToRelative(46f, 77f)
                verticalLineToRelative(240f)
                quadToRelative(0f, 21f, -10.5f, 39.5f)
                reflectiveQuadTo(840f, 809f)
                verticalLineToRelative(31f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(800f, 880f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(760f, 840f)
                verticalLineToRelative(-20f)
                horizontalLineTo(600f)
                close()
                moveToRelative(-5f, -70f)
                quadToRelative(15f, 0f, 25f, -10f)
                reflectiveQuadToRelative(10f, -25f)
                quadToRelative(0f, -15f, -10f, -25f)
                reflectiveQuadToRelative(-25f, -10f)
                quadToRelative(-15f, 0f, -25f, 10f)
                reflectiveQuadToRelative(-10f, 25f)
                quadToRelative(0f, 14f, 10.5f, 24.5f)
                reflectiveQuadTo(595f, 750f)
                close()
                moveToRelative(170f, 0f)
                quadToRelative(15f, 0f, 25f, -10f)
                reflectiveQuadToRelative(10f, -25f)
                quadToRelative(0f, -15f, -10f, -25f)
                reflectiveQuadToRelative(-25f, -10f)
                quadToRelative(-15f, 0f, -25f, 10f)
                reflectiveQuadToRelative(-10f, 25f)
                quadToRelative(0f, 14f, 10.5f, 24.5f)
                reflectiveQuadTo(765f, 750f)
                close()
                moveTo(540f, 600f)
                horizontalLineToRelative(280f)
                verticalLineToRelative(-80f)
                horizontalLineTo(540f)
                verticalLineToRelative(80f)
                close()
                moveToRelative(-90f, -209f)
                close()
            }
        }.build()
        
        return _Boat_bus!!
    }

private var _Boat_bus: ImageVector? = null

