package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Car_defrost_mid_low_right: ImageVector
    get() {
        if (_Car_defrost_mid_low_right != null) return _Car_defrost_mid_low_right!!
        
        _Car_defrost_mid_low_right = ImageVector.Builder(
            name = "car_defrost_mid_low_right",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(166f, 550f)
                horizontalLineTo(71f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(41f, 520f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(71f, 490f)
                horizontalLineToRelative(95f)
                lineToRelative(-26f, -26f)
                quadToRelative(-9f, -9f, -9f, -21.5f)
                reflectiveQuadToRelative(9f, -21.5f)
                quadToRelative(9f, -9f, 21f, -9f)
                reflectiveQuadToRelative(21f, 9f)
                lineToRelative(71f, 71f)
                quadToRelative(6f, 6f, 8.5f, 13f)
                reflectiveQuadToRelative(2.5f, 15f)
                quadToRelative(0f, 8f, -2.5f, 15f)
                reflectiveQuadToRelative(-8.5f, 13f)
                lineToRelative(-71f, 71f)
                quadToRelative(-9f, 9f, -21f, 9f)
                reflectiveQuadToRelative(-21f, -9f)
                quadToRelative(-9f, -9f, -9f, -21.5f)
                reflectiveQuadToRelative(9f, -21.5f)
                lineToRelative(26f, -26f)
                close()
                moveToRelative(-5f, 353f)
                quadToRelative(-8f, 0f, -15f, -2.5f)
                reflectiveQuadTo(133f, 892f)
                lineToRelative(-71f, -71f)
                quadToRelative(-9f, -9f, -9f, -21f)
                reflectiveQuadToRelative(9f, -21f)
                quadToRelative(9f, -9f, 21.5f, -9f)
                reflectiveQuadToRelative(21.5f, 9f)
                lineToRelative(26f, 26f)
                verticalLineToRelative(-95f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(161f, 680f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(191f, 710f)
                verticalLineToRelative(95f)
                lineToRelative(26f, -26f)
                quadToRelative(9f, -9f, 21.5f, -9f)
                reflectiveQuadToRelative(21.5f, 9f)
                quadToRelative(9f, 9f, 9f, 21f)
                reflectiveQuadToRelative(-9f, 21f)
                lineToRelative(-71f, 71f)
                quadToRelative(-6f, 6f, -13f, 8.5f)
                reflectiveQuadTo(161f, 903f)
                close()
                moveToRelative(434f, -223f)
                horizontalLineTo(346f)
                lineToRelative(-27f, 46f)
                quadToRelative(-8f, 13f, -22.5f, 14f)
                reflectiveQuadToRelative(-27.5f, -8f)
                quadToRelative(-15f, -11f, -17f, -29f)
                reflectiveQuadToRelative(8f, -35f)
                lineToRelative(39f, -68f)
                quadToRelative(11f, -19f, 29.5f, -29.5f)
                reflectiveQuadTo(369f, 560f)
                horizontalLineToRelative(92f)
                lineToRelative(58f, -201f)
                quadToRelative(10f, -35f, 37f, -57f)
                reflectiveQuadToRelative(61f, -22f)
                quadToRelative(48f, 0f, 78.5f, 36.5f)
                reflectiveQuadTo(717f, 401f)
                lineToRelative(-43f, 215f)
                quadToRelative(-5f, 28f, -27.5f, 46f)
                reflectiveQuadTo(595f, 680f)
                close()
                moveTo(419f, 880f)
                quadToRelative(-25f, 0f, -42.5f, -17.5f)
                reflectiveQuadTo(359f, 820f)
                quadToRelative(0f, -25f, 17.5f, -42.5f)
                reflectiveQuadTo(419f, 760f)
                horizontalLineToRelative(225f)
                quadToRelative(18f, 0f, 37f, 6.5f)
                reflectiveQuadToRelative(39f, 20.5f)
                verticalLineToRelative(-44f)
                quadToRelative(0f, -63f, 16.5f, -129.5f)
                reflectiveQuadTo(786f, 476f)
                lineToRelative(20f, -42f)
                quadToRelative(12f, -26f, 8f, -52.5f)
                reflectiveQuadTo(791f, 336f)
                quadToRelative(-8f, -8f, -12f, -18f)
                reflectiveQuadToRelative(-4f, -21f)
                quadToRelative(0f, -23f, 17f, -40f)
                reflectiveQuadToRelative(40f, -17f)
                quadToRelative(20f, 0f, 36.5f, 10.5f)
                reflectiveQuadTo(894f, 279f)
                quadToRelative(13f, 26f, 19.5f, 53f)
                reflectiveQuadToRelative(6.5f, 54f)
                quadToRelative(0f, 14f, -2f, 29.5f)
                reflectiveQuadToRelative(-7f, 32.5f)
                lineToRelative(-96f, 373f)
                quadToRelative(-8f, 26f, -29f, 42.5f)
                reflectiveQuadTo(738f, 880f)
                horizontalLineTo(419f)
                close()
                moveToRelative(222f, -640f)
                quadToRelative(-33f, 0f, -56.5f, -23.5f)
                reflectiveQuadTo(561f, 160f)
                quadToRelative(0f, -33f, 23.5f, -56.5f)
                reflectiveQuadTo(641f, 80f)
                quadToRelative(33f, 0f, 56.5f, 23.5f)
                reflectiveQuadTo(721f, 160f)
                quadToRelative(0f, 33f, -23.5f, 56.5f)
                reflectiveQuadTo(641f, 240f)
                close()
                moveToRelative(-326f, 55f)
                quadToRelative(-13f, -13f, -20f, -31f)
                reflectiveQuadToRelative(-7f, -38f)
                quadToRelative(0f, -9f, 1.5f, -17f)
                reflectiveQuadToRelative(4.5f, -15f)
                quadToRelative(5f, -13f, 18f, -19f)
                reflectiveQuadToRelative(25f, 0f)
                quadToRelative(11f, 5f, 15.5f, 16f)
                reflectiveQuadToRelative(-1.5f, 22f)
                quadToRelative(-2f, 3f, -2.5f, 6f)
                reflectiveQuadToRelative(-0.5f, 7f)
                quadToRelative(0f, 9f, 3f, 16.5f)
                reflectiveQuadToRelative(11f, 15.5f)
                quadToRelative(11f, 11f, 18f, 26.5f)
                reflectiveQuadToRelative(9f, 32.5f)
                quadToRelative(2f, 11f, 0.5f, 21f)
                reflectiveQuadToRelative(-5.5f, 18f)
                quadToRelative(-5f, 14f, -17.5f, 21f)
                reflectiveQuadToRelative(-25.5f, 1f)
                quadToRelative(-11f, -5f, -15.5f, -16.5f)
                reflectiveQuadToRelative(0.5f, -22.5f)
                quadToRelative(1f, -2f, 3f, -13f)
                quadToRelative(0f, -8f, -3f, -15.5f)
                reflectiveQuadTo(315f, 295f)
                close()
                moveToRelative(-126f, -4f)
                quadToRelative(-10f, -13f, -15f, -29f)
                reflectiveQuadToRelative(-5f, -34f)
                quadToRelative(0f, -8f, 1f, -15.5f)
                reflectiveQuadToRelative(3f, -13.5f)
                quadToRelative(5f, -14f, 16f, -21.5f)
                reflectiveQuadToRelative(24f, -2.5f)
                quadToRelative(12f, 5f, 17.5f, 16f)
                reflectiveQuadToRelative(0.5f, 22f)
                quadToRelative(-2f, 3f, -2f, 6f)
                verticalLineToRelative(7f)
                quadToRelative(0f, 10f, 2.5f, 19f)
                reflectiveQuadToRelative(9.5f, 17f)
                quadToRelative(10f, 13f, 15f, 29f)
                reflectiveQuadToRelative(5f, 34f)
                quadToRelative(0f, 8f, -1f, 15.5f)
                reflectiveQuadToRelative(-3f, 13.5f)
                quadToRelative(-5f, 14f, -16f, 21.5f)
                reflectiveQuadToRelative(-24f, 2.5f)
                quadToRelative(-12f, -5f, -17.5f, -16f)
                reflectiveQuadToRelative(-0.5f, -22f)
                quadToRelative(2f, -3f, 2f, -6f)
                verticalLineToRelative(-7f)
                quadToRelative(0f, -10f, -2.5f, -19f)
                reflectiveQuadToRelative(-9.5f, -17f)
                close()
                moveToRelative(271f, 29f)
                quadToRelative(-14f, 0f, -23f, -10f)
                reflectiveQuadToRelative(-7f, -24f)
                lineToRelative(24f, -163f)
                quadToRelative(-43f, -11f, -86f, -17f)
                reflectiveQuadToRelative(-87f, -6f)
                quadToRelative(-44f, 0f, -87f, 6f)
                reflectiveQuadToRelative(-86f, 17f)
                lineToRelative(24f, 163f)
                quadToRelative(2f, 14f, -7f, 24f)
                reflectiveQuadToRelative(-23f, 10f)
                quadToRelative(-11f, 0f, -19.5f, -7.5f)
                reflectiveQuadTo(72f, 294f)
                lineTo(47f, 119f)
                quadToRelative(-2f, -17f, 6.5f, -31.5f)
                reflectiveQuadTo(79f, 68f)
                quadToRelative(47f, -13f, 100f, -20.5f)
                reflectiveQuadToRelative(102f, -7.5f)
                quadToRelative(49f, 0f, 102.5f, 7.5f)
                reflectiveQuadTo(483f, 68f)
                quadToRelative(17f, 5f, 25.5f, 19.5f)
                reflectiveQuadTo(515f, 119f)
                lineToRelative(-25f, 175f)
                quadToRelative(-2f, 11f, -10.5f, 18.5f)
                reflectiveQuadTo(460f, 320f)
                close()
            }
        }.build()
        
        return _Car_defrost_mid_low_right!!
    }

private var _Car_defrost_mid_low_right: ImageVector? = null

