package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Component_exchange: ImageVector
    get() {
        if (_Component_exchange != null) return _Component_exchange!!
        
        _Component_exchange = ImageVector.Builder(
            name = "component_exchange",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(196f, 840f)
                lineToRelative(-6f, -51f)
                lineToRelative(-8f, -4f)
                quadToRelative(-4f, -2f, -11f, -7f)
                lineToRelative(-48f, 20f)
                lineToRelative(-44f, -76f)
                lineToRelative(41f, -31f)
                verticalLineToRelative(-21f)
                lineToRelative(-41f, -32f)
                lineToRelative(44f, -76f)
                lineToRelative(48f, 20f)
                quadToRelative(5f, -3f, 9.5f, -6f)
                reflectiveQuadToRelative(9.5f, -5f)
                lineToRelative(6f, -51f)
                horizontalLineToRelative(88f)
                lineToRelative(6f, 51f)
                lineToRelative(4f, 2f)
                lineToRelative(4f, 2f)
                quadToRelative(2f, 1f, 5f, 3f)
                lineToRelative(6f, 4f)
                lineToRelative(48f, -20f)
                lineToRelative(44f, 76f)
                lineToRelative(-41f, 31f)
                verticalLineToRelative(22f)
                lineToRelative(219f, -127f)
                lineToRelative(-45f, 79f)
                lineToRelative(12f, 9f)
                lineToRelative(-158f, 92f)
                lineToRelative(-31f, 54f)
                lineToRelative(-48f, -20f)
                quadToRelative(-5f, 3f, -9.5f, 6f)
                reflectiveQuadToRelative(-9.5f, 5f)
                lineToRelative(-6f, 51f)
                horizontalLineToRelative(-88f)
                close()
                moveToRelative(44f, -220f)
                quadToRelative(-25f, 0f, -42.5f, 17.5f)
                reflectiveQuadTo(180f, 680f)
                quadToRelative(0f, 25f, 17.5f, 42.5f)
                reflectiveQuadTo(240f, 740f)
                quadToRelative(25f, 0f, 42.5f, -17.5f)
                reflectiveQuadTo(300f, 680f)
                quadToRelative(0f, -25f, -17.5f, -42.5f)
                reflectiveQuadTo(240f, 620f)
                close()
                moveToRelative(156f, -220f)
                lineToRelative(-6f, -51f)
                quadToRelative(-2f, -2f, -5f, -3f)
                reflectiveQuadToRelative(-5f, -3f)
                verticalLineToRelative(220f)
                lineToRelative(-15f, -26f)
                lineToRelative(-45f, 19f)
                verticalLineToRelative(-204f)
                lineToRelative(-40f, -70f)
                lineToRelative(40f, -31f)
                verticalLineToRelative(-21f)
                lineToRelative(-41f, -32f)
                lineToRelative(44f, -76f)
                lineToRelative(48f, 20f)
                quadToRelative(5f, -3f, 9.5f, -6f)
                reflectiveQuadToRelative(9.5f, -5f)
                lineToRelative(6f, -51f)
                horizontalLineToRelative(88f)
                lineToRelative(6f, 51f)
                lineToRelative(8f, 4f)
                quadToRelative(4f, 2f, 11f, 7f)
                lineToRelative(48f, -20f)
                lineToRelative(44f, 76f)
                lineToRelative(-41f, 31f)
                verticalLineToRelative(21f)
                lineToRelative(41f, 32f)
                lineToRelative(-44f, 76f)
                lineToRelative(-48f, -20f)
                quadToRelative(-5f, 3f, -9.5f, 6f)
                reflectiveQuadToRelative(-9.5f, 5f)
                lineToRelative(-6f, 51f)
                horizontalLineToRelative(-88f)
                close()
                moveToRelative(44f, -220f)
                quadToRelative(-25f, 0f, -42.5f, 17.5f)
                reflectiveQuadTo(380f, 240f)
                quadToRelative(0f, 25f, 17.5f, 42.5f)
                reflectiveQuadTo(440f, 300f)
                quadToRelative(25f, 0f, 42.5f, -17.5f)
                reflectiveQuadTo(500f, 240f)
                quadToRelative(0f, -25f, -17.5f, -42.5f)
                reflectiveQuadTo(440f, 180f)
                close()
                moveToRelative(236f, 660f)
                lineToRelative(-6f, -51f)
                lineToRelative(-8f, -4f)
                quadToRelative(-4f, -2f, -11f, -7f)
                lineToRelative(-48f, 20f)
                lineToRelative(-44f, -76f)
                lineToRelative(41f, -31f)
                verticalLineToRelative(-21f)
                lineToRelative(-41f, -31f)
                lineToRelative(44f, -77f)
                lineToRelative(48f, 20f)
                quadToRelative(3f, -2f, 4f, -2.5f)
                lineToRelative(15f, -7.5f)
                lineToRelative(-216f, -152f)
                horizontalLineToRelative(48f)
                lineToRelative(4f, -36f)
                lineToRelative(195f, 136f)
                horizontalLineToRelative(63f)
                lineToRelative(6f, 51f)
                lineToRelative(4f, 2f)
                lineToRelative(4f, 2f)
                quadToRelative(2f, 1f, 5f, 3f)
                lineToRelative(6f, 4f)
                lineToRelative(48f, -20f)
                lineToRelative(44f, 76f)
                lineToRelative(-41f, 31f)
                verticalLineToRelative(21f)
                lineToRelative(41f, 32f)
                lineToRelative(-44f, 76f)
                lineToRelative(-48f, -20f)
                quadToRelative(-5f, 3f, -9.5f, 6f)
                reflectiveQuadToRelative(-9.5f, 5f)
                lineToRelative(-6f, 51f)
                horizontalLineToRelative(-88f)
                close()
                moveToRelative(44f, -220f)
                quadToRelative(-25f, 0f, -42.5f, 17.5f)
                reflectiveQuadTo(660f, 680f)
                quadToRelative(0f, 25f, 17.5f, 42.5f)
                reflectiveQuadTo(720f, 740f)
                quadToRelative(25f, 0f, 42.5f, -17.5f)
                reflectiveQuadTo(780f, 680f)
                quadToRelative(0f, -25f, -17.5f, -42.5f)
                reflectiveQuadTo(720f, 620f)
                close()
            }
        }.build()
        
        return _Component_exchange!!
    }

private var _Component_exchange: ImageVector? = null

