package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Early_on: ImageVector
    get() {
        if (_Early_on != null) return _Early_on!!
        
        _Early_on = ImageVector.Builder(
            name = "early_on",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(680f, 840f)
                quadToRelative(-50f, 0f, -85f, -35f)
                reflectiveQuadToRelative(-35f, -85f)
                quadToRelative(0f, -50f, 35f, -85f)
                reflectiveQuadToRelative(85f, -35f)
                quadToRelative(50f, 0f, 85f, 35f)
                reflectiveQuadToRelative(35f, 85f)
                quadToRelative(0f, 50f, -35f, 85f)
                reflectiveQuadToRelative(-85f, 35f)
                close()
                moveToRelative(0f, -280f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(650f, 530f)
                verticalLineToRelative(-20f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(680f, 480f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(710f, 510f)
                verticalLineToRelative(20f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(680f, 560f)
                close()
                moveToRelative(0f, 320f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(710f, 910f)
                verticalLineToRelative(20f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(680f, 960f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(650f, 930f)
                verticalLineToRelative(-20f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(680f, 880f)
                close()
                moveToRelative(114f, -274f)
                quadToRelative(-9f, -9f, -9f, -21.5f)
                reflectiveQuadToRelative(9f, -21.5f)
                lineToRelative(14f, -14f)
                quadToRelative(9f, -9f, 21f, -8.5f)
                reflectiveQuadToRelative(21f, 9.5f)
                quadToRelative(9f, 9f, 9f, 21f)
                reflectiveQuadToRelative(-9f, 21f)
                lineToRelative(-14f, 14f)
                quadToRelative(-9f, 9f, -21f, 9f)
                reflectiveQuadToRelative(-21f, -9f)
                close()
                moveTo(567f, 833f)
                quadToRelative(9f, 9f, 9f, 21f)
                reflectiveQuadToRelative(-9f, 21f)
                lineToRelative(-15f, 15f)
                quadToRelative(-9f, 9f, -21f, 9f)
                reflectiveQuadToRelative(-21f, -9f)
                quadToRelative(-9f, -9f, -9f, -21f)
                reflectiveQuadToRelative(9f, -21f)
                lineToRelative(15f, -15f)
                quadToRelative(9f, -9f, 21f, -9f)
                reflectiveQuadToRelative(21f, 9f)
                close()
                moveToRelative(273f, -113f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(870f, 690f)
                horizontalLineToRelative(20f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(920f, 720f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(890f, 750f)
                horizontalLineToRelative(-20f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(840f, 720f)
                close()
                moveToRelative(-320f, 0f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(490f, 750f)
                horizontalLineToRelative(-20f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(440f, 720f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(470f, 690f)
                horizontalLineToRelative(20f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(520f, 720f)
                close()
                moveToRelative(274f, 113f)
                quadToRelative(9f, -9f, 21f, -8.5f)
                reflectiveQuadToRelative(21f, 8.5f)
                lineToRelative(15f, 14f)
                quadToRelative(9f, 9f, 9f, 21f)
                reflectiveQuadToRelative(-9f, 21f)
                quadToRelative(-9f, 9f, -21.5f, 9f)
                reflectiveQuadTo(808f, 889f)
                lineToRelative(-14f, -14f)
                quadToRelative(-8f, -9f, -8.5f, -21f)
                reflectiveQuadToRelative(8.5f, -21f)
                close()
                moveTo(567f, 606f)
                quadToRelative(-9f, 9f, -21.5f, 9f)
                reflectiveQuadToRelative(-21.5f, -9f)
                lineToRelative(-14f, -14f)
                quadToRelative(-8f, -9f, -8.5f, -21f)
                reflectiveQuadToRelative(8.5f, -21f)
                quadToRelative(9f, -9f, 21f, -8.5f)
                reflectiveQuadToRelative(21f, 8.5f)
                lineToRelative(15f, 14f)
                quadToRelative(9f, 9f, 9f, 21f)
                reflectiveQuadToRelative(-9f, 21f)
                close()
                moveTo(200f, 880f)
                quadToRelative(-33f, 0f, -56.5f, -23.5f)
                reflectiveQuadTo(120f, 800f)
                verticalLineToRelative(-560f)
                quadToRelative(0f, -33f, 23.5f, -56.5f)
                reflectiveQuadTo(200f, 160f)
                horizontalLineToRelative(40f)
                verticalLineToRelative(-40f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(280f, 80f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(320f, 120f)
                verticalLineToRelative(40f)
                horizontalLineToRelative(320f)
                verticalLineToRelative(-40f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(680f, 80f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(720f, 120f)
                verticalLineToRelative(40f)
                horizontalLineToRelative(40f)
                quadToRelative(33f, 0f, 56.5f, 23.5f)
                reflectiveQuadTo(840f, 240f)
                verticalLineToRelative(120f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(800f, 400f)
                horizontalLineTo(200f)
                verticalLineToRelative(400f)
                horizontalLineToRelative(120f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(360f, 840f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(320f, 880f)
                horizontalLineTo(200f)
                close()
                moveToRelative(0f, -560f)
                horizontalLineToRelative(560f)
                verticalLineToRelative(-80f)
                horizontalLineTo(200f)
                verticalLineToRelative(80f)
                close()
                moveToRelative(0f, 0f)
                verticalLineToRelative(-80f)
                verticalLineToRelative(80f)
                close()
            }
        }.build()
        
        return _Early_on!!
    }

private var _Early_on: ImageVector? = null

