package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Farsight_digital: ImageVector
    get() {
        if (_Farsight_digital != null) return _Farsight_digital!!
        
        _Farsight_digital = ImageVector.Builder(
            name = "farsight_digital",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(413f, 322f)
                verticalLineToRelative(120f)
                quadToRelative(0f, 6f, 4f, 10f)
                reflectiveQuadToRelative(10f, 4f)
                quadToRelative(6f, 0f, 10f, -4f)
                reflectiveQuadToRelative(4f, -10f)
                verticalLineToRelative(-148f)
                quadToRelative(0f, -5f, -2.5f, -7.5f)
                reflectiveQuadTo(431f, 284f)
                horizontalLineToRelative(-7f)
                quadToRelative(-2f, 0f, -6f, 2f)
                lineToRelative(-37f, 27f)
                quadToRelative(-5f, 3f, -5.5f, 7.5f)
                reflectiveQuadToRelative(2.5f, 9.5f)
                quadToRelative(3f, 5f, 8f, 6f)
                reflectiveQuadToRelative(10f, -2f)
                lineToRelative(17f, -12f)
                close()
                moveToRelative(118f, -16f)
                quadToRelative(12f, 0f, 20f, 6.5f)
                reflectiveQuadToRelative(8f, 16.5f)
                quadToRelative(0f, 11f, -5f, 21f)
                reflectiveQuadToRelative(-14f, 19f)
                lineToRelative(-59f, 58f)
                quadToRelative(-1f, 1f, -3f, 7f)
                verticalLineToRelative(9f)
                quadToRelative(0f, 5f, 4f, 9f)
                reflectiveQuadToRelative(9f, 4f)
                horizontalLineToRelative(87f)
                quadToRelative(5f, 0f, 8.5f, -4f)
                reflectiveQuadToRelative(3.5f, -9f)
                quadToRelative(0f, -5f, -3.5f, -8.5f)
                reflectiveQuadTo(578f, 431f)
                horizontalLineToRelative(-64f)
                verticalLineToRelative(-1f)
                lineToRelative(44f, -44f)
                quadToRelative(16f, -16f, 22.5f, -29f)
                reflectiveQuadToRelative(6.5f, -28f)
                quadToRelative(0f, -20f, -16f, -34.5f)
                reflectiveQuadTo(532f, 280f)
                quadToRelative(-16f, 0f, -29f, 7f)
                reflectiveQuadToRelative(-21f, 20f)
                quadToRelative(-3f, 5f, 0f, 10f)
                reflectiveQuadToRelative(8f, 7f)
                quadToRelative(5f, 2f, 9.5f, 0.5f)
                reflectiveQuadToRelative(7.5f, -6.5f)
                quadToRelative(5f, -6f, 11f, -9f)
                reflectiveQuadToRelative(13f, -3f)
                close()
                moveTo(408f, 680f)
                quadToRelative(26f, 0f, 43f, -14.5f)
                reflectiveQuadToRelative(17f, -37.5f)
                quadToRelative(0f, -14f, -8f, -25.5f)
                reflectiveQuadTo(439f, 586f)
                verticalLineToRelative(-2f)
                quadToRelative(11f, -5f, 17f, -15.5f)
                reflectiveQuadToRelative(6f, -22.5f)
                quadToRelative(0f, -20f, -15.5f, -33f)
                reflectiveQuadTo(407f, 500f)
                quadToRelative(-14f, 0f, -27f, 7f)
                reflectiveQuadToRelative(-21f, 18f)
                quadToRelative(-3f, 5f, 0f, 9.5f)
                reflectiveQuadToRelative(8f, 6.5f)
                quadToRelative(5f, 2f, 9.5f, 1f)
                reflectiveQuadToRelative(7.5f, -6f)
                quadToRelative(2f, -3f, 22f, -11f)
                quadToRelative(12f, 0f, 19.5f, 6f)
                reflectiveQuadToRelative(7.5f, 17f)
                quadToRelative(0f, 11f, -8.5f, 18f)
                reflectiveQuadToRelative(-20.5f, 7f)
                quadToRelative(-5f, 0f, -9f, 3.5f)
                reflectiveQuadToRelative(-4f, 8.5f)
                quadToRelative(0f, 5f, 3.5f, 9f)
                reflectiveQuadToRelative(8.5f, 4f)
                horizontalLineToRelative(3f)
                quadToRelative(14f, 0f, 23.5f, 8f)
                reflectiveQuadToRelative(9.5f, 20f)
                quadToRelative(0f, 11f, -9f, 19f)
                reflectiveQuadToRelative(-22f, 8f)
                quadToRelative(-8f, 0f, -15.5f, -4f)
                reflectiveQuadTo(380f, 637f)
                quadToRelative(-3f, -5f, -7.5f, -6.5f)
                reflectiveQuadToRelative(-9.5f, 0.5f)
                quadToRelative(-5f, 2f, -8f, 7.5f)
                reflectiveQuadToRelative(0f, 10.5f)
                quadToRelative(8f, 14f, 22f, 22.5f)
                reflectiveQuadToRelative(31f, 8.5f)
                close()
                moveToRelative(142f, 0f)
                quadToRelative(24f, 0f, 42f, -17.5f)
                reflectiveQuadToRelative(18f, -40.5f)
                quadToRelative(0f, -23f, -15.5f, -39.5f)
                reflectiveQuadTo(558f, 566f)
                quadToRelative(-5f, 0f, -18f, 4f)
                horizontalLineToRelative(-1f)
                lineToRelative(31f, -44f)
                quadToRelative(3f, -5f, 2.5f, -10.5f)
                reflectiveQuadTo(567f, 507f)
                quadToRelative(-5f, -3f, -10f, -2f)
                reflectiveQuadToRelative(-8f, 6f)
                lineToRelative(-36f, 53f)
                quadToRelative(-14f, 20f, -18.5f, 32f)
                reflectiveQuadToRelative(-4.5f, 25f)
                quadToRelative(0f, 25f, 17f, 42f)
                reflectiveQuadToRelative(43f, 17f)
                close()
                moveToRelative(0f, -26f)
                quadToRelative(-14f, 0f, -23f, -9f)
                reflectiveQuadToRelative(-9f, -23f)
                quadToRelative(0f, -8f, 4f, -15.5f)
                reflectiveQuadToRelative(12f, -12.5f)
                quadToRelative(3f, -2f, 16f, -4f)
                quadToRelative(13f, 0f, 22.5f, 9.5f)
                reflectiveQuadTo(582f, 623f)
                quadToRelative(0f, 13f, -9f, 22f)
                reflectiveQuadToRelative(-23f, 9f)
                close()
                moveTo(480f, 880f)
                quadToRelative(-83f, 0f, -156f, -31.5f)
                reflectiveQuadTo(197f, 763f)
                quadToRelative(-54f, -54f, -85.5f, -127f)
                reflectiveQuadTo(80f, 480f)
                quadToRelative(0f, -83f, 31.5f, -156f)
                reflectiveQuadTo(197f, 197f)
                quadToRelative(54f, -54f, 127f, -85.5f)
                reflectiveQuadTo(480f, 80f)
                quadToRelative(83f, 0f, 156f, 31.5f)
                reflectiveQuadTo(763f, 197f)
                quadToRelative(54f, 54f, 85.5f, 127f)
                reflectiveQuadTo(880f, 480f)
                quadToRelative(0f, 83f, -31.5f, 156f)
                reflectiveQuadTo(763f, 763f)
                quadToRelative(-54f, 54f, -127f, 85.5f)
                reflectiveQuadTo(480f, 880f)
                close()
                moveToRelative(0f, -80f)
                quadToRelative(133f, 0f, 226.5f, -93.5f)
                reflectiveQuadTo(800f, 480f)
                quadToRelative(0f, -133f, -93.5f, -226.5f)
                reflectiveQuadTo(480f, 160f)
                quadToRelative(-133f, 0f, -226.5f, 93.5f)
                reflectiveQuadTo(160f, 480f)
                quadToRelative(0f, 133f, 93.5f, 226.5f)
                reflectiveQuadTo(480f, 800f)
                close()
                moveToRelative(0f, -320f)
                close()
            }
        }.build()
        
        return _Farsight_digital!!
    }

private var _Farsight_digital: ImageVector? = null

