package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Hdr_plus_off: ImageVector
    get() {
        if (_Hdr_plus_off != null) return _Hdr_plus_off!!
        
        _Hdr_plus_off = ImageVector.Builder(
            name = "hdr_plus_off",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(480f, 160f)
                quadToRelative(-34f, 0f, -66f, 6.5f)
                reflectiveQuadTo(353f, 185f)
                quadToRelative(-16f, 7f, -32f, 2f)
                reflectiveQuadToRelative(-24f, -19f)
                quadToRelative(-8f, -14f, -3.5f, -30f)
                reflectiveQuadToRelative(19.5f, -23f)
                quadToRelative(39f, -18f, 81.5f, -26.5f)
                reflectiveQuadTo(480f, 80f)
                quadToRelative(83f, 0f, 156f, 31.5f)
                reflectiveQuadTo(763f, 197f)
                quadToRelative(54f, 54f, 85.5f, 127f)
                reflectiveQuadTo(880f, 480f)
                quadToRelative(0f, 45f, -9.5f, 87.5f)
                reflectiveQuadTo(844f, 648f)
                quadToRelative(-7f, 15f, -23f, 19f)
                reflectiveQuadToRelative(-30f, -4f)
                quadToRelative(-14f, -8f, -19f, -24f)
                reflectiveQuadToRelative(2f, -32f)
                quadToRelative(13f, -29f, 19.5f, -61f)
                reflectiveQuadToRelative(6.5f, -66f)
                quadToRelative(0f, -134f, -93f, -227f)
                reflectiveQuadToRelative(-227f, -93f)
                close()
                moveToRelative(0f, 207f)
                lineToRelative(-60f, -60f)
                verticalLineToRelative(-37f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(450f, 240f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(480f, 270f)
                verticalLineToRelative(97f)
                close()
                moveToRelative(220f, -67f)
                verticalLineToRelative(120f)
                quadToRelative(0f, 24f, -18f, 42f)
                reflectiveQuadToRelative(-42f, 18f)
                horizontalLineToRelative(-47f)
                lineToRelative(-73f, -73f)
                verticalLineToRelative(-137f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(550f, 240f)
                horizontalLineToRelative(90f)
                quadToRelative(24f, 0f, 42f, 18f)
                reflectiveQuadToRelative(18f, 42f)
                close()
                moveTo(580f, 420f)
                horizontalLineToRelative(60f)
                verticalLineToRelative(-120f)
                horizontalLineToRelative(-60f)
                verticalLineToRelative(120f)
                close()
                moveTo(420f, 620f)
                verticalLineToRelative(-40f)
                horizontalLineToRelative(-80f)
                verticalLineToRelative(40f)
                horizontalLineToRelative(80f)
                close()
                moveToRelative(117f, -197f)
                close()
                moveTo(340f, 680f)
                verticalLineToRelative(50f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(310f, 760f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(280f, 730f)
                verticalLineToRelative(-180f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(310f, 520f)
                horizontalLineToRelative(110f)
                quadToRelative(25f, 0f, 42.5f, 17.5f)
                reflectiveQuadTo(480f, 580f)
                verticalLineToRelative(40f)
                quadToRelative(0f, 18f, -10.5f, 32.5f)
                reflectiveQuadTo(444f, 676f)
                lineToRelative(19f, 44f)
                quadToRelative(6f, 14f, -2.5f, 27f)
                reflectiveQuadTo(437f, 760f)
                quadToRelative(-8f, 0f, -15.5f, -4.5f)
                reflectiveQuadTo(411f, 743f)
                lineToRelative(-27f, -63f)
                horizontalLineToRelative(-44f)
                close()
                moveToRelative(-60f, -344f)
                lineToRelative(60f, 60f)
                verticalLineToRelative(54f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(310f, 480f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(280f, 450f)
                verticalLineToRelative(-114f)
                close()
                moveToRelative(143f, 201f)
                close()
                moveTo(171f, 227f)
                lineToRelative(56f, 57f)
                quadToRelative(-32f, 42f, -49.5f, 90.5f)
                reflectiveQuadTo(160f, 480f)
                quadToRelative(0f, 134f, 93f, 227f)
                reflectiveQuadToRelative(227f, 93f)
                quadToRelative(57f, 0f, 106f, -17.5f)
                reflectiveQuadToRelative(91f, -49.5f)
                lineToRelative(56f, 56f)
                quadToRelative(-51f, 44f, -115.5f, 67.5f)
                reflectiveQuadTo(480f, 880f)
                quadToRelative(-83f, 0f, -156f, -31.5f)
                reflectiveQuadTo(197f, 763f)
                quadToRelative(-54f, -54f, -85.5f, -127f)
                reflectiveQuadTo(80f, 480f)
                quadToRelative(0f, -73f, 24f, -137.5f)
                reflectiveQuadTo(171f, 227f)
                close()
                moveTo(848f, 904f)
                quadToRelative(-11f, 11f, -28f, 11f)
                reflectiveQuadToRelative(-28f, -11f)
                lineTo(56f, 168f)
                quadToRelative(-11f, -11f, -11f, -28f)
                reflectiveQuadToRelative(11f, -28f)
                quadToRelative(11f, -11f, 28f, -11f)
                reflectiveQuadToRelative(28f, 11f)
                lineToRelative(736f, 736f)
                quadToRelative(11f, 11f, 11f, 28f)
                reflectiveQuadToRelative(-11f, 28f)
                close()
            }
        }.build()
        
        return _Hdr_plus_off!!
    }

private var _Hdr_plus_off: ImageVector? = null

