package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Hdr_off_select: ImageVector
    get() {
        if (_Hdr_off_select != null) return _Hdr_off_select!!
        
        _Hdr_off_select = ImageVector.Builder(
            name = "hdr_off_select",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(820f, 800f)
                horizontalLineToRelative(-50f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(740f, 770f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(770f, 740f)
                horizontalLineToRelative(50f)
                verticalLineToRelative(-50f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(850f, 660f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(880f, 690f)
                verticalLineToRelative(50f)
                horizontalLineToRelative(50f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(960f, 770f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(930f, 800f)
                horizontalLineToRelative(-50f)
                verticalLineToRelative(50f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(850f, 880f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(820f, 850f)
                verticalLineToRelative(-50f)
                close()
                moveToRelative(-300f, 50f)
                verticalLineToRelative(-180f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(550f, 640f)
                horizontalLineToRelative(110f)
                quadToRelative(24f, 0f, 42f, 18f)
                reflectiveQuadToRelative(18f, 42f)
                verticalLineToRelative(40f)
                quadToRelative(0f, 23f, -10.5f, 35.5f)
                reflectiveQuadTo(684f, 796f)
                lineToRelative(20f, 46f)
                quadToRelative(6f, 14f, -2f, 26f)
                reflectiveQuadToRelative(-24f, 12f)
                quadToRelative(-8f, 0f, -15f, -4f)
                reflectiveQuadToRelative(-10f, -12f)
                lineToRelative(-29f, -64f)
                horizontalLineToRelative(-44f)
                verticalLineToRelative(50f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(550f, 880f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(520f, 850f)
                close()
                moveToRelative(60f, -110f)
                horizontalLineToRelative(80f)
                verticalLineToRelative(-40f)
                horizontalLineToRelative(-80f)
                verticalLineToRelative(40f)
                close()
                moveTo(60f, 780f)
                verticalLineToRelative(70f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(30f, 880f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(0f, 850f)
                verticalLineToRelative(-180f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(30f, 640f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(60f, 670f)
                verticalLineToRelative(50f)
                horizontalLineToRelative(80f)
                verticalLineToRelative(-50f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(170f, 640f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(200f, 670f)
                verticalLineToRelative(180f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(170f, 880f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(140f, 850f)
                verticalLineToRelative(-70f)
                horizontalLineTo(60f)
                close()
                moveToRelative(200f, 70f)
                verticalLineToRelative(-180f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(290f, 640f)
                horizontalLineToRelative(110f)
                quadToRelative(24f, 0f, 42f, 18f)
                reflectiveQuadToRelative(18f, 42f)
                verticalLineToRelative(120f)
                quadToRelative(0f, 24f, -18f, 42f)
                reflectiveQuadToRelative(-42f, 18f)
                horizontalLineTo(290f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(260f, 850f)
                close()
                moveToRelative(60f, -30f)
                horizontalLineToRelative(80f)
                verticalLineToRelative(-120f)
                horizontalLineToRelative(-80f)
                verticalLineToRelative(120f)
                close()
                moveToRelative(376f, -396f)
                lineToRelative(-62f, -62f)
                quadToRelative(2f, -11f, 4f, -21f)
                reflectiveQuadToRelative(2f, -21f)
                quadToRelative(0f, -66f, -47f, -113f)
                reflectiveQuadToRelative(-113f, -47f)
                quadToRelative(-11f, 0f, -21f, 1.5f)
                reflectiveQuadToRelative(-19f, 4.5f)
                lineToRelative(-64f, -64f)
                quadToRelative(26f, -12f, 52f, -17f)
                reflectiveQuadToRelative(52f, -5f)
                quadToRelative(100f, 0f, 170f, 70f)
                reflectiveQuadToRelative(70f, 170f)
                quadToRelative(0f, 26f, -6f, 52f)
                reflectiveQuadToRelative(-18f, 52f)
                close()
                moveTo(480f, 560f)
                quadToRelative(-100f, 0f, -170f, -70f)
                reflectiveQuadToRelative(-70f, -170f)
                quadToRelative(0f, -29f, 6f, -55f)
                reflectiveQuadToRelative(18f, -49f)
                lineToRelative(-38f, -38f)
                quadToRelative(-11f, -11f, -11f, -28f)
                reflectiveQuadToRelative(11f, -28f)
                quadToRelative(11f, -11f, 28f, -11f)
                reflectiveQuadToRelative(28f, 11f)
                lineToRelative(396f, 396f)
                quadToRelative(11f, 11f, 11f, 28f)
                reflectiveQuadToRelative(-11f, 28f)
                quadToRelative(-11f, 11f, -28f, 11f)
                reflectiveQuadToRelative(-28f, -11f)
                lineToRelative(-38f, -38f)
                quadToRelative(-23f, 12f, -50.5f, 18f)
                reflectiveQuadToRelative(-53.5f, 6f)
                close()
                moveToRelative(42f, -86f)
                lineTo(326f, 278f)
                quadToRelative(-3f, 8f, -4.5f, 19.5f)
                reflectiveQuadTo(320f, 320f)
                quadToRelative(0f, 66f, 47f, 113f)
                reflectiveQuadToRelative(113f, 47f)
                quadToRelative(11f, 0f, 22.5f, -1.5f)
                reflectiveQuadTo(522f, 474f)
                close()
                moveToRelative(15f, -210f)
                close()
                moveTo(424f, 376f)
                close()
            }
        }.build()
        
        return _Hdr_off_select!!
    }

private var _Hdr_off_select: ImageVector? = null

