package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Language_chinese_quick: ImageVector
    get() {
        if (_Language_chinese_quick != null) return _Language_chinese_quick!!
        
        _Language_chinese_quick = ImageVector.Builder(
            name = "language_chinese_quick",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(86f, 680f)
                quadToRelative(-5f, -8f, -3f, -18f)
                reflectiveQuadToRelative(11f, -16f)
                quadToRelative(14f, -10f, 27f, -20.5f)
                reflectiveQuadToRelative(27f, -21.5f)
                verticalLineToRelative(-115f)
                horizontalLineToRelative(-45f)
                quadToRelative(-9f, 0f, -15.5f, -6.5f)
                reflectiveQuadTo(81f, 467f)
                quadToRelative(0f, -9f, 6.5f, -15.5f)
                reflectiveQuadTo(103f, 445f)
                horizontalLineToRelative(71f)
                quadToRelative(8f, 0f, 14f, 6f)
                reflectiveQuadToRelative(6f, 14f)
                verticalLineToRelative(136f)
                quadToRelative(20f, 25f, 50f, 38f)
                reflectiveQuadToRelative(62f, 13f)
                quadToRelative(50f, 0f, 99f, -1f)
                reflectiveQuadToRelative(99f, -3f)
                quadToRelative(10f, -1f, 14.5f, 5.5f)
                reflectiveQuadTo(520f, 670f)
                quadToRelative(-3f, 10f, -10.5f, 17.5f)
                reflectiveQuadTo(488f, 695f)
                quadToRelative(-46f, 0f, -91f, -0.5f)
                reflectiveQuadToRelative(-91f, -0.5f)
                quadToRelative(-38f, 0f, -74f, -13f)
                reflectiveQuadToRelative(-62f, -41f)
                quadToRelative(-12f, 12f, -25f, 24f)
                reflectiveQuadToRelative(-27f, 23f)
                quadToRelative(-8f, 7f, -17.5f, 4.5f)
                reflectiveQuadTo(86f, 680f)
                close()
                moveToRelative(384f, -62f)
                quadToRelative(-26f, -16f, -47.5f, -36f)
                reflectiveQuadTo(381f, 539f)
                verticalLineToRelative(83f)
                quadToRelative(0f, 9f, -6.5f, 15.5f)
                reflectiveQuadTo(359f, 644f)
                quadToRelative(-9f, 0f, -16f, -7f)
                reflectiveQuadToRelative(-7f, -16f)
                verticalLineToRelative(-83f)
                quadToRelative(-18f, 24f, -41f, 43.5f)
                reflectiveQuadTo(247f, 618f)
                quadToRelative(-8f, 5f, -17.5f, 4f)
                reflectiveQuadToRelative(-16.5f, -9f)
                quadToRelative(-7f, -8f, -5f, -14.5f)
                reflectiveQuadToRelative(10f, -11.5f)
                quadToRelative(28f, -15f, 52f, -35f)
                reflectiveQuadToRelative(44f, -45f)
                horizontalLineToRelative(-64f)
                quadToRelative(-8f, 0f, -14f, -6f)
                reflectiveQuadToRelative(-6f, -14f)
                verticalLineToRelative(-89f)
                quadToRelative(0f, -8f, 6f, -14f)
                reflectiveQuadToRelative(14f, -6f)
                horizontalLineToRelative(87f)
                verticalLineToRelative(-30f)
                horizontalLineTo(230f)
                quadToRelative(-8f, 0f, -14f, -6.5f)
                reflectiveQuadToRelative(-6f, -14.5f)
                quadToRelative(0f, -8f, 6.5f, -14f)
                reflectiveQuadToRelative(14.5f, -6f)
                horizontalLineToRelative(106f)
                verticalLineToRelative(-26f)
                quadToRelative(0f, -9f, 6.5f, -15.5f)
                reflectiveQuadTo(359f, 259f)
                quadToRelative(9f, 0f, 15.5f, 6.5f)
                reflectiveQuadTo(381f, 281f)
                verticalLineToRelative(26f)
                horizontalLineToRelative(116f)
                quadToRelative(8f, 0f, 14f, 6f)
                reflectiveQuadToRelative(6f, 14f)
                quadToRelative(0f, 8f, -6f, 14.5f)
                reflectiveQuadToRelative(-14f, 6.5f)
                horizontalLineTo(381f)
                verticalLineToRelative(30f)
                horizontalLineToRelative(93f)
                quadToRelative(8f, 0f, 14f, 6f)
                reflectiveQuadToRelative(6f, 14f)
                verticalLineToRelative(88f)
                quadToRelative(0f, 8f, -6f, 14f)
                reflectiveQuadToRelative(-14f, 6f)
                horizontalLineToRelative(-71f)
                quadToRelative(21f, 24f, 45.5f, 44f)
                reflectiveQuadToRelative(52.5f, 34f)
                quadToRelative(9f, 5f, 10f, 11.5f)
                reflectiveQuadToRelative(-6f, 14.5f)
                quadToRelative(-8f, 8f, -17.5f, 10.5f)
                reflectiveQuadTo(470f, 618f)
                close()
                moveTo(275f, 468f)
                horizontalLineToRelative(61f)
                verticalLineToRelative(-51f)
                horizontalLineToRelative(-61f)
                verticalLineToRelative(51f)
                close()
                moveToRelative(105f, 0f)
                horizontalLineToRelative(70f)
                verticalLineToRelative(-51f)
                horizontalLineToRelative(-70f)
                verticalLineToRelative(51f)
                close()
                moveTo(158f, 361f)
                quadToRelative(-12f, -15f, -26f, -27.5f)
                reflectiveQuadTo(102f, 310f)
                quadToRelative(-8f, -5f, -8.5f, -13f)
                reflectiveQuadToRelative(6.5f, -14f)
                quadToRelative(8f, -6f, 18f, -6f)
                reflectiveQuadToRelative(17f, 5f)
                quadToRelative(15f, 12f, 28.5f, 24.5f)
                reflectiveQuadTo(191f, 333f)
                quadToRelative(7f, 7f, 7f, 16.5f)
                reflectiveQuadToRelative(-8f, 15.5f)
                quadToRelative(-8f, 6f, -17f, 5f)
                reflectiveQuadToRelative(-15f, -9f)
                close()
                moveToRelative(544f, 265f)
                quadToRelative(28f, 0f, 54.5f, -13f)
                reflectiveQuadToRelative(48.5f, -37f)
                verticalLineToRelative(-106f)
                quadToRelative(-23f, 3f, -42.5f, 7f)
                reflectiveQuadToRelative(-36.5f, 9f)
                quadToRelative(-45f, 14f, -67.5f, 35f)
                reflectiveQuadTo(636f, 570f)
                quadToRelative(0f, 26f, 18f, 41f)
                reflectiveQuadToRelative(48f, 15f)
                close()
                moveToRelative(-23f, 68f)
                quadToRelative(-57f, 0f, -90f, -32.5f)
                reflectiveQuadTo(556f, 573f)
                quadToRelative(0f, -52f, 33f, -85f)
                reflectiveQuadToRelative(106f, -53f)
                quadToRelative(23f, -6f, 50.5f, -11f)
                reflectiveQuadToRelative(59.5f, -9f)
                quadToRelative(-2f, -47f, -22f, -68.5f)
                reflectiveQuadTo(721f, 325f)
                quadToRelative(-21f, 0f, -41f, 6f)
                reflectiveQuadToRelative(-47f, 20f)
                quadToRelative(-12f, 7f, -25f, 4f)
                reflectiveQuadToRelative(-20f, -15f)
                quadToRelative(-7f, -12f, -3f, -25.5f)
                reflectiveQuadToRelative(16f, -20.5f)
                quadToRelative(31f, -17f, 66.5f, -27.5f)
                reflectiveQuadTo(740f, 256f)
                quadToRelative(71f, 0f, 108f, 44f)
                reflectiveQuadToRelative(37f, 128f)
                verticalLineToRelative(224f)
                quadToRelative(0f, 14f, -9.5f, 23.5f)
                reflectiveQuadTo(852f, 685f)
                horizontalLineToRelative(-5f)
                quadToRelative(-13f, 0f, -22f, -8.5f)
                reflectiveQuadTo(814f, 656f)
                lineToRelative(-2f, -16f)
                quadToRelative(-28f, 25f, -61.5f, 39.5f)
                reflectiveQuadTo(679f, 694f)
                close()
            }
        }.build()
        
        return _Language_chinese_quick!!
    }

private var _Language_chinese_quick: ImageVector? = null

