package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Language_pinyin: ImageVector
    get() {
        if (_Language_pinyin != null) return _Language_pinyin!!
        
        _Language_pinyin = ImageVector.Builder(
            name = "language_pinyin",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(640f, 360f)
                horizontalLineToRelative(-80f)
                verticalLineToRelative(120f)
                horizontalLineToRelative(80f)
                verticalLineToRelative(-120f)
                close()
                moveTo(280f, 160f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(320f, 200f)
                verticalLineToRelative(80f)
                horizontalLineToRelative(20f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(380f, 320f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(340f, 360f)
                horizontalLineToRelative(-20f)
                verticalLineToRelative(96f)
                quadToRelative(7f, -5f, 13.5f, -8.5f)
                reflectiveQuadTo(347f, 439f)
                quadToRelative(9f, -6f, 19f, 1f)
                reflectiveQuadToRelative(10f, 20f)
                quadToRelative(0f, 18f, -6.5f, 34f)
                reflectiveQuadTo(348f, 520f)
                quadToRelative(-7f, 5f, -13.5f, 9f)
                reflectiveQuadToRelative(-14.5f, 8f)
                verticalLineToRelative(203f)
                quadToRelative(0f, 23f, -18.5f, 41.5f)
                reflectiveQuadTo(260f, 800f)
                horizontalLineToRelative(-49f)
                quadToRelative(-14f, 0f, -25f, -8f)
                reflectiveQuadToRelative(-14f, -22f)
                quadToRelative(-5f, -19f, 7f, -34.5f)
                reflectiveQuadToRelative(32f, -15.5f)
                horizontalLineToRelative(9f)
                quadToRelative(8f, 0f, 14f, -6f)
                reflectiveQuadToRelative(6f, -14f)
                verticalLineToRelative(-125f)
                quadToRelative(-7f, 3f, -13f, 6f)
                reflectiveQuadToRelative(-13f, 5f)
                quadToRelative(-15f, 6f, -29f, -1.5f)
                reflectiveQuadTo(168f, 561f)
                quadToRelative(-3f, -17f, 6f, -31f)
                reflectiveQuadToRelative(25f, -19f)
                quadToRelative(11f, -4f, 21f, -7.5f)
                reflectiveQuadToRelative(20f, -7.5f)
                verticalLineToRelative(-136f)
                horizontalLineToRelative(-20f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(180f, 320f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(220f, 280f)
                horizontalLineToRelative(20f)
                verticalLineToRelative(-80f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(280f, 160f)
                close()
                moveToRelative(376f, 135f)
                quadToRelative(-14f, -6f, -18.5f, -21f)
                reflectiveQuadToRelative(3.5f, -29f)
                quadToRelative(8f, -12f, 15f, -24.5f)
                reflectiveQuadToRelative(14f, -24.5f)
                quadToRelative(8f, -15f, 23.5f, -21.5f)
                reflectiveQuadToRelative(31.5f, -0.5f)
                quadToRelative(15f, 5f, 20.5f, 19.5f)
                reflectiveQuadTo(743f, 222f)
                quadToRelative(-8f, 14f, -16f, 27f)
                reflectiveQuadToRelative(-16f, 27f)
                quadToRelative(-9f, 14f, -24.5f, 20f)
                reflectiveQuadToRelative(-30.5f, -1f)
                close()
                moveToRelative(-122f, -11f)
                quadToRelative(-14f, 8f, -30f, 4f)
                reflectiveQuadToRelative(-26f, -18f)
                quadToRelative(-8f, -11f, -16.5f, -22f)
                reflectiveQuadTo(445f, 226f)
                quadToRelative(-10f, -12f, -6.5f, -27f)
                reflectiveQuadToRelative(17.5f, -22f)
                quadToRelative(16f, -8f, 32.5f, -3.5f)
                reflectiveQuadTo(516f, 192f)
                quadToRelative(8f, 10f, 15f, 20f)
                lineToRelative(14f, 20f)
                quadToRelative(9f, 13f, 6f, 28.5f)
                reflectiveQuadTo(534f, 284f)
                close()
                moveTo(384f, 800f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(344f, 760f)
                quadToRelative(0f, -11f, 5f, -19.5f)
                reflectiveQuadToRelative(13f, -13.5f)
                quadToRelative(42f, -28f, 71f, -73f)
                reflectiveQuadToRelative(40f, -94f)
                horizontalLineToRelative(-33f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(400f, 520f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(440f, 480f)
                horizontalLineToRelative(40f)
                verticalLineToRelative(-120f)
                horizontalLineToRelative(-20f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(420f, 320f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(460f, 280f)
                horizontalLineToRelative(280f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(780f, 320f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(740f, 360f)
                horizontalLineToRelative(-20f)
                verticalLineToRelative(120f)
                horizontalLineToRelative(40f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(800f, 520f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(760f, 560f)
                horizontalLineToRelative(-40f)
                verticalLineToRelative(200f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(680f, 800f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(640f, 760f)
                verticalLineToRelative(-200f)
                horizontalLineToRelative(-86f)
                quadToRelative(-13f, 68f, -52f, 131.5f)
                reflectiveQuadTo(406f, 793f)
                quadToRelative(-5f, 3f, -10.5f, 5f)
                reflectiveQuadToRelative(-11.5f, 2f)
                close()
            }
        }.build()
        
        return _Language_pinyin!!
    }

private var _Language_pinyin: ImageVector? = null

