package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Language_chinese_pinyin: ImageVector
    get() {
        if (_Language_chinese_pinyin != null) return _Language_chinese_pinyin!!
        
        _Language_chinese_pinyin = ImageVector.Builder(
            name = "language_chinese_pinyin",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(340f, 492f)
                horizontalLineToRelative(56f)
                verticalLineToRelative(-82f)
                horizontalLineToRelative(-56f)
                verticalLineToRelative(82f)
                close()
                moveTo(142f, 700f)
                horizontalLineToRelative(-26f)
                quadToRelative(-7f, 0f, -12.5f, -4f)
                reflectiveQuadTo(96f, 685f)
                quadToRelative(-5f, -11f, 2f, -20.5f)
                reflectiveQuadToRelative(19f, -9.5f)
                horizontalLineToRelative(6f)
                quadToRelative(5f, 0f, 9.5f, -3.5f)
                reflectiveQuadToRelative(4.5f, -8.5f)
                verticalLineToRelative(-101f)
                lineToRelative(-30f, 10f)
                quadToRelative(-9f, 3f, -17.5f, -1.5f)
                reflectiveQuadTo(79f, 536f)
                quadToRelative(-2f, -9f, 2.5f, -17f)
                reflectiveQuadTo(95f, 509f)
                lineToRelative(42f, -13f)
                verticalLineToRelative(-90f)
                horizontalLineToRelative(-35f)
                quadToRelative(-9f, 0f, -15f, -6f)
                reflectiveQuadToRelative(-6f, -15f)
                quadToRelative(0f, -9f, 6f, -15f)
                reflectiveQuadToRelative(15f, -6f)
                horizontalLineToRelative(35f)
                verticalLineToRelative(-70f)
                quadToRelative(0f, -9f, 6.5f, -15.5f)
                reflectiveQuadTo(159f, 272f)
                quadToRelative(9f, 0f, 15.5f, 6.5f)
                reflectiveQuadTo(181f, 294f)
                verticalLineToRelative(70f)
                horizontalLineToRelative(24f)
                quadToRelative(9f, 0f, 15f, 6f)
                reflectiveQuadToRelative(6f, 15f)
                quadToRelative(0f, 9f, -6f, 15f)
                reflectiveQuadToRelative(-15f, 6f)
                horizontalLineToRelative(-25f)
                verticalLineToRelative(77f)
                lineToRelative(17f, -5f)
                quadToRelative(9f, -3f, 17f, 2f)
                reflectiveQuadToRelative(10f, 15f)
                quadToRelative(1f, 8f, -3f, 14.5f)
                reflectiveQuadToRelative(-11f, 8.5f)
                lineToRelative(-30f, 10f)
                verticalLineToRelative(125f)
                quadToRelative(0f, 18f, -10.5f, 32.5f)
                reflectiveQuadTo(142f, 700f)
                close()
                moveToRelative(194f, -164f)
                quadToRelative(-2f, 46f, -21.5f, 86f)
                reflectiveQuadTo(260f, 691f)
                quadToRelative(-8f, 7f, -18f, 7f)
                reflectiveQuadToRelative(-17f, -8f)
                quadToRelative(-6f, -7f, -4f, -15.5f)
                reflectiveQuadToRelative(9f, -14.5f)
                quadToRelative(28f, -23f, 44.5f, -55f)
                reflectiveQuadToRelative(17.5f, -69f)
                horizontalLineToRelative(-46f)
                quadToRelative(-9f, 0f, -15.5f, -7f)
                reflectiveQuadToRelative(-6.5f, -16f)
                quadToRelative(0f, -9f, 7f, -15.5f)
                reflectiveQuadToRelative(16f, -6.5f)
                horizontalLineToRelative(49f)
                verticalLineToRelative(-81f)
                horizontalLineToRelative(-34f)
                quadToRelative(-8f, 0f, -14f, -6.5f)
                reflectiveQuadToRelative(-6f, -14.5f)
                quadToRelative(0f, -8f, 6f, -14f)
                reflectiveQuadToRelative(14f, -6f)
                horizontalLineToRelative(211f)
                quadToRelative(9f, 0f, 15.5f, 6.5f)
                reflectiveQuadTo(495f, 391f)
                quadToRelative(0f, 9f, -6.5f, 15.5f)
                reflectiveQuadTo(473f, 413f)
                horizontalLineToRelative(-35f)
                verticalLineToRelative(83f)
                horizontalLineToRelative(49f)
                quadToRelative(8f, 0f, 14.5f, 6.5f)
                reflectiveQuadTo(507f, 517f)
                quadToRelative(-1f, 8f, -6.5f, 13.5f)
                reflectiveQuadTo(487f, 536f)
                horizontalLineToRelative(-49f)
                verticalLineToRelative(143f)
                quadToRelative(0f, 9f, -6.5f, 15.5f)
                reflectiveQuadTo(416f, 701f)
                quadToRelative(-9f, 0f, -15.5f, -6.5f)
                reflectiveQuadTo(394f, 679f)
                verticalLineToRelative(-143f)
                horizontalLineToRelative(-58f)
                close()
                moveToRelative(77f, -162f)
                quadToRelative(-8f, -2f, -12f, -9f)
                reflectiveQuadToRelative(0f, -15f)
                quadToRelative(6f, -14f, 12.5f, -28f)
                reflectiveQuadToRelative(11.5f, -28f)
                quadToRelative(4f, -9f, 13f, -13f)
                reflectiveQuadToRelative(18f, -1f)
                quadToRelative(9f, 3f, 13f, 12f)
                reflectiveQuadToRelative(-1f, 18f)
                quadToRelative(-6f, 13f, -12f, 25f)
                reflectiveQuadToRelative(-13f, 25f)
                quadToRelative(-4f, 8f, -13f, 12f)
                reflectiveQuadToRelative(-17f, 2f)
                close()
                moveToRelative(-110f, -17f)
                quadToRelative(-6f, -13f, -12f, -25f)
                reflectiveQuadToRelative(-13f, -24f)
                quadToRelative(-5f, -8f, -2.5f, -15.5f)
                reflectiveQuadTo(286f, 281f)
                quadToRelative(8f, -4f, 17.5f, -1f)
                reflectiveQuadToRelative(14.5f, 11f)
                quadToRelative(7f, 12f, 13f, 24f)
                reflectiveQuadToRelative(12f, 25f)
                quadToRelative(4f, 8f, 0.5f, 16f)
                reflectiveQuadTo(332f, 368f)
                quadToRelative(-8f, 4f, -16.5f, 0.5f)
                reflectiveQuadTo(303f, 357f)
                close()
                moveToRelative(399f, 269f)
                quadToRelative(28f, 0f, 54.5f, -13f)
                reflectiveQuadToRelative(48.5f, -37f)
                verticalLineToRelative(-106f)
                quadToRelative(-23f, 3f, -42.5f, 7f)
                reflectiveQuadToRelative(-36.5f, 9f)
                quadToRelative(-45f, 14f, -67.5f, 35f)
                reflectiveQuadTo(636f, 570f)
                quadToRelative(0f, 26f, 18f, 41f)
                reflectiveQuadToRelative(48f, 15f)
                close()
                moveToRelative(-23f, 68f)
                quadToRelative(-57f, 0f, -90f, -32.5f)
                reflectiveQuadTo(556f, 573f)
                quadToRelative(0f, -52f, 33f, -85f)
                reflectiveQuadToRelative(106f, -53f)
                quadToRelative(23f, -6f, 50.5f, -11f)
                reflectiveQuadToRelative(59.5f, -9f)
                quadToRelative(-2f, -47f, -22f, -68.5f)
                reflectiveQuadTo(721f, 325f)
                quadToRelative(-21f, 0f, -41f, 6f)
                reflectiveQuadToRelative(-47f, 20f)
                quadToRelative(-12f, 7f, -25f, 4f)
                reflectiveQuadToRelative(-20f, -15f)
                quadToRelative(-7f, -12f, -3f, -25.5f)
                reflectiveQuadToRelative(16f, -20.5f)
                quadToRelative(31f, -17f, 66.5f, -27.5f)
                reflectiveQuadTo(740f, 256f)
                quadToRelative(71f, 0f, 108f, 44f)
                reflectiveQuadToRelative(37f, 128f)
                verticalLineToRelative(224f)
                quadToRelative(0f, 14f, -9.5f, 23.5f)
                reflectiveQuadTo(852f, 685f)
                horizontalLineToRelative(-5f)
                quadToRelative(-13f, 0f, -22f, -8.5f)
                reflectiveQuadTo(814f, 656f)
                lineToRelative(-2f, -16f)
                quadToRelative(-28f, 25f, -61.5f, 39.5f)
                reflectiveQuadTo(679f, 694f)
                close()
            }
        }.build()
        
        return _Language_chinese_pinyin!!
    }

private var _Language_chinese_pinyin: ImageVector? = null

