package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Lte_plus_mobiledata_badge: ImageVector
    get() {
        if (_Lte_plus_mobiledata_badge != null) return _Lte_plus_mobiledata_badge!!
        
        _Lte_plus_mobiledata_badge = ImageVector.Builder(
            name = "lte_plus_mobiledata_badge",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(120f, 760f)
                verticalLineToRelative(-560f)
                verticalLineToRelative(560f)
                close()
                moveToRelative(0f, 80f)
                quadToRelative(-33f, 0f, -56.5f, -23.5f)
                reflectiveQuadTo(40f, 760f)
                verticalLineToRelative(-560f)
                quadToRelative(0f, -33f, 23.5f, -56.5f)
                reflectiveQuadTo(120f, 120f)
                horizontalLineToRelative(720f)
                quadToRelative(33f, 0f, 56.5f, 23.5f)
                reflectiveQuadTo(920f, 200f)
                verticalLineToRelative(80f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(880f, 320f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(840f, 280f)
                verticalLineToRelative(-80f)
                horizontalLineTo(120f)
                verticalLineToRelative(560f)
                horizontalLineToRelative(720f)
                verticalLineToRelative(-80f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(880f, 640f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(920f, 680f)
                verticalLineToRelative(80f)
                quadToRelative(0f, 33f, -23.5f, 56.5f)
                reflectiveQuadTo(840f, 840f)
                horizontalLineTo(120f)
                close()
                moveToRelative(160f, -200f)
                quadToRelative(17f, 0f, 28.5f, -11.5f)
                reflectiveQuadTo(320f, 600f)
                quadToRelative(0f, -17f, -11.5f, -28.5f)
                reflectiveQuadTo(280f, 560f)
                horizontalLineToRelative(-40f)
                verticalLineToRelative(-200f)
                quadToRelative(0f, -17f, -11.5f, -28.5f)
                reflectiveQuadTo(200f, 320f)
                quadToRelative(-17f, 0f, -28.5f, 11.5f)
                reflectiveQuadTo(160f, 360f)
                verticalLineToRelative(240f)
                quadToRelative(0f, 17f, 11.5f, 28.5f)
                reflectiveQuadTo(200f, 640f)
                horizontalLineToRelative(80f)
                close()
                moveToRelative(100f, -240f)
                verticalLineToRelative(200f)
                quadToRelative(0f, 17f, 11.5f, 28.5f)
                reflectiveQuadTo(420f, 640f)
                quadToRelative(17f, 0f, 28.5f, -11.5f)
                reflectiveQuadTo(460f, 600f)
                verticalLineToRelative(-200f)
                horizontalLineToRelative(20f)
                quadToRelative(17f, 0f, 28.5f, -11.5f)
                reflectiveQuadTo(520f, 360f)
                quadToRelative(0f, -17f, -11.5f, -28.5f)
                reflectiveQuadTo(480f, 320f)
                horizontalLineTo(360f)
                quadToRelative(-17f, 0f, -28.5f, 11.5f)
                reflectiveQuadTo(320f, 360f)
                quadToRelative(0f, 17f, 11.5f, 28.5f)
                reflectiveQuadTo(360f, 400f)
                horizontalLineToRelative(20f)
                close()
                moveToRelative(300f, 240f)
                quadToRelative(17f, 0f, 28.5f, -11.5f)
                reflectiveQuadTo(720f, 600f)
                quadToRelative(0f, -17f, -11.5f, -28.5f)
                reflectiveQuadTo(680f, 560f)
                horizontalLineToRelative(-40f)
                verticalLineToRelative(-40f)
                horizontalLineToRelative(20f)
                quadToRelative(17f, 0f, 28.5f, -11.5f)
                reflectiveQuadTo(700f, 480f)
                quadToRelative(0f, -17f, -11.5f, -28.5f)
                reflectiveQuadTo(660f, 440f)
                horizontalLineToRelative(-20f)
                verticalLineToRelative(-40f)
                horizontalLineToRelative(40f)
                quadToRelative(17f, 0f, 28.5f, -11.5f)
                reflectiveQuadTo(720f, 360f)
                quadToRelative(0f, -17f, -11.5f, -28.5f)
                reflectiveQuadTo(680f, 320f)
                horizontalLineToRelative(-80f)
                quadToRelative(-17f, 0f, -28.5f, 11.5f)
                reflectiveQuadTo(560f, 360f)
                verticalLineToRelative(240f)
                quadToRelative(0f, 17f, 11.5f, 28.5f)
                reflectiveQuadTo(600f, 640f)
                horizontalLineToRelative(80f)
                close()
                moveToRelative(130f, -130f)
                verticalLineToRelative(20f)
                quadToRelative(0f, 13f, 8.5f, 21.5f)
                reflectiveQuadTo(840f, 560f)
                quadToRelative(13f, 0f, 21.5f, -8.5f)
                reflectiveQuadTo(870f, 530f)
                verticalLineToRelative(-20f)
                horizontalLineToRelative(20f)
                quadToRelative(13f, 0f, 21.5f, -8.5f)
                reflectiveQuadTo(920f, 480f)
                quadToRelative(0f, -13f, -8.5f, -21.5f)
                reflectiveQuadTo(890f, 450f)
                horizontalLineToRelative(-20f)
                verticalLineToRelative(-20f)
                quadToRelative(0f, -13f, -8.5f, -21.5f)
                reflectiveQuadTo(840f, 400f)
                quadToRelative(-13f, 0f, -21.5f, 8.5f)
                reflectiveQuadTo(810f, 430f)
                verticalLineToRelative(20f)
                horizontalLineToRelative(-20f)
                quadToRelative(-13f, 0f, -21.5f, 8.5f)
                reflectiveQuadTo(760f, 480f)
                quadToRelative(0f, 13f, 8.5f, 21.5f)
                reflectiveQuadTo(790f, 510f)
                horizontalLineToRelative(20f)
                close()
            }
        }.build()
        
        return _Lte_plus_mobiledata_badge!!
    }

private var _Lte_plus_mobiledata_badge: ImageVector? = null

