package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Network_intelligence_history: ImageVector
    get() {
        if (_Network_intelligence_history != null) return _Network_intelligence_history!!
        
        _Network_intelligence_history = ImageVector.Builder(
            name = "network_intelligence_history",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(740f, 712f)
                verticalLineToRelative(-92f)
                quadToRelative(0f, -8f, -6f, -14f)
                reflectiveQuadToRelative(-14f, -6f)
                quadToRelative(-8f, 0f, -14f, 6f)
                reflectiveQuadToRelative(-6f, 14f)
                verticalLineToRelative(91f)
                quadToRelative(0f, 8f, 3f, 15.5f)
                reflectiveQuadToRelative(9f, 13.5f)
                lineToRelative(60f, 60f)
                quadToRelative(6f, 6f, 14f, 6f)
                reflectiveQuadToRelative(14f, -6f)
                quadToRelative(6f, -6f, 6f, -14f)
                reflectiveQuadToRelative(-6f, -14f)
                lineToRelative(-60f, -60f)
                close()
                moveTo(500f, 360f)
                verticalLineToRelative(-160f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(540f, 160f)
                horizontalLineToRelative(97f)
                quadToRelative(11f, 0f, 20.5f, 5.5f)
                reflectiveQuadTo(672f, 181f)
                lineToRelative(78f, 139f)
                horizontalLineToRelative(-58f)
                lineToRelative(-29f, -58f)
                quadToRelative(-5f, -11f, -15f, -16.5f)
                reflectiveQuadToRelative(-21f, -5.5f)
                horizontalLineToRelative(-47f)
                quadToRelative(-8f, 0f, -14f, 6f)
                reflectiveQuadToRelative(-6f, 14f)
                quadToRelative(0f, 8f, 6f, 14f)
                reflectiveQuadToRelative(14f, 6f)
                horizontalLineToRelative(48f)
                lineToRelative(29f, 58f)
                quadToRelative(5f, 11f, 15f, 16.5f)
                reflectiveQuadToRelative(21f, 5.5f)
                horizontalLineToRelative(79f)
                lineToRelative(15f, 26f)
                quadToRelative(12f, 20f, -2.5f, 39.5f)
                reflectiveQuadTo(745f, 441f)
                quadToRelative(-6f, -1f, -12.5f, -1f)
                horizontalLineTo(720f)
                quadToRelative(-50f, 0f, -94.5f, 16f)
                reflectiveQuadTo(545f, 501f)
                quadToRelative(-14f, 11f, -29.5f, 5f)
                reflectiveQuadTo(500f, 483f)
                verticalLineToRelative(-83f)
                horizontalLineToRelative(60f)
                quadToRelative(8f, 0f, 14f, -6f)
                reflectiveQuadToRelative(6f, -14f)
                quadToRelative(0f, -8f, -6f, -14f)
                reflectiveQuadToRelative(-14f, -6f)
                horizontalLineToRelative(-60f)
                close()
                moveToRelative(-80f, 440f)
                horizontalLineToRelative(-97f)
                quadToRelative(-11f, 0f, -20.5f, -5.5f)
                reflectiveQuadTo(288f, 779f)
                lineToRelative(-78f, -139f)
                horizontalLineToRelative(58f)
                lineToRelative(29f, 58f)
                quadToRelative(5f, 11f, 15f, 16.5f)
                reflectiveQuadToRelative(21f, 5.5f)
                horizontalLineToRelative(47f)
                quadToRelative(8f, 0f, 14f, -6f)
                reflectiveQuadToRelative(6f, -14f)
                quadToRelative(0f, -8f, -6f, -14f)
                reflectiveQuadToRelative(-14f, -6f)
                horizontalLineToRelative(-48f)
                lineToRelative(-29f, -58f)
                quadToRelative(-5f, -11f, -15f, -16.5f)
                reflectiveQuadToRelative(-21f, -5.5f)
                horizontalLineToRelative(-79f)
                lineToRelative(-57f, -100f)
                quadToRelative(-2f, -5f, -3.5f, -10f)
                reflectiveQuadToRelative(-1.5f, -10f)
                quadToRelative(0f, -4f, 5f, -20f)
                lineToRelative(57f, -100f)
                horizontalLineToRelative(79f)
                quadToRelative(11f, 0f, 21f, -5.5f)
                reflectiveQuadToRelative(15f, -16.5f)
                lineToRelative(29f, -58f)
                horizontalLineToRelative(48f)
                quadToRelative(8f, 0f, 14f, -6f)
                reflectiveQuadToRelative(6f, -14f)
                quadToRelative(0f, -8f, -6f, -14f)
                reflectiveQuadToRelative(-14f, -6f)
                horizontalLineToRelative(-47f)
                quadToRelative(-11f, 0f, -21f, 5.5f)
                reflectiveQuadTo(297f, 262f)
                lineToRelative(-29f, 58f)
                horizontalLineToRelative(-58f)
                lineToRelative(78f, -139f)
                quadToRelative(5f, -10f, 14.5f, -15.5f)
                reflectiveQuadTo(323f, 160f)
                horizontalLineToRelative(97f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(460f, 200f)
                verticalLineToRelative(160f)
                horizontalLineToRelative(-60f)
                quadToRelative(-8f, 0f, -14f, 6f)
                reflectiveQuadToRelative(-6f, 14f)
                quadToRelative(0f, 8f, 6f, 14f)
                reflectiveQuadToRelative(14f, 6f)
                horizontalLineToRelative(60f)
                verticalLineToRelative(120f)
                horizontalLineToRelative(-88f)
                lineToRelative(-29f, -58f)
                quadToRelative(-5f, -11f, -15f, -16.5f)
                reflectiveQuadToRelative(-21f, -5.5f)
                horizontalLineToRelative(-67f)
                quadToRelative(-8f, 0f, -14f, 6f)
                reflectiveQuadToRelative(-6f, 14f)
                quadToRelative(0f, 8f, 6f, 14f)
                reflectiveQuadToRelative(14f, 6f)
                horizontalLineToRelative(68f)
                lineToRelative(29f, 58f)
                quadToRelative(5f, 11f, 15f, 16.5f)
                reflectiveQuadToRelative(21f, 5.5f)
                horizontalLineToRelative(87f)
                verticalLineToRelative(56f)
                quadToRelative(-10f, 24f, -15f, 50f)
                reflectiveQuadToRelative(-5f, 54f)
                quadToRelative(0f, 17f, 1.5f, 34f)
                reflectiveQuadToRelative(6.5f, 34f)
                quadToRelative(-5f, 5f, -12.5f, 8.5f)
                reflectiveQuadTo(420f, 800f)
                close()
                moveTo(720f, 920f)
                quadToRelative(-83f, 0f, -141.5f, -58.5f)
                reflectiveQuadTo(520f, 720f)
                quadToRelative(0f, -83f, 58.5f, -141.5f)
                reflectiveQuadTo(720f, 520f)
                quadToRelative(83f, 0f, 141.5f, 58.5f)
                reflectiveQuadTo(920f, 720f)
                quadToRelative(0f, 83f, -58.5f, 141.5f)
                reflectiveQuadTo(720f, 920f)
                close()
            }
        }.build()
        
        return _Network_intelligence_history!!
    }

private var _Network_intelligence_history: ImageVector? = null

