package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Password: ImageVector
    get() {
        if (_Password != null) return _Password!!
        
        _Password = ImageVector.Builder(
            name = "password",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(120f, 680f)
                horizontalLineToRelative(720f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(880f, 720f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(840f, 760f)
                horizontalLineTo(120f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(80f, 720f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(120f, 680f)
                close()
                moveToRelative(40f, -222f)
                lineToRelative(-19f, 34f)
                quadToRelative(-6f, 11f, -18f, 14f)
                reflectiveQuadToRelative(-23f, -3f)
                quadToRelative(-11f, -6f, -14f, -18f)
                reflectiveQuadToRelative(3f, -23f)
                lineToRelative(19f, -34f)
                horizontalLineTo(70f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(40f, 398f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(70f, 368f)
                horizontalLineToRelative(38f)
                lineToRelative(-19f, -32f)
                quadToRelative(-6f, -11f, -3f, -23f)
                reflectiveQuadToRelative(14f, -18f)
                quadToRelative(11f, -6f, 23f, -3f)
                reflectiveQuadToRelative(18f, 14f)
                lineToRelative(19f, 32f)
                lineToRelative(19f, -32f)
                quadToRelative(6f, -11f, 18f, -14f)
                reflectiveQuadToRelative(23f, 3f)
                quadToRelative(11f, 6f, 14f, 18f)
                reflectiveQuadToRelative(-3f, 23f)
                lineToRelative(-19f, 32f)
                horizontalLineToRelative(38f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(280f, 398f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(250f, 428f)
                horizontalLineToRelative(-38f)
                lineToRelative(19f, 34f)
                quadToRelative(6f, 11f, 3f, 23f)
                reflectiveQuadToRelative(-14f, 18f)
                quadToRelative(-11f, 6f, -23f, 3f)
                reflectiveQuadToRelative(-18f, -14f)
                lineToRelative(-19f, -34f)
                close()
                moveToRelative(320f, 0f)
                lineToRelative(-19f, 34f)
                quadToRelative(-6f, 11f, -18f, 14f)
                reflectiveQuadToRelative(-23f, -3f)
                quadToRelative(-11f, -6f, -14f, -18f)
                reflectiveQuadToRelative(3f, -23f)
                lineToRelative(19f, -34f)
                horizontalLineToRelative(-38f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(360f, 398f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(390f, 368f)
                horizontalLineToRelative(38f)
                lineToRelative(-19f, -32f)
                quadToRelative(-6f, -11f, -3f, -23f)
                reflectiveQuadToRelative(14f, -18f)
                quadToRelative(11f, -6f, 23f, -3f)
                reflectiveQuadToRelative(18f, 14f)
                lineToRelative(19f, 32f)
                lineToRelative(19f, -32f)
                quadToRelative(6f, -11f, 18f, -14f)
                reflectiveQuadToRelative(23f, 3f)
                quadToRelative(11f, 6f, 14f, 18f)
                reflectiveQuadToRelative(-3f, 23f)
                lineToRelative(-19f, 32f)
                horizontalLineToRelative(38f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(600f, 398f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(570f, 428f)
                horizontalLineToRelative(-38f)
                lineToRelative(19f, 34f)
                quadToRelative(6f, 11f, 3f, 23f)
                reflectiveQuadToRelative(-14f, 18f)
                quadToRelative(-11f, 6f, -23f, 3f)
                reflectiveQuadToRelative(-18f, -14f)
                lineToRelative(-19f, -34f)
                close()
                moveToRelative(320f, 0f)
                lineToRelative(-19f, 34f)
                quadToRelative(-6f, 11f, -18f, 14f)
                reflectiveQuadToRelative(-23f, -3f)
                quadToRelative(-11f, -6f, -14f, -18f)
                reflectiveQuadToRelative(3f, -23f)
                lineToRelative(19f, -34f)
                horizontalLineToRelative(-38f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(680f, 398f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(710f, 368f)
                horizontalLineToRelative(38f)
                lineToRelative(-19f, -32f)
                quadToRelative(-6f, -11f, -3f, -23f)
                reflectiveQuadToRelative(14f, -18f)
                quadToRelative(11f, -6f, 23f, -3f)
                reflectiveQuadToRelative(18f, 14f)
                lineToRelative(19f, 32f)
                lineToRelative(19f, -32f)
                quadToRelative(6f, -11f, 18f, -14f)
                reflectiveQuadToRelative(23f, 3f)
                quadToRelative(11f, 6f, 14f, 18f)
                reflectiveQuadToRelative(-3f, 23f)
                lineToRelative(-19f, 32f)
                horizontalLineToRelative(38f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(920f, 398f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(890f, 428f)
                horizontalLineToRelative(-38f)
                lineToRelative(19f, 34f)
                quadToRelative(6f, 11f, 3f, 23f)
                reflectiveQuadToRelative(-14f, 18f)
                quadToRelative(-11f, 6f, -23f, 3f)
                reflectiveQuadToRelative(-18f, -14f)
                lineToRelative(-19f, -34f)
                close()
            }
        }.build()
        
        return _Password!!
    }

private var _Password: ImageVector? = null

