package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Respiratory_rate: ImageVector
    get() {
        if (_Respiratory_rate != null) return _Respiratory_rate!!
        
        _Respiratory_rate = ImageVector.Builder(
            name = "respiratory_rate",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(480f, 480f)
                close()
                moveTo(80f, 320f)
                verticalLineToRelative(-80f)
                quadToRelative(0f, -33f, 23.5f, -56.5f)
                reflectiveQuadTo(160f, 160f)
                horizontalLineToRelative(640f)
                quadToRelative(33f, 0f, 56.5f, 23.5f)
                reflectiveQuadTo(880f, 240f)
                verticalLineToRelative(180f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(840f, 460f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(800f, 420f)
                verticalLineToRelative(-180f)
                horizontalLineTo(160f)
                verticalLineToRelative(80f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(120f, 360f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(80f, 320f)
                close()
                moveToRelative(80f, 480f)
                quadToRelative(-33f, 0f, -56.5f, -23.5f)
                reflectiveQuadTo(80f, 720f)
                verticalLineToRelative(-80f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(120f, 600f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(160f, 640f)
                verticalLineToRelative(80f)
                horizontalLineToRelative(180f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(380f, 760f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(340f, 800f)
                horizontalLineTo(160f)
                close()
                moveToRelative(120f, -120f)
                quadToRelative(-11f, 0f, -21f, -5.5f)
                reflectiveQuadTo(244f, 658f)
                lineToRelative(-68f, -138f)
                horizontalLineToRelative(-55f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(81f, 480f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(121f, 440f)
                horizontalLineToRelative(80f)
                quadToRelative(11f, 0f, 20.5f, 6f)
                reflectiveQuadToRelative(14.5f, 16f)
                lineToRelative(44f, 88f)
                lineToRelative(124f, -248f)
                quadToRelative(5f, -10f, 15f, -15f)
                reflectiveQuadToRelative(21f, -5f)
                quadToRelative(11f, 0f, 21f, 5f)
                reflectiveQuadToRelative(15f, 15f)
                lineToRelative(79f, 159f)
                quadToRelative(-21f, 2f, -39.5f, 9f)
                reflectiveQuadTo(481f, 490f)
                lineToRelative(-41f, -80f)
                lineToRelative(-124f, 248f)
                quadToRelative(-5f, 11f, -15f, 16.5f)
                reflectiveQuadToRelative(-21f, 5.5f)
                close()
                moveTo(500f, 920f)
                quadToRelative(-25f, 0f, -42.5f, -17.5f)
                reflectiveQuadTo(440f, 860f)
                verticalLineToRelative(-132f)
                quadToRelative(0f, -8f, 1.5f, -15f)
                reflectiveQuadToRelative(3.5f, -14f)
                lineToRelative(48f, -127f)
                quadToRelative(9f, -23f, 29.5f, -37.5f)
                reflectiveQuadTo(568f, 520f)
                horizontalLineToRelative(72f)
                verticalLineToRelative(-40f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(680f, 440f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(720f, 480f)
                verticalLineToRelative(40f)
                horizontalLineToRelative(72f)
                quadToRelative(25f, 0f, 45.5f, 14.5f)
                reflectiveQuadTo(867f, 572f)
                lineToRelative(48f, 127f)
                quadToRelative(2f, 7f, 3.5f, 14f)
                reflectiveQuadToRelative(1.5f, 15f)
                verticalLineToRelative(132f)
                quadToRelative(0f, 25f, -17.5f, 42.5f)
                reflectiveQuadTo(860f, 920f)
                horizontalLineToRelative(-80f)
                quadToRelative(-25f, 0f, -42.5f, -17.5f)
                reflectiveQuadTo(720f, 860f)
                verticalLineToRelative(-20f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(760f, 800f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(800f, 840f)
                horizontalLineToRelative(40f)
                verticalLineToRelative(-113f)
                lineToRelative(-48f, -127f)
                horizontalLineToRelative(-72f)
                verticalLineToRelative(37f)
                lineToRelative(38f, 39f)
                quadToRelative(11f, 12f, 11f, 28.5f)
                reflectiveQuadTo(758f, 732f)
                quadToRelative(-11f, 11f, -28f, 11f)
                reflectiveQuadToRelative(-28f, -11f)
                lineToRelative(-22f, -22f)
                lineToRelative(-22f, 22f)
                quadToRelative(-11f, 11f, -27.5f, 11.5f)
                reflectiveQuadTo(602f, 732f)
                quadToRelative(-11f, -11f, -11f, -28f)
                reflectiveQuadToRelative(11f, -28f)
                lineToRelative(38f, -39f)
                verticalLineToRelative(-37f)
                horizontalLineToRelative(-72f)
                lineToRelative(-48f, 127f)
                verticalLineToRelative(113f)
                horizontalLineToRelative(40f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(600f, 800f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(640f, 840f)
                verticalLineToRelative(20f)
                quadToRelative(0f, 25f, -17.5f, 42.5f)
                reflectiveQuadTo(580f, 920f)
                horizontalLineToRelative(-80f)
                close()
                moveToRelative(180f, -200f)
                close()
                moveToRelative(-78f, -44f)
                lineToRelative(38f, -39f)
                verticalLineToRelative(-37f)
                verticalLineToRelative(37f)
                lineToRelative(-38f, 39f)
                close()
                moveToRelative(156f, 0f)
                lineToRelative(-38f, -39f)
                verticalLineToRelative(-37f)
                verticalLineToRelative(37f)
                lineToRelative(38f, 39f)
                close()
            }
        }.build()
        
        return _Respiratory_rate!!
    }

private var _Respiratory_rate: ImageVector? = null

