package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Sauna: ImageVector
    get() {
        if (_Sauna != null) return _Sauna!!
        
        _Sauna = ImageVector.Builder(
            name = "sauna",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(160f, 880f)
                quadToRelative(-33f, 0f, -56.5f, -23.5f)
                reflectiveQuadTo(80f, 800f)
                verticalLineToRelative(-640f)
                quadToRelative(0f, -33f, 23.5f, -56.5f)
                reflectiveQuadTo(160f, 80f)
                horizontalLineToRelative(640f)
                quadToRelative(33f, 0f, 56.5f, 23.5f)
                reflectiveQuadTo(880f, 160f)
                verticalLineToRelative(640f)
                quadToRelative(0f, 33f, -23.5f, 56.5f)
                reflectiveQuadTo(800f, 880f)
                horizontalLineTo(160f)
                close()
                moveToRelative(0f, -240f)
                verticalLineToRelative(160f)
                horizontalLineToRelative(80f)
                verticalLineToRelative(-80f)
                horizontalLineToRelative(-20f)
                quadToRelative(-8f, 0f, -14f, -6f)
                reflectiveQuadToRelative(-6f, -14f)
                verticalLineToRelative(-60f)
                horizontalLineToRelative(-40f)
                close()
                moveToRelative(0f, -80f)
                horizontalLineToRelative(40f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(240f, 520f)
                verticalLineToRelative(-100f)
                quadToRelative(0f, -25f, 17.5f, -42.5f)
                reflectiveQuadTo(300f, 360f)
                horizontalLineToRelative(80f)
                quadToRelative(25f, 0f, 42.5f, 17.5f)
                reflectiveQuadTo(440f, 420f)
                verticalLineToRelative(100f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(480f, 560f)
                horizontalLineToRelative(320f)
                verticalLineToRelative(-400f)
                horizontalLineTo(160f)
                verticalLineToRelative(400f)
                close()
                moveToRelative(100f, 100f)
                horizontalLineToRelative(160f)
                verticalLineToRelative(-80f)
                horizontalLineTo(260f)
                verticalLineToRelative(80f)
                close()
                moveToRelative(80f, -340f)
                quadToRelative(-25f, 0f, -42.5f, -17.5f)
                reflectiveQuadTo(280f, 260f)
                quadToRelative(0f, -25f, 17.5f, -42.5f)
                reflectiveQuadTo(340f, 200f)
                quadToRelative(25f, 0f, 42.5f, 17.5f)
                reflectiveQuadTo(400f, 260f)
                quadToRelative(0f, 25f, -17.5f, 42.5f)
                reflectiveQuadTo(340f, 320f)
                close()
                moveToRelative(-20f, 480f)
                horizontalLineToRelative(40f)
                verticalLineToRelative(-80f)
                horizontalLineToRelative(-40f)
                verticalLineToRelative(80f)
                close()
                moveToRelative(120f, 0f)
                horizontalLineToRelative(360f)
                verticalLineToRelative(-160f)
                horizontalLineTo(480f)
                verticalLineToRelative(60f)
                quadToRelative(0f, 8f, -6f, 14f)
                reflectiveQuadToRelative(-14f, 6f)
                horizontalLineToRelative(-20f)
                verticalLineToRelative(80f)
                close()
                moveToRelative(30f, -481f)
                quadToRelative(-15f, -19f, -22.5f, -38f)
                reflectiveQuadToRelative(-7.5f, -39f)
                verticalLineToRelative(-12f)
                quadToRelative(1f, -12f, 9.5f, -21f)
                reflectiveQuadToRelative(20.5f, -9f)
                quadToRelative(13f, 0f, 22f, 8.5f)
                reflectiveQuadToRelative(8f, 21.5f)
                verticalLineToRelative(12f)
                quadToRelative(0f, 11f, 4.5f, 21.5f)
                reflectiveQuadTo(520f, 286f)
                quadToRelative(18f, 22f, 26f, 41.5f)
                reflectiveQuadToRelative(8f, 40.5f)
                quadToRelative(0f, 13f, -9f, 22.5f)
                reflectiveQuadToRelative(-22f, 9.5f)
                quadToRelative(-13f, 0f, -21.5f, -9.5f)
                reflectiveQuadTo(493f, 368f)
                quadToRelative(0f, -12f, -4.5f, -22f)
                reflectiveQuadTo(470f, 319f)
                close()
                moveToRelative(100f, 0f)
                quadToRelative(-15f, -19f, -22.5f, -38f)
                reflectiveQuadToRelative(-7.5f, -39f)
                verticalLineToRelative(-12f)
                quadToRelative(1f, -12f, 9.5f, -21f)
                reflectiveQuadToRelative(20.5f, -9f)
                quadToRelative(13f, 0f, 22f, 8.5f)
                reflectiveQuadToRelative(8f, 21.5f)
                verticalLineToRelative(12f)
                quadToRelative(0f, 11f, 4.5f, 21.5f)
                reflectiveQuadTo(620f, 286f)
                quadToRelative(18f, 22f, 26f, 41.5f)
                reflectiveQuadToRelative(8f, 40.5f)
                quadToRelative(0f, 13f, -9f, 22.5f)
                reflectiveQuadToRelative(-22f, 9.5f)
                quadToRelative(-13f, 0f, -21.5f, -9.5f)
                reflectiveQuadTo(593f, 368f)
                quadToRelative(0f, -12f, -4.5f, -22f)
                reflectiveQuadTo(570f, 319f)
                close()
                moveToRelative(102f, 0f)
                quadToRelative(-15f, -19f, -22.5f, -38f)
                reflectiveQuadToRelative(-7.5f, -39f)
                verticalLineToRelative(-12f)
                quadToRelative(1f, -12f, 9.5f, -21f)
                reflectiveQuadToRelative(20.5f, -9f)
                quadToRelative(13f, 0f, 22f, 8.5f)
                reflectiveQuadToRelative(8f, 21.5f)
                verticalLineToRelative(12f)
                quadToRelative(0f, 11f, 4.5f, 21.5f)
                reflectiveQuadTo(722f, 286f)
                quadToRelative(18f, 22f, 26f, 41.5f)
                reflectiveQuadToRelative(8f, 40.5f)
                quadToRelative(0f, 13f, -9f, 22.5f)
                reflectiveQuadToRelative(-22f, 9.5f)
                quadToRelative(-13f, 0f, -21.5f, -9.5f)
                reflectiveQuadTo(695f, 368f)
                quadToRelative(0f, -12f, -4.5f, -22f)
                reflectiveQuadTo(672f, 319f)
                close()
                moveTo(260f, 660f)
                verticalLineToRelative(-80f)
                verticalLineToRelative(80f)
                close()
            }
        }.build()
        
        return _Sauna!!
    }

private var _Sauna: ImageVector? = null

