package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Scoreboard: ImageVector
    get() {
        if (_Scoreboard != null) return _Scoreboard!!
        
        _Scoreboard = ImageVector.Builder(
            name = "scoreboard",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(620f, 600f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(580f, 560f)
                verticalLineToRelative(-160f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(620f, 360f)
                horizontalLineToRelative(100f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(760f, 400f)
                verticalLineToRelative(160f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(720f, 600f)
                horizontalLineTo(620f)
                close()
                moveToRelative(20f, -60f)
                horizontalLineToRelative(60f)
                verticalLineToRelative(-120f)
                horizontalLineToRelative(-60f)
                verticalLineToRelative(120f)
                close()
                moveToRelative(-380f, 0f)
                horizontalLineToRelative(90f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(380f, 570f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(350f, 600f)
                horizontalLineTo(240f)
                quadToRelative(-17f, 0f, -28.5f, -11.5f)
                reflectiveQuadTo(200f, 560f)
                verticalLineToRelative(-60f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(240f, 460f)
                horizontalLineToRelative(80f)
                verticalLineToRelative(-40f)
                horizontalLineToRelative(-90f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(200f, 390f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(230f, 360f)
                horizontalLineToRelative(110f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(380f, 400f)
                verticalLineToRelative(60f)
                quadToRelative(0f, 17f, -11.5f, 28.5f)
                reflectiveQuadTo(340f, 500f)
                horizontalLineToRelative(-80f)
                verticalLineToRelative(40f)
                close()
                moveTo(160f, 800f)
                quadToRelative(-33f, 0f, -56.5f, -23.5f)
                reflectiveQuadTo(80f, 720f)
                verticalLineToRelative(-480f)
                quadToRelative(0f, -33f, 23.5f, -56.5f)
                reflectiveQuadTo(160f, 160f)
                horizontalLineToRelative(120f)
                verticalLineToRelative(-40f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(320f, 80f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(360f, 120f)
                verticalLineToRelative(40f)
                horizontalLineToRelative(240f)
                verticalLineToRelative(-40f)
                quadToRelative(0f, -17f, 11.5f, -28.5f)
                reflectiveQuadTo(640f, 80f)
                quadToRelative(17f, 0f, 28.5f, 11.5f)
                reflectiveQuadTo(680f, 120f)
                verticalLineToRelative(40f)
                horizontalLineToRelative(120f)
                quadToRelative(33f, 0f, 56.5f, 23.5f)
                reflectiveQuadTo(880f, 240f)
                verticalLineToRelative(480f)
                quadToRelative(0f, 33f, -23.5f, 56.5f)
                reflectiveQuadTo(800f, 800f)
                horizontalLineTo(160f)
                close()
                moveToRelative(0f, -80f)
                horizontalLineToRelative(290f)
                verticalLineToRelative(-30f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(480f, 660f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(510f, 690f)
                verticalLineToRelative(30f)
                horizontalLineToRelative(290f)
                verticalLineToRelative(-480f)
                horizontalLineTo(510f)
                verticalLineToRelative(30f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(480f, 300f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(450f, 270f)
                verticalLineToRelative(-30f)
                horizontalLineTo(160f)
                verticalLineToRelative(480f)
                close()
                moveToRelative(0f, 0f)
                verticalLineToRelative(-480f)
                verticalLineToRelative(480f)
                close()
                moveToRelative(320f, -280f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(450f, 410f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(480f, 380f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(510f, 410f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(480f, 440f)
                close()
                moveToRelative(0f, 140f)
                quadToRelative(-13f, 0f, -21.5f, -8.5f)
                reflectiveQuadTo(450f, 550f)
                quadToRelative(0f, -13f, 8.5f, -21.5f)
                reflectiveQuadTo(480f, 520f)
                quadToRelative(13f, 0f, 21.5f, 8.5f)
                reflectiveQuadTo(510f, 550f)
                quadToRelative(0f, 13f, -8.5f, 21.5f)
                reflectiveQuadTo(480f, 580f)
                close()
            }
        }.build()
        
        return _Scoreboard!!
    }

private var _Scoreboard: ImageVector? = null

