package com.composables.icons.materialsymbols.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.materialsymbols.MaterialSymbols
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialSymbols.Rounded.Settings_panorama: ImageVector
    get() {
        if (_Settings_panorama != null) return _Settings_panorama!!
        
        _Settings_panorama = ImageVector.Builder(
            name = "settings_panorama",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(570f, 878f)
                quadToRelative(-19f, 5f, -34.5f, -6.5f)
                reflectiveQuadTo(520f, 840f)
                verticalLineToRelative(-200f)
                quadToRelative(0f, -20f, 15.5f, -31.5f)
                reflectiveQuadTo(571f, 602f)
                quadToRelative(37f, 10f, 74f, 14f)
                reflectiveQuadToRelative(75f, 4f)
                quadToRelative(38f, 0f, 75.5f, -4f)
                reflectiveQuadToRelative(74.5f, -14f)
                quadToRelative(19f, -5f, 34.5f, 6.5f)
                reflectiveQuadTo(920f, 640f)
                verticalLineToRelative(200f)
                quadToRelative(0f, 20f, -15.5f, 31.5f)
                reflectiveQuadTo(870f, 878f)
                quadToRelative(-37f, -10f, -74.5f, -14f)
                reflectiveQuadToRelative(-75.5f, -4f)
                quadToRelative(-38f, 0f, -75.5f, 4f)
                reflectiveQuadTo(570f, 878f)
                close()
                moveToRelative(-90f, -398f)
                close()
                moveToRelative(0f, 0f)
                close()
                moveTo(440f, 880f)
                horizontalLineToRelative(-35f)
                quadToRelative(-15f, 0f, -26f, -10f)
                reflectiveQuadToRelative(-13f, -25f)
                lineToRelative(-12f, -91f)
                quadToRelative(-13f, -5f, -24.5f, -12f)
                reflectiveQuadTo(307f, 727f)
                lineToRelative(-62f, 26f)
                quadToRelative(-25f, 11f, -50f, 2f)
                reflectiveQuadToRelative(-39f, -32f)
                lineToRelative(-47f, -82f)
                quadToRelative(-14f, -23f, -8f, -49f)
                reflectiveQuadToRelative(27f, -43f)
                lineToRelative(53f, -40f)
                quadToRelative(-1f, -7f, -1f, -13.5f)
                verticalLineToRelative(-27f)
                quadToRelative(0f, -6.5f, 1f, -13.5f)
                lineToRelative(-53f, -40f)
                quadToRelative(-21f, -17f, -27f, -43f)
                reflectiveQuadToRelative(8f, -49f)
                lineToRelative(47f, -82f)
                quadToRelative(14f, -23f, 39f, -32f)
                reflectiveQuadToRelative(50f, 2f)
                lineToRelative(62f, 26f)
                quadToRelative(11f, -8f, 23f, -15f)
                reflectiveQuadToRelative(24f, -12f)
                lineToRelative(8f, -66f)
                quadToRelative(3f, -27f, 23f, -44.5f)
                reflectiveQuadToRelative(47f, -17.5f)
                horizontalLineToRelative(96f)
                quadToRelative(27f, 0f, 47f, 17.5f)
                reflectiveQuadToRelative(23f, 44.5f)
                lineToRelative(8f, 66f)
                quadToRelative(13f, 5f, 24.5f, 12f)
                reflectiveQuadToRelative(22.5f, 15f)
                lineToRelative(60f, -26f)
                quadToRelative(25f, -11f, 50.5f, -2f)
                reflectiveQuadToRelative(39.5f, 32f)
                lineToRelative(47f, 82f)
                quadToRelative(14f, 23f, 8.5f, 49f)
                reflectiveQuadTo(832f, 415f)
                lineToRelative(-53f, 38f)
                quadToRelative(1f, 7f, 1f, 13f)
                verticalLineToRelative(13f)
                quadToRelative(0f, 17f, -12.5f, 29f)
                reflectiveQuadTo(737f, 520f)
                quadToRelative(-16f, 0f, -26.5f, -12f)
                reflectiveQuadTo(700f, 479f)
                quadToRelative(0f, -15f, -2f, -30f)
                reflectiveQuadToRelative(-7f, -30f)
                lineToRelative(86f, -65f)
                lineToRelative(-39f, -68f)
                lineToRelative(-99f, 42f)
                quadToRelative(-22f, -23f, -48.5f, -38.5f)
                reflectiveQuadTo(533f, 266f)
                lineToRelative(-13f, -106f)
                horizontalLineToRelative(-79f)
                lineToRelative(-14f, 106f)
                quadToRelative(-31f, 8f, -57.5f, 23.5f)
                reflectiveQuadTo(321f, 327f)
                lineToRelative(-99f, -41f)
                lineToRelative(-39f, 68f)
                lineToRelative(86f, 64f)
                quadToRelative(-5f, 15f, -7f, 30f)
                reflectiveQuadToRelative(-2f, 32f)
                quadToRelative(0f, 16f, 2f, 31f)
                reflectiveQuadToRelative(7f, 30f)
                lineToRelative(-86f, 65f)
                lineToRelative(39f, 68f)
                lineToRelative(99f, -42f)
                quadToRelative(24f, 25f, 54f, 42f)
                reflectiveQuadToRelative(65f, 22f)
                verticalLineToRelative(184f)
                close()
                moveToRelative(42f, -540f)
                quadToRelative(56f, 0f, 96f, 38f)
                reflectiveQuadToRelative(44f, 94f)
                quadToRelative(2f, 20f, -9.5f, 35.5f)
                reflectiveQuadTo(581f, 524f)
                quadToRelative(-17f, 1f, -29.5f, -10.5f)
                reflectiveQuadTo(541f, 485f)
                quadToRelative(4f, -26f, -14f, -45.5f)
                reflectiveQuadTo(482f, 420f)
                quadToRelative(-25f, 0f, -42.5f, 17.5f)
                reflectiveQuadTo(422f, 480f)
                quadToRelative(0f, 14f, 5.5f, 25.5f)
                reflectiveQuadTo(443f, 525f)
                quadToRelative(11f, 10f, 10f, 25.5f)
                reflectiveQuadTo(440f, 577f)
                quadToRelative(-14f, 12f, -32.5f, 10.5f)
                reflectiveQuadTo(376f, 572f)
                quadToRelative(-18f, -18f, -26f, -42f)
                reflectiveQuadToRelative(-8f, -50f)
                quadToRelative(0f, -59f, 41f, -99.5f)
                reflectiveQuadToRelative(99f, -40.5f)
                close()
            }
        }.build()
        
        return _Settings_panorama!!
    }

private var _Settings_panorama: ImageVector? = null

