package com.composables.icons.fontawesome.solid

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.fontawesome.FontAwesome
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val FontAwesome.Solid.ChessBoard: ImageVector
    get() {
        if (_ChessBoard != null) return _ChessBoard!!
        
        _ChessBoard = ImageVector.Builder(
            name = "chess-board",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 512f,
            viewportHeight = 512f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(255.9f, 0.2f)
                horizontalLineToRelative(-64f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                close()
                moveTo(0f, 64.17f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                close()
                moveTo(128f, 0.2f)
                horizontalLineTo(64f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                close()
                moveToRelative(64f, 255.9f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                close()
                moveTo(0f, 192.12f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                close()
                moveTo(383.85f, 0.2f)
                horizontalLineToRelative(-64f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                close()
                moveToRelative(128f, 0f)
                horizontalLineToRelative(-64f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                close()
                moveTo(128f, 256.1f)
                horizontalLineTo(64f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                close()
                moveTo(511.8f, 448f)
                verticalLineToRelative(-64f)
                horizontalLineToRelative(-64f)
                verticalLineToRelative(64f)
                close()
                moveToRelative(0f, -128f)
                verticalLineToRelative(-64f)
                horizontalLineToRelative(-64f)
                verticalLineToRelative(64f)
                close()
                moveTo(383.85f, 512f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                horizontalLineToRelative(-64f)
                close()
                moveToRelative(128f, -319.88f)
                verticalLineToRelative(-64f)
                horizontalLineToRelative(-64f)
                verticalLineToRelative(64f)
                close()
                moveTo(128f, 512f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                horizontalLineToRelative(-64f)
                close()
                moveTo(0f, 512f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                horizontalLineTo(0f)
                close()
                moveToRelative(255.9f, 0f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                horizontalLineToRelative(-64f)
                close()
                moveTo(0f, 320.07f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                close()
                moveToRelative(319.88f, -191.92f)
                verticalLineToRelative(-64f)
                horizontalLineToRelative(-64f)
                verticalLineToRelative(64f)
                close()
                moveToRelative(-64f, 128f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                horizontalLineToRelative(-64f)
                close()
                moveToRelative(-64f, 128f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                close()
                moveToRelative(128f, -64f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                horizontalLineToRelative(-64f)
                close()
                moveToRelative(0f, -127.95f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                horizontalLineToRelative(-64f)
                close()
                moveToRelative(0f, 191.93f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                close()
                moveTo(64f, 384.05f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                close()
                moveToRelative(128f, -255.9f)
                verticalLineToRelative(-64f)
                horizontalLineToRelative(-64f)
                verticalLineToRelative(64f)
                close()
                moveToRelative(191.92f, 255.9f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                horizontalLineToRelative(-64f)
                close()
                moveToRelative(-128f, -191.93f)
                verticalLineToRelative(-64f)
                horizontalLineToRelative(-64f)
                verticalLineToRelative(64f)
                close()
                moveToRelative(128f, -127.95f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                close()
                moveToRelative(-128f, 255.9f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                close()
                moveToRelative(-64f, -127.95f)
                horizontalLineTo(128f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                close()
                moveToRelative(191.92f, 64f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                horizontalLineToRelative(-64f)
                close()
                moveTo(128f, 128.15f)
                horizontalLineTo(64f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                close()
                moveToRelative(0f, 191.92f)
                verticalLineToRelative(64f)
                horizontalLineToRelative(64f)
                verticalLineToRelative(-64f)
                close()
            }
        }.build()
        
        return _ChessBoard!!
    }

private var _ChessBoard: ImageVector? = null

