package com.composables.icons.fontawesome.solid

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import com.composables.icons.fontawesome.FontAwesome
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val FontAwesome.Solid.Microchip: ImageVector
    get() {
        if (_Microchip != null) return _Microchip!!
        
        _Microchip = ImageVector.Builder(
            name = "microchip",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 512f,
            viewportHeight = 512f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(416f, 48f)
                verticalLineToRelative(416f)
                curveToRelative(0f, 26.51f, -21.49f, 48f, -48f, 48f)
                horizontalLineTo(144f)
                curveToRelative(-26.51f, 0f, -48f, -21.49f, -48f, -48f)
                verticalLineTo(48f)
                curveToRelative(0f, -26.51f, 21.49f, -48f, 48f, -48f)
                horizontalLineToRelative(224f)
                curveToRelative(26.51f, 0f, 48f, 21.49f, 48f, 48f)
                close()
                moveToRelative(96f, 58f)
                verticalLineToRelative(12f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, 6f)
                horizontalLineToRelative(-18f)
                verticalLineToRelative(6f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, 6f)
                horizontalLineToRelative(-42f)
                verticalLineTo(88f)
                horizontalLineToRelative(42f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, 6f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(18f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, 6f)
                close()
                moveToRelative(0f, 96f)
                verticalLineToRelative(12f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, 6f)
                horizontalLineToRelative(-18f)
                verticalLineToRelative(6f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, 6f)
                horizontalLineToRelative(-42f)
                verticalLineToRelative(-48f)
                horizontalLineToRelative(42f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, 6f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(18f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, 6f)
                close()
                moveToRelative(0f, 96f)
                verticalLineToRelative(12f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, 6f)
                horizontalLineToRelative(-18f)
                verticalLineToRelative(6f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, 6f)
                horizontalLineToRelative(-42f)
                verticalLineToRelative(-48f)
                horizontalLineToRelative(42f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, 6f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(18f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, 6f)
                close()
                moveToRelative(0f, 96f)
                verticalLineToRelative(12f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, 6f)
                horizontalLineToRelative(-18f)
                verticalLineToRelative(6f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, 6f)
                horizontalLineToRelative(-42f)
                verticalLineToRelative(-48f)
                horizontalLineToRelative(42f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, 6f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(18f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, 6f)
                close()
                moveTo(30f, 376f)
                horizontalLineToRelative(42f)
                verticalLineToRelative(48f)
                horizontalLineTo(30f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, -6f)
                verticalLineToRelative(-6f)
                horizontalLineTo(6f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, -6f)
                verticalLineToRelative(-12f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, -6f)
                horizontalLineToRelative(18f)
                verticalLineToRelative(-6f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, -6f)
                close()
                moveToRelative(0f, -96f)
                horizontalLineToRelative(42f)
                verticalLineToRelative(48f)
                horizontalLineTo(30f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, -6f)
                verticalLineToRelative(-6f)
                horizontalLineTo(6f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, -6f)
                verticalLineToRelative(-12f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, -6f)
                horizontalLineToRelative(18f)
                verticalLineToRelative(-6f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, -6f)
                close()
                moveToRelative(0f, -96f)
                horizontalLineToRelative(42f)
                verticalLineToRelative(48f)
                horizontalLineTo(30f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, -6f)
                verticalLineToRelative(-6f)
                horizontalLineTo(6f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, -6f)
                verticalLineToRelative(-12f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, -6f)
                horizontalLineToRelative(18f)
                verticalLineToRelative(-6f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, -6f)
                close()
                moveToRelative(0f, -96f)
                horizontalLineToRelative(42f)
                verticalLineToRelative(48f)
                horizontalLineTo(30f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, -6f)
                verticalLineToRelative(-6f)
                horizontalLineTo(6f)
                arcToRelative(6f, 6f, 0f, false, true, -6f, -6f)
                verticalLineToRelative(-12f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, -6f)
                horizontalLineToRelative(18f)
                verticalLineToRelative(-6f)
                arcToRelative(6f, 6f, 0f, false, true, 6f, -6f)
                close()
            }
        }.build()
        
        return _Microchip!!
    }

private var _Microchip: ImageVector? = null

